Support additional fuels BEIS (bioenergy)
climatiq/Open-Emission-Factors-DB pull request #100
Opened 2021-12-14 08:37 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Fuel

**What?**

Additional bioenergy fuel emission factors 

**Why?**

Biomethane, biogas, and biomass were not supported.

2021-12-15 09:35 UTC, maryarbab requested changes
Great addition! Why do we include both units for each EF? Also, BEIS has “out of scope” emissions tab for bioenergy that we might want to consider to add.

2021-12-16 07:51 UTC, greenercode commented
> Great addition! Why do we include both units for each EF? Also, BEIS has “out of scope” emissions tab for bioenergy that we might want to consider to add.

@patstirling @maryarbab @AnastasiaLobanova  outside of scope ones include more than just bioenergy - should these be added in the same PR or in a subsequent one?

2021-12-16 13:53 UTC, AnastasiaLobanova requested changes

2021-12-16 13:53 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_me_from_tallow-fuel_use_na,Biodiesel ME (from tallow),kg-CO2e/kg,0.16751,,BEIS,2021,GB,2021/12/14,Emission intensity of biodiesel ME (from tallow). Bioenergy conversio
And also from was not used before, e.g. line above

2021-12-16 13:53 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_me_from_tallow-fuel_use_na,Biodiesel ME (from tallow),kg-CO2e/kg,0.16751,,BEIS,2021,GB,2021/12/14,Emission intensity of biodiesel ME (from tallow). Bioenergy conversio
Is the value of this EF correct? bc the units are different from the one above but the value is the same (I assume the density of diesel is higher than 1...)

2021-12-16 23:02 UTC, maryarbab submitted a review, later dismissed

2021-12-17 07:04 UTC, AnastasiaLobanova approved these changes

2021-12-20 20:07 UTC, AnastasiaLobanova approved these changes

2021-12-21 07:56 UTC, merged