adding EPA spend-based (commodity) EFs
climatiq/Open-Emission-Factors-DB pull request #101
Opened 2021-12-14 09:20 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Multiple, including the introduction of new categories

**What?**

Adding spend-based EFs from the EPA source

**Why?**

This is a part of a major addition of the spend-based EFs from various sources to the OEFDB

2021-12-17 13:28 UTC, patstirling requested changes
Looks super at first review - there's a couple of small changes that will need to be made to make full review possible:

- re-order by sector > category > name
- there seems to have been a mismatch in description from a certain point - marked with a comment in the DB
- `lca_activity` field: "cradle_to_shelve" -> "cradle_to_shelf"

2021-12-17 13:28 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Equipment,Electronics,electronics-type_electromedical_appartuses,Electromedical appartuses,kg-CO2e/USD,0.097,,EPA,2020,USA,2021/10/12,Emission intensity of supply chain in US dollars spend on: electr
The description here appears to be a duplicate of the previous EF? It appears to have had a knock-on - each subsequent description matches the EF previous to it.

2021-12-17 13:47 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Equipment,Electronics,electronics-type_electromedical_appartuses,Electromedical appartuses,kg-CO2e/USD,0.097,,EPA,2020,USA,2021/10/12,Emission intensity of supply chain in US dollars spend on: electr
Hm that's strange.. I will check it!

2021-12-20 20:08 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Equipment,Electronics,electronics-type_electromedical_appartuses,Electromedical appartuses,kg-CO2e/USD,0.097,,EPA,2020,USA,2021/10/12,Emission intensity of supply chain in US dollars spend on: electr
Ok now it is resolved!

2021-12-21 09:15 UTC, greenercode requested changes
Other than those tiny requested changes - great PR!

2021-12-21 09:15 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_gasoline_fuels_by_products_of_petroleum_refining-fuel_use_na,Gasoline/fuels and by-products of petroleum refining,kg-CO2e/USD,0.517,,EPA,2016,USA,2021/10/12,Emission intensity o
Perhaps slightly long?

2021-12-21 09:15 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_other_petroleum_coal_products-fuel_use_na,Other petroleum and coal products,kg-CO2e/USD,0.742,,EPA,2016,USA,2021/10/12,Emission intensity of supply chain in US dollars spend on:
Perhaps slightly long ID?

2021-12-21 09:15 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Restaurants and Accommodation,Accommodation,accommodation_type_hotels_campgrounds,Hotels and campgrounds,kg-CO2e/USD,0.178,,EPA,2016,USA,2021/10/12,Emission intensity of supply chain in US dollars sp
TBR - suggestion; accommodation-type_hotels_campgrounds

2021-12-21 09:15 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Education,Education,education_type_elementary_secondary_schools,Elementary and secondary schools,kg-CO2e/USD,0.138,,EPA,2016,USA,2021/10/12,Emission intensity of supply chain in US dollars spend on:
lines 2036 - 2039 - ID line break. Suggestion; **education-type_elementary_secondary_schools**

2021-12-21 09:15 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Domestic services,domestic_services-type_household_employees,Household employees,kg-CO2e/USD,0,,EPA,2016,USA,2021/10/12,Emission intensity of supply chain in US dollars sp
**cradle_to_shelf** Is there a consensus on this wording for all spend-based LCA activities?

2022-01-07 13:31 UTC, closed without merging