Include EF electric rail travel (NZ)
climatiq/Open-Emission-Factors-DB pull request #102
Opened 2021-12-14 14:18 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Rail travel 

**What?**

Include single EF for electric rail travel (NZ)

**Why?**

We have a national average and diesel value. The electric one was not included yet.

2021-12-15 04:22 UTC, maryarbab requested changes

2021-12-15 04:22 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_nuclear_plant,Nuclear plant,kg-CO2e/kWh,0.006,10,ADEME,2018,FR,2021/11/30,Emission intensity for nuclear power plant. The data scope includes upstream emi
I would remove "plant" from the ID: electricity-energy_source_nuclear

2021-12-15 04:22 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_mainline-fuel_source_na,Mainline train,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,Emission intensity for mainline train including upstream electr
Is this part of this PR?

2021-12-15 04:22 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_nuclear_plant,Nuclear plant,kg-CO2e/kWh,0.006,10,ADEME,2018,FR,2021/11/30,Emission intensity for nuclear power plant. The data scope includes upstream emi
Should this part of this PR?

2021-12-15 07:58 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_nuclear_plant,Nuclear plant,kg-CO2e/kWh,0.006,10,ADEME,2018,FR,2021/11/30,Emission intensity for nuclear power plant. The data scope includes upstream emi
This is what I explained yesterday! The **main file** has been update with another closed PR since this one was open, and it therefore takes into account these changes. This is not supposed to show up in this PR - but because we were not quick enough to close the other ones, it does.. :/

2021-12-15 09:44 UTC, maryarbab requested changes

2021-12-15 09:44 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_urban-fuel_source_electric,Electric urban passenger train,kg-CO2e/pkm,0.03772874,,MfE,2020,NZ,2021/09/10,Emission intensity for electric urban passeng
LCA activity suggestion for the electric vehicle in this case: upstream-electricity _consumption

2021-12-15 09:44 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_mainline-fuel_source_na,Mainline train,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,Emission intensity for mainline train including upstream electr
The fuel source is unknown, so we shouldn’t have the electricity generation in the lca activity. Suggestion: upstream_fuel-combustion

2021-12-15 11:59 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_nuclear_plant,Nuclear plant,kg-CO2e/kWh,0.006,10,ADEME,2018,FR,2021/11/30,Emission intensity for nuclear power plant. The data scope includes upstream emi
This is a conflict - @grindcode could help. But it highlights why we need to not make changes to any given category while another PR is open that touches it. Also that we should try to limit the number of PRs somewhat and push for quicker reviews/corrections

2021-12-16 09:57 UTC, AnastasiaLobanova requested changes

2021-12-16 09:57 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_urban-fuel_source_electric,Electric urban passenger train,kg-CO2e/pkm,0.03772874,,MfE,2020,NZ,2021/09/10,Emission intensity for electric urban passeng
here is an extra space in the lca_actitiy column

2021-12-16 10:30 UTC, maryarbab approved these changes

2021-12-16 15:08 UTC, maryarbab approved these changes

2021-12-16 15:09 UTC, merged