WTT fuel conversion factors (BEIS)
climatiq/Open-Emission-Factors-DB pull request #106
Opened 2021-12-20 08:24 UTC by greenercode

Include WTT upstream fuel conversion factors (BEIS).

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Fuel 

**What?**

Include WTT upstream fuel conversion factors (BEIS). 

**Why?**

These are necessary for scope 3 calculations.

2021-12-20 08:52 UTC, greenercode commented
Should we make a distinction that these are WTT in the name field, or is upstream a sufficient and specific enough  reference in the descriptions and LCA fields? @patstirling @AnastasiaLobanova

2022-01-11 13:27 UTC, AnastasiaLobanova requested changes
Looks good! 

just to delete here also "-" in the name, for consistency

2022-01-20 09:30 UTC, maryarbab requested changes

2022-01-20 09:30 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation_wtt,Aviation fuel (avgas) WTT,kg-CO2e/L,0.59512,,BEIS,2021,GB,2021/12/20,"Emission intensity for aviation fuel (avgas). Well-to-Tank (WTT) fuels conversi
I don't think we need wtt in the ID as it is the LCA activity.

2022-01-20 09:30 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation_wtt,Aviation fuel (avgas) WTT,kg-CO2e/L,0.59512,,BEIS,2021,GB,2021/12/20,"Emission intensity for aviation fuel (avgas). Well-to-Tank (WTT) fuels conversi
Can you please use "Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL" for all the referencing in the descriptions across your PRs?

2022-01-20 10:13 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation_wtt,Aviation fuel (avgas) WTT,kg-CO2e/L,0.59512,,BEIS,2021,GB,2021/12/20,"Emission intensity for aviation fuel (avgas). Well-to-Tank (WTT) fuels conversi
also the Well-to-Tank in the lca_activity field can be uncapitalised

2022-01-20 10:13 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation_wtt,Aviation fuel (avgas) WTT,kg-CO2e/L,0.59512,,BEIS,2021,GB,2021/12/20,"Emission intensity for aviation fuel (avgas). Well-to-Tank (WTT) fuels conversi
This is already the case @AnastasiaLobanova :)

2022-01-20 11:11 UTC, maryarbab approved these changes

2022-01-20 11:23 UTC, AnastasiaLobanova approved these changes

2022-01-24 13:50 UTC, patstirling requested changes
commas in all description fields

2022-01-24 17:30 UTC, closed without merging