Correct grid mix values (ADEME)
climatiq/Open-Emission-Factors-DB pull request #108
Opened 2021-12-20 13:50 UTC by greenercode

Two wrongly inputted EFs for the French (overseas territories) grid mix had to be replaced with the correct values.

**Is this a new addition or an update to an existing factor?**

- [x] Update

**What category or categories does it affect?**

Electricity 

**What?**

Two wrongly inputted EFs for the French (overseas territories) grid mix had to be replaced with the correct values. 

**Why?**

Values were wrongly inputted.

2021-12-21 10:55 UTC, AnastasiaLobanova requested changes

2021-12-21 10:55 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,1.09,15,ADEME,2018,PF,2021/08/13,Emission intensity of grid mix as reported. Overseas departments and territories. French Po
Was these two a typo?

2021-12-21 10:56 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,1.09,15,ADEME,2018,PF,2021/08/13,Emission intensity of grid mix as reported. Overseas departments and territories. French Po
Yes - or rather SUPER HIGH ef values for electricity grid mix values.

2021-12-22 13:57 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,1.09,15,ADEME,2018,PF,2021/08/13,Emission intensity of grid mix as reported. Overseas departments and territories. French Po
I think the question is whether the error is at our end of at the ADEME end.

2021-12-22 13:58 UTC, patstirling approved these changes

2021-12-22 14:05 UTC, patstirling approved these changes

2021-12-22 14:06 UTC, merged