Include WTT - Bioenergy (BEIS)
climatiq/Open-Emission-Factors-DB pull request #109
Opened 2021-12-21 12:56 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Fuel 

**What?**

Includes WTT (Well-to-Tank) - Bioenergy conversion factors from BEIS). 

**Why?**

These are essential for company's scope 2 and 3 activities' reporting.

2022-01-11 13:13 UTC, AnastasiaLobanova requested changes
Nice Stephane! Also here - do we need the "-" before WTT in the name and description?

2022-01-18 14:11 UTC, maryarbab requested changes
Thank you, @greenercode! One question: Would wtt account as fuel use?

2022-01-18 14:17 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo-fuel_use_wtt,Biodiesel HVO WTT,kg-CO2e/L,0.2132,,BEIS,2021,GB,2021/12/21,"Emission intensity of biodiesel HVO WTT. Well-to-Tank (WTT) bioenergy conversion factors
Also, echoing Anastasias's comment, I don't think we need WTT in the name as it refers to the lca activity.

2022-01-18 14:17 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo-fuel_use_wtt,Biodiesel HVO WTT,kg-CO2e/L,0.2132,,BEIS,2021,GB,2021/12/21,"Emission intensity of biodiesel HVO WTT. Well-to-Tank (WTT) bioenergy conversion factors
lca activity should all be in lower case.

2022-01-18 14:17 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo-fuel_use_wtt,Biodiesel HVO WTT,kg-CO2e/L,0.2132,,BEIS,2021,GB,2021/12/21,"Emission intensity of biodiesel HVO WTT. Well-to-Tank (WTT) bioenergy conversion factors
Just adding my comment here again: WTT does not seem like fuel use to me.

2022-01-18 14:17 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo-fuel_use_wtt,Biodiesel HVO WTT,kg-CO2e/L,0.2132,,BEIS,2021,GB,2021/12/21,"Emission intensity of biodiesel HVO WTT. Well-to-Tank (WTT) bioenergy conversion factors
Please update the description of the source to reflect the latest update: Available in BEISs Greenhouse Gas Reporting: Conversion Factors 2021-flat file.

2022-01-20 09:43 UTC, maryarbab requested changes
Please use the latest reeference style for BEIS.

2022-01-20 09:43 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
What are these changes in the transport category for?

2022-01-20 09:46 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
Please ignore these @maryarbab It did the same thing in the past. It is related to previous PRs, and the since-then updated **main** file.

2022-01-20 10:00 UTC, maryarbab approved these changes

2022-01-20 11:27 UTC, AnastasiaLobanova submitted a review, later dismissed

2022-01-20 17:52 UTC, patstirling requested changes

2022-01-20 17:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo-fuel_use_na,Biodiesel HVO WTT,kg-CO2e/L,0.2132,,BEIS,2021,GB,2021/12/21,"Emission intensity of biodiesel HVO WTT. Well-to-Tank (WTT) bioenergy conversion factors s
In other PRs the form for the name field has included brackets around the term WTT - I think this is a good policy

2022-01-24 12:06 UTC, maryarbab approved these changes

2022-01-24 12:39 UTC, patstirling requested changes
Still seeing commas throughout here

2022-01-24 13:53 UTC, closed without merging