Contributing guide + PR Template
climatiq/Open-Emission-Factors-DB pull request #11
Opened 2021-09-24 14:33 UTC by igmoweb

Added a new guide to contribute and a PR template

2021-09-24 14:38 UTC, igmoweb commented
@grindcode Can you give it a look at this one?

2021-09-27 07:07 UTC, grindcode reviewed
Thank you for the changes @igmoweb. Great idea to add a guide for less experienced GitHub users. Please see the comments above.

Additionally I suggest we add guidance around commit message and pull request title writing. We don't have a strict style guide, but I think we should suggest the usage of imperative syntax for those messages, and perhaps some examples. Would be good to work in some consistency between changes at this stage already.

2021-09-27 07:07 UTC, grindcode commented on README.md
> +### 1. Edit the file
This is a simple workflow for users without git experience, I think we should highlight that fact.

2021-09-27 09:53 UTC, patstirling requested changes
Looking really great Ignacio - really simple and clear, love it. Please see my review with some tweaks around language and tone.

2021-09-27 09:53 UTC, patstirling commented on README.md
> +Thank you for thinking about contributing to the Open Emission Factors Database! To contribute by creating or updating factors in the database, follow these steps:
Suggest a slight change in tone here, and adding a reference to the fact that any submissions will be reviewed and validated - something like "It's straightforward to contribute to the Open Emission Factors Database, and by doing so you are adding value to a crucial resource for the measurement of emissions - thank you! To contribute by creating or updating factors in the database for review by the OEFDB data stewards, follow these steps:"

2021-09-27 09:53 UTC, patstirling commented on README.md
> +2. Open `OpenEmissionFactorsDB.csv` file with a CSV editor. You can work with any editor like Microsoft Office or Apple Numbers but keep an eye on the characters encoding and make sure that they are
replace "characters" with "character". Suggest we add Google sheets as one of the options, to provide balance between behemoth tech companies, and maybe nudge people towards more open/cloud based apps :)

2021-09-27 09:53 UTC, patstirling commented on README.md
> +3. Make the changes to the file. Try to keep them as short as possible and do not try to addnew factors along with other factors updates. Try to do both in separate requests.
Couple of suggested edits to the second 2 sentences: "Try to keep them as short as possible and avoid adding new factors along with other factors updates - updates and additions should be submitted in separate requests."

2021-09-27 09:53 UTC, patstirling commented on README.md
> +4. Save or export the file as a `.csv` file separated by commas.
Do we need to say "separated by commas" given that a CSV is by definition a set of comma-separated variables?

2021-09-27 09:53 UTC, patstirling commented on README.md
> +7. Back to GitHub, click on `OpenEmissionFactorsDB.csv` file and then in the edit icon.
"then **on** the edit icon"

2021-09-27 09:53 UTC, patstirling commented on README.md
> +![Edit icon](./img/edit.png)
should this go above point 8, given that it is a screen grab of point 7?

2021-09-27 09:53 UTC, patstirling commented on README.md
> +Now that you have edit your changes, you need to create a Pull Request so the changes can be reviewed before going live:
"Now that you made your changes or additions"

2021-09-27 09:53 UTC, patstirling commented on README.md
> +1. Commit the changes by completing the form. Give it a proper title and specify if you are adding or updating an existing factor and the category it belongs to. Additionally, insert a description wi
Suggest: "Give it a proper title and specify if you are adding or updating an existing factor/factors and the category it/they belong to."

Can we specify the "what" and "why" paradigm here? E.g. "Additionally, insert a description of the changes made under a bolded heading "What" and provide a brief description of why these changes are necessary or beneficial under the heading "Why". This will speed up the revision process and make clear the reasons for the contribution." <- note full stop at end of sentence needs to be added

2021-09-27 09:53 UTC, patstirling commented on README.md
> +2. Immediately after, you will be redirected to another screen to create a new Pull Request. If the title and descriptions are fine for you, click on `Create Pull Request` and wait for approval or ch
Suggest: "Immediately after clicking the commit button, you will be prompted to create a new Pull Request. Please review the title and descriptions for clarity and brevity, then click on `Create Pull Request` and wait for approval or any alterations or clarifications required by the OEFDB data stewards."

2021-09-27 10:23 UTC, grindcode commented on README.md
> +4. Save or export the file as a `.csv` file separated by commas.
I think the specification is beneficial. From [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt):

```While there are various specifications and implementations for the
   CSV format (for ex. [4], [5], [6] and [7]), there is no formal
   specification in existence, which allows for a wide variety of
   interpretations of CSV files.```

2021-09-27 16:23 UTC, greenercode approved these changes

2021-09-27 19:04 UTC, maryarbab commented on README.md
> +1. Commit the changes by completing the form. Give it a proper title and specify if you are adding or updating an existing factor and the category it belongs to. Additionally, insert a description wi
Agree.

2021-09-27 19:07 UTC, maryarbab commented on README.md
> +3. Make the changes to the file. Try to keep them as short as possible and do not try to addnew factors along with other factors updates. Try to do both in separate requests.
"Short" seems vague to me. How many changes are possible in each request?

2021-09-28 08:19 UTC, igmoweb commented on README.md
> +3. Make the changes to the file. Try to keep them as short as possible and do not try to addnew factors along with other factors updates. Try to do both in separate requests.
I've removed the `Try to keep them as short as...` but highlighted the part about avoiding updates and additions in the same request. Instead, we'll deal with long changes as they appear.

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +## How to contribute
Done!

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +### 1. Edit the file
How about now?

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +Thank you for thinking about contributing to the Open Emission Factors Database! To contribute by creating or updating factors in the database, follow these steps:
Fixed

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +2. Open `OpenEmissionFactorsDB.csv` file with a CSV editor. You can work with any editor like Microsoft Office or Apple Numbers but keep an eye on the characters encoding and make sure that they are
Fixed and added Google Spreadsheets as an option

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +![Edit icon](./img/edit.png)
Fixed

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +Now that you have edit your changes, you need to create a Pull Request so the changes can be reviewed before going live:
Fixed

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +1. Commit the changes by completing the form. Give it a proper title and specify if you are adding or updating an existing factor and the category it belongs to. Additionally, insert a description wi
Now changed. I've also added the What and Why sections in the Pull Request template, which is the content by default when you create a PR. See here: https://github.com/climatiq/Open-Emission-Factors-DB/blob/csv-update-guide/.github/pull_request_template.md

2021-09-28 08:37 UTC, igmoweb commented on README.md
> +2. Immediately after, you will be redirected to another screen to create a new Pull Request. If the title and descriptions are fine for you, click on `Create Pull Request` and wait for approval or ch
Fixed

2021-09-28 12:44 UTC, patstirling commented on CONTRIBUTING.md
> +This guide pretends to be a simple guide for users with or without Git experience. To contribute by creating or updating factors in the database for review by the OEFDB data stewards, follow these st
replace "pretends" with "aims" or "is intended"

2021-09-28 14:23 UTC, maryarbab approved these changes

2021-09-29 08:32 UTC, igmoweb commented
@patstirling All fixed. I also added a table of contents and a new section on how to write good commit messages

2021-09-29 11:44 UTC, patstirling requested changes

2021-09-29 11:44 UTC, patstirling commented on .github/pull_request_template.md
> +**What?**
Hm, sorry to be a bit pedantic but I feel we need to turn the one word questions into something more sentence-based... so "What?" with "What changes or additions are being made?" and "Why?" with "Why are these changes valuable or necessary?"

2021-09-29 11:44 UTC, patstirling commented on CONTRIBUTING.md
> +This guide aims to be a simple guide for users with or without Git experience. To contribute by creating or updating factors in the database for review by the OEFDB data stewards, follow these steps:
This my fault but "Guide" used twice - could we say "This document aims to be..."

2021-09-29 11:44 UTC, patstirling commented on CONTRIBUTING.md
> +- Reference issues and pull requests liberally after the commit title. If you need to link to another Pull Request, do it after the commit title.
Should we add advice here or elsewhere that "As the OEFDB is an evolving database, the whole process from download to pull request should be performed in as timely a fashion as possible to avoid conflicting versions being produced"?

2021-09-29 11:44 UTC, patstirling commented on CONTRIBUTING.md
> +## How to add or change values to the Emission Factors CSV file
replace "change values to" with "change values in"

2021-09-30 10:08 UTC, igmoweb commented on CONTRIBUTING.md
> +- Reference issues and pull requests liberally after the commit title. If you need to link to another Pull Request, do it after the commit title.
I don't know where to place that as it doesn't belong to the Commit Messages section and I don't know if it will cause more confusion to GitHub non expert users

2021-09-30 10:08 UTC, igmoweb commented on CONTRIBUTING.md
> +## How to add or change values to the Emission Factors CSV file
Fixed

2021-09-30 10:08 UTC, igmoweb commented on CONTRIBUTING.md
> +This guide aims to be a simple guide for users with or without Git experience. To contribute by creating or updating factors in the database for review by the OEFDB data stewards, follow these steps:
I should have seen it. Fixed now.

2021-09-30 10:09 UTC, igmoweb commented
@patstirling Thanks again, I've added some more fixes

2021-09-30 11:34 UTC, maryarbab approved these changes

2021-10-01 09:53 UTC, patstirling approved these changes

2021-10-01 11:28 UTC, merged

2021-11-09 15:10 UTC, greenercode reviewed
Great work @AnastasiaLobanova! 👏