Include transmission and distribution (BEIS)
climatiq/Open-Emission-Factors-DB pull request #110
Opened 2021-12-21 13:10 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Electricity & Heat and Steam

**What?**

Includes two emission factors to report the Scope 3 emissions associated with grid losses (the energy loss that occurs in getting the electricity from the power plant to the organisations that purchase it.

**Why?**

These are essential in reporting to calculate total emissions generated.

2022-01-11 13:10 UTC, AnastasiaLobanova requested changes

2022-01-13 09:37 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt_distribution_5percent_loss,District heat & steam (WTT distribution 5% loss),kg-CO2e/kWh,0.00166,,BEIS,2021,GB,2021/11/25,Emission intensity for
Ah I just noticed also - heat-and-steam, should be probably heat_and_steam- as we separate subIDs with "-" and words within subID with "_"

2022-01-13 09:37 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt_distribution_5percent_loss,District heat & steam (WTT distribution 5% loss),kg-CO2e/kWh,0.00166,,BEIS,2021,GB,2021/11/25,Emission intensity for
I think there will be a difference in the id - you have "wtt"in line 457

2022-01-18 14:23 UTC, maryarbab requested changes

2022-01-18 14:23 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,transmission-and-distribution-type_uk_electricity,T&D - UK electricity,kg-CO2e/kg,0.01879,,BEIS,2021,GB,2021/12/21,Emission intensity of T&D- UK electricity.Transmission and distri
Why do we need UK in the ID as it is indicated in the region column?

2022-01-18 14:23 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,transmission-and-distribution-type_uk_electricity,T&D - UK electricity,kg-CO2e/kg,0.01879,,BEIS,2021,GB,2021/12/21,Emission intensity of T&D- UK electricity.Transmission and distri
Please update the description to reflect the new way of citation: Available in BEISs Greenhouse Gas Reporting: Conversion Factors 2021-flat file.

2022-01-20 10:15 UTC, maryarbab requested changes

2022-01-20 10:15 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,transmission-and-distribution-type_uk_electricity,T&D - UK electricity,kg-CO2e/kg,0.01879,,BEIS,2021,GB,2021/12/21,Emission intensity of T&D- UK electricity.Transmission and distri
It does not follow the citing style for BEIS.

2022-01-20 10:19 UTC, maryarbab requested changes

2022-01-20 10:19 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_distribution_5percent_loss,District heat & steam distribution - 5% loss,kg-CO2e/kg,0.00899,,BEIS,2021,GB,2021/12/21,Emission intensity of district h
If this is related to this PR, it does not follow the citing style.

2022-01-20 10:20 UTC, maryarbab requested changes

2022-01-20 10:20 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_distribution_5percent_loss,District heat & steam distribution - 5% loss,kg-CO2e/kg,0.00899,,BEIS,2021,GB,2021/12/21,Emission intensity of district h
If this is related to this PR, it does not follow the citing style.

2022-01-20 10:21 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_distribution_5percent_loss,District heat & steam distribution - 5% loss,kg-CO2e/kg,0.00899,,BEIS,2021,GB,2021/12/21,Emission intensity of district h
It is not - but I can change it too. Let me know! :) @maryarbab

2022-01-20 10:29 UTC, maryarbab requested changes

2022-01-20 10:29 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_distribution_5percent_loss,District heat & steam distribution - 5% loss,kg-CO2e/kg,0.00899,,BEIS,2021,GB,2021/12/21,Emission intensity of district h
Okay, it also needs to be transmission and distribution in the lca activity same as 362.

2022-01-20 11:29 UTC, AnastasiaLobanova approved these changes

2022-01-20 17:24 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt_distribution_5percent_loss,District heat & steam (WTT distribution 5% loss),kg-CO2e/kWh,0.00166,,BEIS,2021,GB,2021/11/25,Emission intensity for
We've had this in the lca_activity field in other datasets (fuel) so that ID stays consistent between the usage and upstream aspects of an activity - suggest we stick to that.

2022-01-20 17:40 UTC, patstirling requested changes

2022-01-20 17:40 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,transmission-and-distribution-type_uk_electricity,T&D - UK electricity,kg-CO2e/kg,0.01879,,BEIS,2021,GB,2021/12/21,Emission intensity of T&D- UK electricity.Transmission and distri
ID here should be "electricity-energy_source_grid_mix" with lca_activity being the "unique" aspect to differentiate from the partner EF here: https://explorer.climatiq.io/emission-factor/grid-mix-energy-electricity-united-kingdom-2021-beis

2022-01-20 17:40 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
Is this because of reordering? Can we change this back to avoid conflicts

2022-01-20 17:40 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_van-fuel_source_na-vehicle_weight_lt_3.5t,Average van (up to 3.5 tonnes),kg-CO2e/tkm,0.60635,,BEIS,2021,GB,2021/12/13,Emission intensity of van w
Revert this to avoid conflicts

2022-01-21 08:57 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt_distribution_5percent_loss,District heat & steam (WTT distribution 5% loss),kg-CO2e/kWh,0.00166,,BEIS,2021,GB,2021/11/25,Emission intensity for
Ok

2022-01-21 08:57 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,transmission-and-distribution-type_uk_electricity,T&D - UK electricity,kg-CO2e/kg,0.01879,,BEIS,2021,GB,2021/12/21,Emission intensity of T&D- UK electricity.Transmission and distri
Ok, great! Thanks!

2022-01-21 09:17 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
This should be ok now. Please review when possible - @patstirling @AnastasiaLobanova @maryarbab

2022-01-21 09:18 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
**NB:** these do not refer to WTT but only T&D as the PR title suggests. There are additional WTT emission factors from BEIS that are applicable to T&D. These could be included in a separate PR.

2022-01-24 12:42 UTC, maryarbab approved these changes

2022-01-25 10:15 UTC, closed without merging