Include WTT- UK & overseas elec. (BEIS)
climatiq/Open-Emission-Factors-DB pull request #111
Opened 2021-12-21 14:14 UTC by greenercode

Include WTT- UK & overseas elec. (BEIS)

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Electricity 

**What?**

Includes WTT- UK & overseas elec. (BEIS).

**Why?**

These are essential in reporting to calculate total emissions generated.

2022-01-11 13:09 UTC, AnastasiaLobanova requested changes
Nice work Stephane!! A lot of new data, really cool stuff!

I have two general suggestions, in the description instead of "," use "/" to avoid the appearance of "" and to delete  "-" in the names column, e.g.

WTT- Electricity generation - Gibraltar -> WTT electricity generation Gibraltar

2022-01-11 13:09 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,"WTT- Electricity generation - Hong Kong, China",kg-CO2e/kWh,0.17198,,BEIS,2021,HK,2021/12/21,"Emission intensity of WTT- Ele
I suggest and instead of "," in the name column

2022-01-13 09:51 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,"WTT- Electricity generation - Hong Kong, China",kg-CO2e/kWh,0.17198,,BEIS,2021,HK,2021/12/21,"Emission intensity of WTT- Ele
Done - better now? 🤔

2022-01-13 10:15 UTC, AnastasiaLobanova requested changes
one small bug

2022-01-13 10:15 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_td,WTT Transmission & Distribution NonOECD Europe and Eurasia (average),kg-CO2e/kWh,0.013588,,BEIS,2021,EURASIA,2021/12/21,Emission inte
NonOECD -> Non OECD

2022-01-18 14:39 UTC, maryarbab requested changes

2022-01-18 14:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
We should not include wtt in the ID. It refers to the lca activity. We also need to be consistent with other IDs in the same category. Suggestion for the ID: electricity-energy_source_grid_mix

2022-01-18 14:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
Please update the description to be: Available in BEISs Greenhouse Gas Reporting: Conversion Factors 2021-flat file.

2022-01-18 14:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
Where does the fuel, which is needed to generate electricity produced? Africa or UK?

2022-01-18 14:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
We need to distinguish between AF and UK here. Same as other rows.

2022-01-18 14:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
lca activity needs to be in lowe case.

2022-01-19 07:39 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix-type_wtt_generation,WTT Electricity generation Africa (average),kg-CO2e/kWh,0.118733,,BEIS,2021,AF,2021/12/21,Emission intensity of WTT Electrici
This is **WTT- UK & overseas electricity** - would you mind providing an example of how this should be distinguished? Thanks!

> We need to distinguish between AF and UK here. Same as other rows.

2022-01-20 10:17 UTC, maryarbab approved these changes

2022-01-20 11:36 UTC, AnastasiaLobanova approved these changes

2022-01-25 07:51 UTC, closed without merging