Adding EPA spend-based EFs for commodity
climatiq/Open-Emission-Factors-DB pull request #112
Opened 2021-12-22 16:43 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

multiple

**What?**

Adding EPA spend-based EFs for commodity 

**Why?**

Adding spend-based emission factors to OEFDB

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_natural_gas,Natural gas,kg-CO2e/USD,0.83,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spen
should this be just fuel?

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_gasoline_stations-fuel_use_na,Gasoline stations,kg-CO2e/USD,0.301,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars sp
these two EFs, I think they might belong to other category but I am not sure which one exactly

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_pipeline_transport-fuel_use_na,Pipeline transport,kg-CO2e/USD,2.015,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars
I think here the category might be "Infrastructure"?

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_air_transport-distance_na-weight_na-contrails_na,Air transport,kg-CO2e/USD,0.965,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with mar
@Pat do you think they refer here to passenger transport?

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_ships_ship_repair-fuel_source_na,Ships and ship repair,kg-CO2e/USD,0.18,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. c
Feels like this should be in another category but I am not sure which one

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_military_armored_vehicles_tanks-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Military armored vehicles and tanks,kg-CO2e/USD,0.215,
is it a passenger vehicle? a tank.... :(

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_railroad_rolling_stock-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Railroad rolling stock,kg-CO2e/USD,0.314,,EPA,2020,US,2021/10/1
I am not sure but this is not rail freight?

2021-12-23 11:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_electricity,Electric long-distance passenger train,kg-CO2e/pkm,0.00948,,UBA,2020,DE,2021/09/15,Emission intensity of electri
I think this is correctly sorted! (by Open Office :D )

2021-12-24 12:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_natural_gas,Natural gas,kg-CO2e/USD,0.83,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spen
yes, I think this must have been mis-categorised

2021-12-24 12:38 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_gasoline_stations-fuel_use_na,Gasoline stations,kg-CO2e/USD,0.301,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars sp
Based on the context I agree 551 shouldn't be in fuel - this should go to Consumer Goods and Services > General Retail. 552 should stay in this category as it is spend on fuel itself

2021-12-24 12:38 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_pipeline_transport-fuel_use_na,Pipeline transport,kg-CO2e/USD,2.015,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars
Yes - "Building and Infrastructure"

2021-12-24 12:47 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_air_transport-distance_na-weight_na-contrails_na,Air transport,kg-CO2e/USD,0.965,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with mar
it's non-specific I believe - this sits alongside "Rail transport", "Water transport (boats, ships, ferries)", "Truck transport", "Passenger ground transport" and "Pipeline transport" so I think other than "Passenger ground transport" we should put these in "transport" not "travel" categories. Not perfect, but can't see another option!

2021-12-24 12:47 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_ships_ship_repair-fuel_source_na,Ships and ship repair,kg-CO2e/USD,0.18,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. c
Yes - this should go into "Vehicle"

2021-12-24 12:48 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_military_armored_vehicles_tanks-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Military armored vehicles and tanks,kg-CO2e/USD,0.215,
No, good catch! Let's use "military_vehicle"

2021-12-30 16:00 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_natural_gas,Natural gas,kg-CO2e/USD,0.83,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spen
This one now not in Sector > Category > Name order

2021-12-30 16:02 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_gasoline_stations-fuel_use_na,Gasoline stations,kg-CO2e/USD,0.301,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars sp
Recategorised correctly but now needs to be re-ordered

2021-12-30 16:02 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_pipeline_transport-fuel_use_na,Pipeline transport,kg-CO2e/USD,2.015,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars
Recategorised correctly but now needs to be re-ordered

2021-12-30 16:03 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_ships_ship_repair-fuel_source_na,Ships and ship repair,kg-CO2e/USD,0.18,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. c
Recategorised correctly but now needs to be re-ordered

2021-12-30 16:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_railroad_rolling_stock-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Railroad rolling stock,kg-CO2e/USD,0.314,,EPA,2020,US,2021/10/1
No this can be considered a vehicle (rolling stock is any non-powered rail vehicle, so can be a passenger carriage or a goods carriage)

2021-12-30 17:29 UTC, patstirling requested changes

2021-12-30 17:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Travel,passenger_flight-route_type_aircraft-aircraft_type_na-distance_na-class_na-contrails_na,Aircraft,kg-CO2e/USD,0.09,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with
This should be recategorised to Vehicle

2021-12-30 17:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Travel,passenger_flight-route_type_guided_missiles_space_vehicles-aircraft_type_na-distance_na-class_na-contrails_na,Guided missiles and space vehicles,kg-CO2e/USD,0.102,,EPA,2020,US,20
This should be recategorised to Vehicle

2021-12-30 17:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_boats-fuel_source_na,Boats,kg-CO2e/USD,0.271,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dolla
This should be recategorised to Vehicle

2022-01-04 16:43 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Agriculture and Fishing and Forestry,Wild fish and game,wild_fish-type_wild_caught_fish_game,Wild-caught fish and game,kg-CO2e/USD,0.376,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (wi
Category should be in Title Case: Wild Fish and Game

2022-01-05 10:18 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Buildings and Infrastructure,Construction,construction-type_commercial_structures_incl_farm_structures,Commercial structures/including farm structures,kg-CO2e/USD,0.289,,EPA,2020,US,2021/10/12,Emissi
This is again slightly outside the specific scope of the PR, but for the sake of consistency can we change the ID of these and the adjacent BEIS EFs to be "education-type_xxx" rather than "education_type_xxx"

2022-01-05 10:39 UTC, patstirling commented on OpenEmissionFactorsDB.csv
>  Information and Communication,Electronic Equipment,communication_equipment-type_telephone,Telephone equipment,kg-CO2e/GBP,0.283,,BEIS,2018,GB,2021/11/10,Emission intensity of supply chain in GBP spen
Let's put this EF in sector "Equipment" for consistency - will need to update ID to align.

2022-01-05 16:37 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Information and Communication,Information and Communication Services,communication_services-type_postal_service,Postal service,kg-CO2e/USD,0.206,,EPA,2020,US,2021/10/12,Emission intensity of supply c
can we update id to "communication_services-type_postal_services" to match existing BEIS

2022-01-05 16:48 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining (materials),mining-type_copper_nickel_lead_zinc,Copper/nickel/lead and zinc,kg-CO2e/USD,1.36,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to s
These EFs should probably not be called "Mining (materials)" - rather "Mined materials" - ID should reflect this also with mined_materials-type_xx

2022-01-05 16:54 UTC, patstirling commented on OpenEmissionFactorsDB.csv
>  Organisational activities,Government Activities,organisational_activity-type_central_government,Central government,kg-CO2e/GBP,0.132,,BEIS,2018,GB,2021/11/10,Emission intensity of supply chain in GBP
This sector should be renamed "Organizational Activities"

2022-01-05 16:55 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Organisational Activities,Non-profit Activities,organisational_activity-type_grantmaking_giving_social_advocacy_organizations,Grantmaking/giving and social advocacy organizations,kg-CO2e/USD,0.074,,E
In addition to the sector rename, the IDs for all these EFs (old and new) should begin with "organizational_activities"

2022-01-05 16:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Organisational Activities,Wholesale Trade,wholesale_trade-type_drugs_druggists’_sundries,Drugs and druggists’ sundries,kg-CO2e/USD,0.159,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (wi
remove ' from ID

2022-01-05 17:28 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Waste Management,waste_management-type_waste_management_remediation,Waste management and remediation,kg-CO2e/USD,1.501,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i
The ID for this EF should follow the format `waste_type_[e.g."aggregates"]-disposal_method_[e.g."open-loop"]` - in this case "waste_type_na-disposal_method_waste_management_remediation"

2022-01-05 17:36 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-drinking_water_wastewater_treatment,Drinking water and wastewater treatment,kg-CO2e/USD,0.618,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e.
The ID here should align with existing water IDs - e.g. "water-drinking_supply_wastewater_treatment

2022-01-06 09:00 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Waste,Waste Management,waste_management-type_waste_management_remediation,Waste management and remediation,kg-CO2e/USD,1.501,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i
Isn't it actually rather Buildings and Infrastructure?

2022-01-06 10:20 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Waste Management,waste_management-type_waste_management_remediation,Waste management and remediation,kg-CO2e/USD,1.501,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i
Nup - we have an independent waste disposal sector and category (currently with 139 EFs), as disposal/treatment of waste can be related to many more things than buildings/infrastructure

2022-01-06 13:59 UTC, patstirling approved these changes

2022-01-06 14:17 UTC, merged