DISER source update
climatiq/Open-Emission-Factors-DB pull request #115
Opened 2022-01-12 12:57 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [*] Update

**What category or categories does it affect?**

_Electricity_

**What?**

_Updates to the value, year, source link, and description fields._

**Why?**

_To link to the most recent primary source, which is DISER 2021_

2022-01-12 15:02 UTC, AnastasiaLobanova approved these changes
Looks good! Just a question about DISER - were the numbers from 2018 wrong? Thank you Maryam!

2022-01-18 14:40 UTC, maryarbab commented
> Looks good! Just a question about DISER - were the numbers from 2018 wrong? Thank you Maryam!

Nope, they were just outdated.

2022-01-19 09:34 UTC, patstirling approved these changes

2022-01-19 09:57 UTC, patstirling requested changes
The wording here uses "consumption" which seems right. A few non-AU DISER-related changes in this PR will cause conflicts.

2022-01-19 09:57 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
This and the next two changes will cause conflicts

2022-01-19 11:24 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
I am going to change it in the last PR. Should I wait to merge the last PR before merging this one then?

2022-01-19 14:11 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
I'd remove the changes from each PR to be sure

2022-01-19 14:30 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
Done;)

2022-01-19 15:21 UTC, patstirling requested changes

2022-01-19 15:21 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.54,,DISER,2021,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
Just checking in light of other reviews: does "Indirect (scope 2) emission factors for consumption of purchased electricity or loss of electricity from the grid" imply that this is the emissions generated at consumption? If so should we change lca_activity for these EFs?

2022-01-19 15:38 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.54,,DISER,2021,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
I know it is a bit confusing. I actually checked the source when I was updating it and the source has this explanation: 

"The estimated electricity emission factors have been aligned with the definitions used in The
Greenhouse Gas Protocol: A Corporate Accounting and Reporting Standard of the World
Resources Institute/World Business Council for Sustainable Development (the GHG
Protocol). The emission factor for scope 2 is defined in terms of energy sent out on the grid
rather than energy delivered because this effectively ensures that end users of electricity are
allocated only the scope 2 emissions attributable to the electricity they consume and not the
scope 2 emissions attributable to electricity lost in transmission and distribution."

2022-01-19 18:40 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.54,,DISER,2021,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
This to me _largely_ suggests that it is for measurement of consumed electricity, to be attributed as scope 2 by the consumer - so suggest we treat this as a consumption metric

2022-01-19 18:55 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.54,,DISER,2021,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
Alright, changed it.

2022-01-20 09:24 UTC, patstirling approved these changes

2022-01-20 09:24 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.54,,DISER,2021,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
This also maps neatly on to "use_phase" as a macro LCA category. Approved!

2022-01-20 09:26 UTC, merged