DEWA source update
climatiq/Open-Emission-Factors-DB pull request #116
Opened 2022-01-13 07:19 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [ ] Update

**What category or categories does it affect?**

_Electricity_

**What?**

_Updates to the value, year, source link, and description fields._

**Why?**

_To link to the most recent primary source, which is DEWA 2020_

2022-01-13 09:15 UTC, greenercode submitted a review, later dismissed

2022-01-13 10:20 UTC, AnastasiaLobanova approved these changes

2022-01-19 09:42 UTC, patstirling requested changes

2022-01-19 09:42 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.4041,,DEWA,2020,AE,2021/07/30,Emission intensity of electricity generated as reported. Published by Dubai Electricity & Wa
should this be "electricity generated" or "electricity consumed"? I think these EFs are designed to be used by consumers of the energy?

I also think we should be more explicit, say "electricity consumed in the United Arab Emirates." There's a question here about whether we should be using the term "Average" somewhere - e.g. "Average emissions generated by consumption of a unit of electricity in the United Arab Emirates" - but I'll post that for a broader discussion.

2022-01-19 09:42 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
I think this is going to cause conflicts with all the other EFs - it needs to be fixed, but suggest it be fixed in the very last of this volley of PRs?

2022-01-19 11:22 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
Yes, let's do that.

2022-01-19 12:15 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.4041,,DEWA,2020,AE,2021/07/30,Emission intensity of electricity generated as reported. Published by Dubai Electricity & Wa
The source says: Carbon emission intensity, tCO2e/MWH of electricity generated. So, I think we should also keep it as generated indicating that it does not include t&d losses.

2022-01-19 15:23 UTC, patstirling requested changes

2022-01-19 15:43 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.4041,,DEWA,2020,AE,2021/07/30,Emission intensity of electricity generated as reported. Published by Dubai Electricity & Wa
Revised;)

2022-01-20 11:30 UTC, patstirling approved these changes

2022-01-20 11:38 UTC, AnastasiaLobanova approved these changes

2022-01-20 13:11 UTC, merged