BEIS source update
climatiq/Open-Emission-Factors-DB pull request #117
Opened 2022-01-13 12:07 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- Update

**What category or categories does it affect?**

_All BEIS categories_

**What?**

_Updates to the value, year, source link, and description fields._

**Why?**

_To link to the most recent primary source, which is BEIS "Conversion factors 2021: flat file"_

2022-01-13 14:56 UTC, AnastasiaLobanova approved these changes
Great stuff Maryam!

2022-01-19 10:30 UTC, patstirling requested changes

2022-01-19 10:30 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.21233,,BEIS,2021,GB,2021/07/23,Emission intensity of electricity generated as reported. Available in BEISs Greenhouse Gas
can we replace "-flat" with ": flat" as per the text at the source URL

2022-01-19 10:30 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.4041,,DEWA,2020,AE,2021/07/30,Emission intensity of electricity generated as reported. Published by Dubai Electricity & Wa
I think this may have sneaked in from another PR?

2022-01-19 12:33 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.21233,,BEIS,2021,GB,2021/07/23,Emission intensity of electricity generated as reported. Available in BEISs Greenhouse Gas
I intentionally changed it to dash since it would be "Available in BEISs Greenhouse Gas Reporting: Conversion Factors 2021: flat file" in some case. If it seems okay, I can change it all to ": flat".

2022-01-19 13:18 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.4041,,DEWA,2020,AE,2021/07/30,Emission intensity of electricity generated as reported. Published by Dubai Electricity & Wa
Removed it:)

2022-01-19 15:34 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.21233,,BEIS,2021,GB,2021/07/23,Emission intensity of electricity generated as reported. Available in BEISs Greenhouse Gas
Hm, tricky. Ok I've had a look at the site - suggest the following "Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL"

2022-01-19 16:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.21233,,BEIS,2021,GB,2021/07/23,Emission intensity of electricity generated as reported. Available in BEISs Greenhouse Gas
Done.

2022-01-20 11:33 UTC, patstirling submitted a review, later dismissed

2022-01-20 11:57 UTC, AnastasiaLobanova submitted a review, later dismissed

2022-01-20 13:13 UTC, greenercode approved these changes

2022-01-20 13:53 UTC, grindcode approved these changes

2022-01-20 13:54 UTC, merged