ADEME source update
climatiq/Open-Emission-Factors-DB pull request #120
Opened 2022-01-13 14:54 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update
What category or categories does it affect?

All BEIS categories

What?

Updates to the year, source link, and description fields.

Why?

To link to the most recent primary source, which is ADEME Base Carbone - Data V21.0.csv.

2022-01-18 16:27 UTC, greenercode approved these changes

2022-01-19 12:39 UTC, patstirling requested changes

2022-01-19 12:39 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.842,10,ADEME,2013,KW,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh sup
I think for this temporary fix this should be clearer, e.g. "NOTE: this value is provided in CO2 only and does no include the impact of other GHGs. This factor will be deprecated."

2022-01-19 12:39 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.0296,10,ADEME,2013,SE,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh su
addition made twice here

2022-01-19 14:40 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.842,10,ADEME,2013,KW,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh sup
Revised!

2022-01-19 15:36 UTC, patstirling requested changes

2022-01-19 15:36 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.842,10,ADEME,2013,KW,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh sup
Oops - really sorry there was a typo in my text should be "does not include" not "does no include" (which sounds ok in a Scots accent but otherwise is definitely wrong)

2022-01-20 13:44 UTC, patstirling submitted a review, later dismissed

2022-01-20 15:25 UTC, AnastasiaLobanova approved these changes

2022-01-20 15:30 UTC, merged