CT source update
climatiq/Open-Emission-Factors-DB pull request #121
Opened 2022-01-13 15:40 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update

What category or categories does it affect?

Electricity 

What?

Updates to the year, source link, value, and description fields.

Why?

To link to the most recent primary source.

2022-01-18 16:27 UTC, greenercode submitted a review, later dismissed

2022-01-19 12:45 UTC, patstirling requested changes

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Recreation and Culture,consumer_goods-type_paper_goods_books_cards_newspapers_magazines,Paper goods (books/cards/newspapers/magazines),kg-CO2e/GBP,0.186,,BEIS,2018,GB,2021
Believe this may be an accidental change?

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.761,,CT,2019,ID,2021/07/30,Emission intensity of grid mix as reported. Available in the Climate Transparency Report 2019.
I think we should be more consistent about our language here; could the "grid mix" term be replaced with something that aligns with other EFs? With respect to data sourcing, the term I'm used to seeing in puclished articles is "retrieved from" rather than "available in" - would you agree this is better @maryarbab @AnastasiaLobanova ?

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
remove this change to avoid conflicts

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_well_drilling,Well drilling,kg-CO2e/USD,0.543,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spend on: well
remove this change to avoid conflicts

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,General Waste,waste_type_household_residual_waste-disposal_method_anaerobic_digestion,Household residual waste disposal - anaerobic digestion,kg-CO2e/t,8.951,,BEIS,2021,GB,2021/11/18,Emission i
remove this change to avoid conflicts

2022-01-19 12:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
remove this change to avoid conflicts

2022-01-19 13:29 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Recreation and Culture,consumer_goods-type_paper_goods_books_cards_newspapers_magazines,Paper goods (books/cards/newspapers/magazines),kg-CO2e/GBP,0.186,,BEIS,2018,GB,2021
No, that is the change @AnastasiaLobanova asked for to add the (_) after "paper".

2022-01-19 13:42 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.761,,CT,2019,ID,2021/07/30,Emission intensity of grid mix as reported. Available in the Climate Transparency Report 2019.
Hum, I didn't really understand the first point: the "grid mix" is used for other EFs as well. Do you mean the "fuel mix" be replaced?

2022-01-19 14:22 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.761,,CT,2019,ID,2021/07/30,Emission intensity of grid mix as reported. Available in the Climate Transparency Report 2019.
No, I mean the grid mix term - it is used but for example you have updated it in https://github.com/climatiq/Open-Emission-Factors-DB/pull/116 to "Emission intensity of electricity generated" which I think is better. Ideally this should be standardised to something like "Emission intensity of electricity consumed in Indonesia"

2022-01-20 12:04 UTC, AnastasiaLobanova approved these changes

2022-01-20 12:38 UTC, patstirling commented
There's a typo in the description (from my text, sorry!): "does no include" -> "does not include"

2022-01-20 13:48 UTC, patstirling submitted a review, later dismissed

2022-01-20 15:49 UTC, AnastasiaLobanova approved these changes

2022-01-20 15:49 UTC, merged