AIB source update
climatiq/Open-Emission-Factors-DB pull request #122
Opened 2022-01-13 18:51 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update

What category or categories does it affect?

Electricity 

What?

Updates to the year, source link, value, and description fields.

Why?

To link to the most recent AIB source as the primary source.

2022-01-14 09:38 UTC, greenercode submitted a review, later dismissed

2022-01-19 12:58 UTC, patstirling requested changes

2022-01-19 12:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.05128,,AIB,2020,FR,2021/07/30,"Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies
remove comma and quotation marks throughout

2022-01-19 12:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.05128,,AIB,2020,FR,2021/07/30,"Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies
Suggest "grid mix" be replaced with "average electricity consumption" or similar (consistent with other EFs). Replace "available in" with "retrieved from" (nb decision pending on best reference style.

2022-01-19 12:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
remove this change to avoid conflicts

2022-01-19 12:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_well_drilling,Well drilling,kg-CO2e/USD,0.543,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spend on: well
remove this change to avoid conflicts

2022-01-19 12:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
remove this change to avoid conflicts

2022-01-19 14:20 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.05128,,AIB,2020,FR,2021/07/30,"Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies
Done.

2022-01-20 12:10 UTC, AnastasiaLobanova submitted a review, later dismissed

2022-01-20 12:10 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.6429,,AIB,2020,CY,2021/07/30,Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies (A
Here, the year and factor were updated - it is because it was wrong or because these are new efs for the year 2020?

I ask because I think if we should actually keep the historic EFs?

2022-01-20 12:39 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.6429,,AIB,2020,CY,2021/07/30,Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies (A
For simplicity and speed, I think we should just stay with @maryarbab 's approach here and go with the latest EF. We can add backdated EFs later if they are something people want - this activity was about getting the initial dataset correctly represented and referenced

2022-01-20 13:50 UTC, patstirling submitted a review, later dismissed

2022-01-20 16:10 UTC, AnastasiaLobanova approved these changes

2022-01-20 16:11 UTC, merged