UNFCCC & EPPO source update
climatiq/Open-Emission-Factors-DB pull request #123
Opened 2022-01-14 07:20 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update

What category or categories does it affect?

Electricity 

What?

Updates to the year, source link, value, and description fields.

Why?

To link to the most recent UNFCCC and EPPO sources.

2022-01-14 09:37 UTC, greenercode submitted a review, later dismissed

2022-01-19 13:06 UTC, patstirling requested changes

2022-01-19 13:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.442,,EPPO,2020,TH,2021/07/30,Emission intensity of grid mix as reported. Published by the Energy Policy and Planning Offic
Love this level of detail! We are getting people respond really well to our transparency and consistency - this is great.

2022-01-19 13:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
this should be removed to avoid conflicts

2022-01-19 13:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_well_drilling,Well drilling,kg-CO2e/USD,0.543,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spend on: well
this should be removed to avoid conflicts

2022-01-19 13:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
this should be removed to avoid conflicts

2022-01-19 14:47 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
Done done;)

2022-01-20 12:14 UTC, AnastasiaLobanova approved these changes

2022-01-20 12:41 UTC, patstirling approved these changes

2022-01-20 14:14 UTC, patstirling approved these changes

2022-01-20 14:14 UTC, merged