EPA source update
climatiq/Open-Emission-Factors-DB pull request #124
Opened 2022-01-14 09:28 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update

What category or categories does it affect?

Multiple categories  

What?

Updates to the year, source link, value, and description fields.

Why?

To link to the most recent EPA and eGrid sources.

2022-01-14 09:37 UTC, greenercode submitted a review, later dismissed

2022-01-19 14:30 UTC, patstirling requested changes

2022-01-19 14:30 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_well_drilling,Well drilling,kg-CO2e/USD,0.543,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spend on: well
remove to avoid conflicts

2022-01-19 14:30 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.603764064,,EPA,2021,US-CO,2021/07/23,"Emission intensity of grid mix as reported. Total output emission rate, available in
Replace "available in" with "retrieved from" throughout

2022-01-19 15:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.603764064,,EPA,2021,US-CO,2021/07/23,"Emission intensity of grid mix as reported. Total output emission rate, available in
Let's make this change as a separate PR as it will impact multiple sources.

2022-01-20 12:27 UTC, AnastasiaLobanova approved these changes

2022-01-20 12:27 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.572764226,,EPA,2021,US-MT,2021/07/23,Emission intensity of grid mix as reported. Total output emission rate. Available in
Here I have the same, general comment - was this data wrong? Or it was replaced with the latest EF? I think we should discuss if we want to keep the historic data?

2022-01-20 12:42 UTC, patstirling submitted a review, later dismissed

2022-01-20 14:39 UTC, patstirling approved these changes

2022-01-20 14:39 UTC, merged