Mfe source update
climatiq/Open-Emission-Factors-DB pull request #125
Opened 2022-01-14 11:57 UTC by maryarbab

Is this a new addition or an update to an existing factor?

Update

What category or categories does it affect?

Multiple categories  

What?

Updates to the year, source link, value, and description fields.

Why?

To link to the most recent Mfe source.

2022-01-18 16:26 UTC, greenercode approved these changes

2022-01-19 14:52 UTC, patstirling requested changes

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.101,,MfE,2020,NZ,2021/09/10,Emission intensity purchased grid-average electricity. Published by the Ministry for the Envir
I don't really understand the sentence "Emission intensity purchased grid-average electricity" - should this be "Emission intensity of electricity purchased from the grid"?

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.101,,MfE,2020,NZ,2021/09/10,Emission intensity purchased grid-average electricity. Published by the Ministry for the Envir
Suggest replacing all "Available in" with "Retrieved from"

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avtur-fuel_use_aviation,Aviation turbine fuel (avtur),kg-CO2e/L,2.62632,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Enviro
There appears to be a copy and paste error in this line and many others (they all have "aviation gasoline" - please check!

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Health and Social Care,Health Care,health_care-type_medical_services,Medical services,kg-CO2e/GBP,0.297,,BEIS,2018,GB,2021/11/10,Emission intensity of supply chain in GBP spend on: NHS medical/optica
this change has been made in other PRs - remove to avoid conflicts

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_other_support_activities_for_mining,Other support activities for mining,kg-CO2e/USD,0.613,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cr
remove to avoid conflicts

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Materials,Mining,mining-type_well_drilling,Well drilling,kg-CO2e/USD,0.543,,EPA,2020,US,2021/10/12,Emission intensity of supply chain (with margins i.e. cradle to shelf) in US dollars spend on: well
remove to avoid conflicts

2022-01-19 14:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
remove this change - looks like a type

2022-01-20 12:38 UTC, AnastasiaLobanova requested changes
I think there is a problem with replacements - "aviation gasoline" appears in some places it should not be

2022-01-20 12:38 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_petrol-fuel_use_transport,Petrol (transport),kg-CO2e/L,2.45323824,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environment
Is this correct? Should the id reflect it is the aviation gasoline? I thought avgas has strict requirements on its quality, higher than average petrol? Happy to be corrected :)

2022-01-20 12:38 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_domestic-distance_na-weight_na-contrails_included,Domestic air freight,kg-CO2e/tkm,4.76719,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gas
Looks like a replacement error?

2022-01-20 12:38 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_international-distance_long_haul-weight_na-contrails_included,International air freight long haul,kg-CO2e/tkm,1.13382,,MfE,2020,NZ,2021/09/10,Emissio
same here - is it a typo?

2022-01-20 15:21 UTC, closed without merging