UBA source update
climatiq/Open-Emission-Factors-DB pull request #127
Opened 2022-01-19 15:56 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Multiple categories from the UBA

**What?**

some small inconsistencies with the source data

**Why?**

part of tackling current data health issues

2022-01-20 13:08 UTC, patstirling requested changes
Lovely update - some great catches here! There is a small issue with the vehicle IDs, see comment below.

2022-01-20 13:08 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_bio_cng-distance_na-engine_size_large,Bio CNG passenger car large,kg-CO2e/pkm,0.00392,,UBA,2020,DE,2021/09/15,Emission intensity o
Little issue with the engine_size in the ID here - this should be "unknown", not sure how this got into the old emission factors. The "large" aspect should be after "vehicle_type_" so "vehicle_type_large_car" as per this emission factor: https://explorer.climatiq.io/emission-factor/lpg-car-large-transport-vehicle-united-kingdom-2021-beis - this will need to be applied throughout the UBA EFs

2022-01-20 15:23 UTC, maryarbab approved these changes

2022-01-20 16:22 UTC, greenercode submitted a review, later dismissed

2022-01-20 16:27 UTC, maryarbab approved these changes

2022-01-20 17:04 UTC, patstirling submitted a review, later dismissed

2022-01-21 14:30 UTC, AnastasiaLobanova commented
Updated with the latest version of main

2022-01-21 14:30 UTC, closed without merging