adding spend-based EFs from GHG protocol (latest main)
climatiq/Open-Emission-Factors-DB pull request #145
Opened 2022-01-25 14:56 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x ] New
- [] Update

**What category or categories does it affect?**

multiple 

**What?**

adding spend-based EFs from GHG protocol (latest main)

**Why?**

Last portion of spend-based EFs to add to OEFDB

2022-01-26 08:57 UTC, maryarbab requested changes

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
Wouldn't this cause conflicts?

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_taxi-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Taxi,kgCO2e/km,0.2751,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
Shouldn't the unit be per Dollar?

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_van-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Van,kgCO2e/km,0.3218,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of su
Shouldn't the unit be per Dollar?

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_taxi-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Taxi,kgCO2e/km,0.2751,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
There are multiple of these.

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_upstream_transportation_distribution,Upstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission inten
What does this EF refer to? Is this the upstream emission related to transportation and distribution of goods? If so, to me LCA activity should not be known.

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_downstream_transportation_distribution,Downstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission i
What does this EF refer to? Does it refer to the downstream emissions related to transportation and distribution of goods? If so, to me LCA activity should not be known.

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Materials,Mining ,mining-type_mining_quarrying,Mining and quarrying,kgCO2e/USD,1.784,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of supply chain (purchase of service or standard good or c
Would the whitespace after "Mining" cause conflicts later?

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Vehicle Maintenance and Services,consumer_services-type_sale_maintenance_repair_of_motor_vehicles_motorcycles_retail_sale_of_fuel,Sale maintenance and repair of motor vehi
The name and ID seem confusing: is this about the maintenance of the vehicle or the fuel sale?

2022-01-26 08:57 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Clothing and Footwear,consumer_goods-type_leather_leather_footwear,Leather leather and footwear,kgCO2e/USD,0.9437,,GHG Protocol,2016,Global,2021/10/12,Emission intensity o
leather leather and footwear -> leather and footwear

2022-01-26 08:59 UTC, greenercode approved these changes

2022-01-26 09:18 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
Probably, I am not sure why git recognises this as deletion/addition but I haven't done anything to this line..

It is just one so I think it won't cause to serious conflict (I hope)

2022-01-26 09:24 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_taxi-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Taxi,kgCO2e/km,0.2751,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
In this case no - this was obtained from the Scope 3 calculator, for business travel. I agree these are not spend-based but we tried to extract the most important categories from this calculator. 

[Here you can see the Gsheet](https://docs.google.com/spreadsheets/d/1Wmg2FQ8APnG-e-Ov9aaFvTy4arBtfRpZzwfe3tpgi4E/edit#gid=447447126) with the extracted values from the calculator and also the units

2022-01-26 11:14 UTC, patstirling requested changes

2022-01-26 11:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_other_supporting_auxiliary_transport_activities_travel_agencies,Other supporting and auxiliary transport activities and activities of travel agenc
add an "and" between "activities" and "activities" in description

2022-01-26 11:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_bicycle-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Bicycle,kgCO2e/km,0,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
add "travel" after "bicycle" in description

2022-01-26 11:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_taxi-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Taxi,kgCO2e/km,0.2751,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
We can remove this and other EFs in the "Vehicles" category as this represents expenditure on purchase or operation of vehicles rather than use of them for travel

2022-01-26 11:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,freight_vehicle-vehicle_type_na-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Transport equipment,kgCO2e/USD,0.5354,,GHG Protocol,2016,Global,2021/10/12,Emission i
remove

2022-01-26 11:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_van-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Van,kgCO2e/km,0.3218,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of su
remove

2022-01-26 11:38 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Agriculture and Fishing and Forestry,Agriculture or Hunting or Forestry or Fishing,agriculture_fishing_forestry-type_agriculture_hunting_forestry_fishing,Agriculture hunting forestry and fishing,kgCO
But these are the values calculator provides for years 2016?

2022-01-26 12:52 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_upstream_transportation_distribution,Upstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission inten
I think it is emission intensity of the upstream t&d of a particular company, e.g. delivery of goods.. Activity field is left unknown

2022-01-26 12:52 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_downstream_transportation_distribution,Downstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission i
Yes, LCA activity field is left unknown

2022-01-26 12:52 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Materials,Mining ,mining-type_mining_quarrying,Mining and quarrying,kgCO2e/USD,1.784,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of supply chain (purchase of service or standard good or c
Good catch!!

2022-01-26 13:18 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Vehicle Maintenance and Services,consumer_services-type_sale_maintenance_repair_of_motor_vehicles_motorcycles_retail_sale_of_fuel,Sale maintenance and repair of motor vehi
All of these! It is coming from the source, i.e. from the WIOD sectors

2022-01-26 13:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Agriculture and Fishing and Forestry,Agriculture or Hunting or Forestry or Fishing,agriculture_fishing_forestry-type_agriculture_hunting_forestry_fishing,Agriculture hunting forestry and fishing,kgCO
Ok!

2022-01-26 13:42 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Clothing and Footwear,consumer_goods-type_leather_leather_footwear,Leather leather and footwear,kgCO2e/USD,0.9437,,GHG Protocol,2016,Global,2021/10/12,Emission intensity o
ok!

2022-01-26 13:46 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_downstream_transportation_distribution,Downstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission i
See slack discussion - `lca_activity` this should be "downstream" as should all other downstream EFs

2022-01-26 13:46 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_upstream_transportation_distribution,Upstream transportation and distribution,kgCO2e/USD,0.484,,GHG Protocol,2016,Global,2021/10/12,Emission inten
See discussion - `lca_activity` this should be "upstream" as should all other upstream EFs in this dataset (e.g. the majority - anything that isn't "downstream")

2022-01-26 13:57 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_na-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Water freight,kgCO2e/USD,1.9324,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of
This one is for downstream leased water freight - the lac activity will be different here with the following one. I will keep it for now

2022-01-26 13:58 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_na-fuel_source_na,Sea travel,kgCO2e/USD,0.7595,,GHG Protocol,2016,Global,2021/10/12,Emission intensity of supply chain (purchase of service or standard
Dollars spend on sea :D like a good metaphor for spending money hehehe

2022-01-26 16:40 UTC, maryarbab approved these changes

2022-01-26 17:58 UTC, patstirling requested changes
Ok - dug in a bit deeper on things and we've uncovered a few things. See comments for getting these straightened out; note also:

- there are 2 EFs that appear to be missing (Transport Equipment and  per km EF for van travel) - they've been highlighted in the associated import sheet
- facilities and downstream leased assets and investments tabs have a number of EFs that will need to come in; we intend to do these in a follow-up PR once the initial set are in

2022-01-26 17:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Warehousing and Storage,warehouse_storage-type_warehousing,Warehousing,kg-CO2e/USD,0.484,,GHG Protocol,2017,Global,2021/10/12,Emission intensity of downstream-leased assets in US dollars sp
replace "downstream-leased assets" with "third-party distribution" in `description` and "upstream_downstream" in `lca_activity`. Remove space at end of description

2022-01-26 17:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_na-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Water freight,kg-CO2e/USD,1.9324,,GHG Protocol,2017,Global,2021/10/12,Emission intensity of
replace "downstream-leased assets" with "third-party transport" in `description` and "upstream_downstream" in `lca_activity`.

2022-01-26 17:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_downstream_transportation_distribution,Downstream transportation and distribution,kg-CO2e/USD,0.484,,GHG Protocol,2017,Global,2021/10/12,Emission
replace "supply chain (purchase of service/standard good/capital good)" with "third-party distribution" in `description`.

2022-01-26 17:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Transport Services,transport_services-type_upstream_transportation_distribution,Upstream transportation and distribution,kg-CO2e/USD,0.484,,GHG Protocol,2017,Global,2021/10/12,Emission inte
replace "supply chain (purchase of service/standard good/capital good)" with "third-party distribution" in ´description´.

2022-01-26 17:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Paper Products,paper_products-type_pulp_paper_printing_publishing,Pulp or paper printing and publishing,kgCO2e/USD,0.6365,,GHG Protocol,2016,Global,2021/10/12,Emission int
Let's use "Pulp/paper/printing and publishing" for name and description here - GHG original is "Pulp, Paper, Printing and Publishing"

2022-01-27 08:34 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Restaurants and Accommodation,Accommodation,accommodation_type_hotel_room,Hotel room,kg-CO2e/USD,17.98,,GHG Protocol,2017,Global,2021/10/12,Emission intensity of supply chain (purchase of service/sta
Good catch!!

2022-01-27 08:46 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicles,passenger_vehicle-vehicle_type_bicycle-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Bicycle,kg-CO2e/km,0,,GHG Protocol,2017,Global,2021/10/12,Emission intensity o
Would be great if we take the final decision on categorisation before data is already in the database next time - will save a lot of time.

2022-01-27 08:56 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Transport,freight_train-route_type_na-fuel_type_na,Rail freight,kg-CO2e/USD,0.776,,GHG Protocol,2017,Global,2021/10/12,Emission intensity of downstream-leased assets in US dollars spen
I think it should be upstream-downstream. We separate different boundaries with "-" in the other fields

2022-01-27 10:45 UTC, maryarbab approved these changes

2022-01-27 11:13 UTC, patstirling approved these changes
AMAZING WORK!

2022-01-27 11:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Transport,freight_train-route_type_na-fuel_type_na,Rail freight,kg-CO2e/USD,0.776,,GHG Protocol,2017,Global,2021/10/12,Emission intensity of downstream-leased assets in US dollars spen
Good catch!

2022-01-27 11:17 UTC, merged