Fix minor issues
climatiq/Open-Emission-Factors-DB pull request #149
Opened 2022-01-28 11:14 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Multiple_

**What?**

_Tackle minor issues spotted in the OEFDB_

2022-01-28 12:16 UTC, AnastasiaLobanova submitted a review, later dismissed

2022-01-31 12:46 UTC, patstirling requested changes
Could more detail be provided in the description of this PR? It's good practice to provide detail which describes at least each category of change, even if it's fairly broad - and very helpful when reviewing so you know what to look out for!

2022-01-31 12:46 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.77669,,AIB,2020,RS,2021/07/30,Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies (
"no include" -> "not include" for this and numerous other lines. We've also recently decided we will keep these factors in but not provide CO2e numbers, so we can remove "This factor will be deprecated" from this and other CO2-only EFs

2022-01-31 13:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kWh,0.77669,,AIB,2020,RS,2021/07/30,Emission intensity of grid mix as reported. Published by the Association of Issuing Bodies (
Great catch! Done:)

2022-01-31 16:15 UTC, patstirling approved these changes

2022-01-31 20:59 UTC, merged