GHG protocol-Electricity, Heat and Stream
climatiq/Open-Emission-Factors-DB pull request #152
Opened 2022-02-01 11:19 UTC by maryarbab

Is this a new addition or an update to an existing factor?

[*] New

What category or categories does it affect?

Electricity and Heat and Steam

What?

Adding GHG protocol EFs along with the constituent gasses and scope as new columns.

Why?

To grow the scope and coverage of the OEFDB.

2022-02-01 12:27 UTC, AnastasiaLobanova approved these changes

2022-02-01 12:27 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
why here are so many "" in the description?

2022-02-01 12:27 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
I am a bit confused by the description:

The primary source is EPA Emission Factors for Greenhouse Gas Inventories - Table 6 Electricity - March 9 2018. From EPA eGRID2016 - February 2018.

Can we make it a bit clearer? Is the source eGRID2016, published on March 9 2018?

2022-02-01 12:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
Removed them!

2022-02-01 12:43 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
The data is retrieved from Table 6, which data is retrieved from the eGRID!!

2022-02-01 12:43 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
My suggestion is to just cite the eGRID.

2022-02-01 12:49 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
I agree!

2022-02-01 16:22 UTC, patstirling requested changes
Add eGrid region to the description field for all US, EU and Canadian eGrid EFs

2022-02-01 16:22 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_na,Purchased heat and steam,MMBTU,66.398125,66.3985,66.33,0.00125,0.000125,not-supplied,not-supplied,2,12,GHG Protocol,2021,US,2022/01/15,Emission intensity
specify locality in the description here

2022-02-02 11:45 UTC, patstirling requested changes

2022-02-02 11:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_photovoltaic_made_in_china,Photovoltaic (Made in China),kg-CO2e/kWh,,0.0439,,,,,,,30,ADEME,2021,FR,2021/08/20,"Emission intensity for photovoltaic made in
still got " at the start and end of this and a number of others

2022-02-02 11:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_location_based,Purchased electricity - Grid mix - Location based,kWh,0.238959264,0.23898648,0.238173642,1.09E-05,1.81E-06,not-supplied,not-suppli
Think we need "grid" after "ASCC Miscellaneous" - this true for all eGrid EFs

2022-02-02 13:54 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_na,Purchased heat and steam,MMBTU,66.398125,66.3985,66.33,0.00125,0.000125,not-supplied,not-supplied,2,12,GHG Protocol,2021,US,2022/01/15,Emission intensity
The locality is not specified in the source. Since it is retrieved from EPA, I added US as the UNLOCODE.

2022-02-02 15:16 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +sector,category,id,name,unit,kgCO2e-AR5,kgCO2e-AR4 ,kgCO2, kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,scope,uncertainty,source,year,region,date_accessed,description,source_link,lca_activit
Can we address the spaces in column names in this PR? cc @GeeWee

2022-02-02 15:20 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +sector,category,id,name,unit,kgCO2e-AR5,kgCO2e-AR4 ,kgCO2, kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,scope,uncertainty,source,year,region,date_accessed,description,source_link,lca_activit
Done;)

2022-02-02 15:21 UTC, patstirling approved these changes

2022-02-02 15:21 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +sector,category,id,name,unit,kgCO2e-AR5,kgCO2e-AR4 ,kgCO2, kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,scope,uncertainty,source,year,region,date_accessed,description,source_link,lca_activit
think that's been done?

2022-02-02 15:23 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +sector,category,id,name,unit,kgCO2e-AR5,kgCO2e-AR4 ,kgCO2, kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,scope,uncertainty,source,year,region,date_accessed,description,source_link,lca_activit
brilliant, thank you!

2022-02-02 15:23 UTC, merged