GHG protocol- Transport
climatiq/Open-Emission-Factors-DB pull request #156
Opened 2022-02-03 13:40 UTC by maryarbab

Is this a new addition or an update to an existing factor?

[*] New

What category or categories does it affect?

Rail, Road, Air, Sea Transport and Travel.

What?

Adding GHG protocol EFs along with the constituent gasses and scope as new columns.

Why?

To grow the scope and coverage of the OEFDB.

2022-02-03 14:20 UTC, AnastasiaLobanova requested changes
Another piece of great work Maryam! The DB is growing huuuge

Could you check again what is "RF" in flights - I suspect it could be the radiative forcing factor, which is applied usually to emissions from flights

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_rf_international_non_uk-distance_na-weight_na-contrails_na,International air freight - to/from non-UK - RF,tonne-km,1.12757777,1.12776278,1.12609,0.0
What is RF here? It is not the "radiative forcing" factor by chance here? I think this means this EF includes contrails actually

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_na-distance_rf_short_haul-weight_na-contrails_na,Short-haul air freight - to/from UK_RF,tonne-km,2.37092687,2.37131567,2.3678,0.00009,0.01179,not-sup
Naming is a bit off with UK_RF - I think here is RF also means with contrails

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Travel,passenger_flight-route_type_domestic-aircraft_type_rf-distance_na-class_na-contrails_na,Domestic flight - to/from UK - average passenger - RF,passenger-km,0.25388726,0.25392848,0
Same here?

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_transit_rail-fuel_source_na,"Transit rail (i.e. Subway, tram)",passenger-mile,0.1195205,0.1195691,0.119,0.0025,0.0017,not-supplied,not-supplied,3,12,G
comma in the description!

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_lpg-engine_size_na-vehicle_age_na-vehicle_weight_na,LPG EV vans - average (up to 3.5 tonnes) ,mile,0.43739943,0.4374438,0.43704,0.0000
Probably here the weight should be added to the id?

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_lpg-engine_size_na-vehicle_age_na-vehicle_weight_na,LPG EV vans - average (up to 3.5 tonnes) ,mile,0.43739943,0.4374438,0.43704,0.0000
There is an extra space at the end of name

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_lpg-engine_size_na-vehicle_age_na-vehicle_weight_na,LPG EV vans - average (up to 3.5 tonnes) ,mile,0.43739943,0.4374438,0.43704,0.0000
Probably we need to be consistent with using "up to" or ">=" (see lines 2565 and 2017)

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_petrol-engine_size_na-vehicle_age_na-vehicle_weight_na,Petrol EV vans - average (up to 3.5 tonnes) ,mile,0.37929358,0.37932997,0.37898
extra space at the end of the name column

2022-02-03 14:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_na-engine_size_na-vehicle_age_na-vehicle_weight_na,Vans - average (up to 3.5 tonnes) ,mile,0.40277906,0.4028747,0.40201,0.00002,0.0029
extra space at the end of the name column

2022-02-03 14:51 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_lpg-engine_size_na-vehicle_age_na-vehicle_weight_na,LPG EV vans - average (up to 3.5 tonnes) ,mile,0.43739943,0.4374438,0.43704,0.0000
About the weight you are correct. But since we don't have it in the same EF from BEIS, I didn't include it for consistency. But I can include it in this one

2022-02-03 17:16 UTC, patstirling requested changes

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv-fuel_source_all_diesel-vehicle_weight_na-percentage_load_na,All diesel HGV,tonne-km,0.10855412,0.1086266,0.10797,0.00004,0.0022,not-supplied,
Think this would be better named and described as "HGV (all diesel)" to reflect the source

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv_refrigerated-fuel_source_all_diesel-vehicle_weight_na-percentage_load_na,All diesel HGV refrigerated,tonne-km,0.127430973,0.127503453,0.12684
Think this would be better named and described as "HGV refrigerated (all diesel)" to reflect the source

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_lng_tanker-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Sea tanker - lng tanker - average,tonne-km,0.011431159,0.011436265,0.01139,0.000003
capitalise "LNG" in name and description

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_lpg_tanker-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Sea tanker - lpg tanker - average,tonne-km,0.010277184,0.010281795,0.01024,0.000003
capitalise "LPG" in name and description

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_hgv-fuel_source_all_diesel-engine_size_na-vehicle_age_na-vehicle_weight_na,All diesel HGV,km,0.85699881,0.85741971,0.85361,0.00017,0.01277,not-supplie
Think this would be better named and described as "HGV (all diesel)" to reflect the source

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_hgv-fuel_source_all_diesel-engine_size_na-vehicle_age_na-vehicle_weight_na,All diesel HGV,mile,1.37920331,1.37988065,1.37375,0.00027,0.02055,not-suppl
Think this would be better named and described as "HGV (all diesel)" to reflect the source

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_hgv_refrigerated-fuel_source_all_diesel-engine_size_na-vehicle_age_na-vehicle_weight_na,All diesel HGV refrigerated,km,1.006239064,1.006659964,1.00285
Think this would be better named and described as "HGV refrigerated (all diesel)" to reflect the source

2022-02-03 17:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_hgv_refrigerated-fuel_source_all_diesel-engine_size_na-vehicle_age_na-vehicle_weight_na,All diesel HGV refrigerated,mile,1.61938331,1.62006065,1.61393
Think this would be better named and described as "HGV refrigerated (all diesel)" to reflect the source

2022-02-03 17:18 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_lpg-engine_size_na-vehicle_age_na-vehicle_weight_na,LPG EV vans - average (up to 3.5 tonnes) ,mile,0.43739943,0.4374438,0.43704,0.0000
I think we do include weight in the [equivalent BEIS EF](https://explorer.climatiq.io/emission-factor/lpg-van-up-to-35-tonnes-transport-road-transport-united-kingdom-2021-beis)?

2022-02-03 19:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_rf_international_non_uk-distance_na-weight_na-contrails_na,International air freight - to/from non-UK - RF,tonne-km,1.12757777,1.12776278,1.12609,0.0
Hum... I think we can keep them all here and the ID differentiates between w/wo contrails. It is also good for comparison and understanding how much RF contributes to emissions. We can add BEIS non-RFs later?

2022-02-04 09:39 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_rf_international_non_uk-distance_na-weight_na-contrails_na,International air freight - to/from non-UK - RF,tonne-km,1.12757777,1.12776278,1.12609,0.0
I agree with Maryam! We have the "contrails" sub-id to account for this. I think it is necessary bc RF factor, depending on the source and approach to calculate, can vary between 1.5 and 3 (at least the values I have seen in the literature), and maybe some users/developers want to apply their preferred RF factor in their calculations or apps, developed on the basis of the OEFDB

2022-02-04 10:09 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_rf_international_non_uk-distance_na-weight_na-contrails_na,International air freight - to/from non-UK - RF,tonne-km,1.12757777,1.12776278,1.12609,0.0
OK, fair point on comparison, and we do actually have EFs without the RF uplift. But we'll need to do more than have it in the ID, it will need to be clear in the name and the description also per above. We'll need a good shorthand for name, suggest "with RF effect" and "including radiative forcing (RF) effect reflecting impact of contrails and high-altitude release of GHGs"

2022-02-04 12:02 UTC, patstirling requested changes

2022-02-04 12:02 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_van-fuel_source_petrol-engine_size_na-vehicle_age_na-vehicle_weight_na,Petrol EV vans - average (up to 3.5 tonnes) ,mile,0.37929358,0.37932997,0.37898
EV still in the name and description here

2022-02-04 13:15 UTC, patstirling approved these changes

2022-02-04 13:16 UTC, merged