Update OEFDB_sources.md
climatiq/Open-Emission-Factors-DB pull request #172
Opened 2022-02-14 14:44 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Multiple_

**What?**

_Added GHG protocol EFs source info._

**Why?**

_Complete the source table._

2022-02-14 14:56 UTC, patstirling requested changes

2022-02-14 14:56 UTC, patstirling commented on OEFDB_sources.md
> +| GHG Protocol | 2021 | [GHG Emissions Calculation Tool](https://ghgprotocol.org/ghg-emissions-calculation-tool) | EFs are retrieved from the GHG Emissions Calculation Tool.xlsx, Emission Factors tab
remove "the" before "the third parties" and good to go!

2022-02-14 17:57 UTC, AnastasiaLobanova approved these changes

2022-02-15 09:40 UTC, patstirling approved these changes

2022-02-15 09:42 UTC, merged