Fix ADEME Rail Travel error
climatiq/Open-Emission-Factors-DB pull request #173
Opened 2022-02-16 12:38 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Rail Travel_

**What?**

_Fix value, name, and ID errors in ADEME Rail Travel_

**Why?**

_Removing errors found in the OEFDB_

2022-02-17 12:25 UTC, patstirling requested changes
Looks good - just a query on LCA for fuel combustion - I think either the LCA or the description needs to be updated in these

2022-02-17 12:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_regional_express-fuel_source_na,Regional Express Train (Paris and suburbs),passenger-km,0.0296,,,,,,,60,,upstream,ADEME,2021,FR-PAR,2021/11/30,Emissio
according to description, this can include fuel combustion, as they are not all electric - should we not keep that in the LCA?

2022-02-17 12:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),passenger-km,0.00728,,,,,,,20,,upstream,ADEME,2021,FR-PAR,202
according to description, this can include fuel combustion, as they are not all electric - should we not keep that in the LCA?

2022-02-17 12:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_mainline-fuel_source_na,Mainline train,passenger-km,0.00592,,,,,,,20,,upstream,ADEME,2021,FR,2021/11/30,Emission intensity for mainline train includin
according to description, this can include fuel combustion, as they are not all electric - should we not keep that in the LCA?

2022-02-17 13:49 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-fuel_source_na,High speed train,passenger-km,0.00236,,,,,,,20,,upstream,ADEME,2021,FR,2021/11/30,Emission intensity for high speed train in
The source "combustion" emissions zero for these EFs:

https://bilans-ges.ademe.fr/en/basecarbone/donnees-consulter/liste-element/categorie/180

2022-02-22 08:39 UTC, patstirling approved these changes

2022-02-22 09:18 UTC, merged