Fix duplicates
climatiq/Open-Emission-Factors-DB pull request #174
Opened 2022-02-17 22:15 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Multiple_

**What?**

_Fix duplicates by changing IDs._

**Why?**

_Eliminate any potential errors due to the existence of duplicates in OEFDB._

2022-02-18 08:45 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_losses,Transmission & distribution – WTT,kWh,,0.021287,,,,,,,,well_to_tank,BEIS,2021,AF,2021/12/21,Emission intensity of WTT transmission & distr
I think it is a great solution here to add it to the id! I wonder if it make sense now to have `electricity-energy_source_grid_mix_losses`? Or maybe we can just go around with `electricity-energy_source_grid_mix_losses`? It won't break our id-subid structure

2022-02-18 09:02 UTC, AnastasiaLobanova requested changes
Great job Maryam! Thank you for tackling these - I see the checker still complains that there are duplicates in these lines [780, 781] - I guess the changes added to the name column and not to the id. 

And there are also 2 ids with spaces in them - could you also correct them? I think it is ok to have one PR for them all?

2022-02-18 09:05 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_100percent-fuel_use_biodiesel_medium_and_heavy_duty_vehicles,Biodiesel (100%) - biodiesel medium and heavy-duty vehicles_8.8_fuel_efficiency,gal (US),0.012892,0.014212
corrected:)

2022-02-21 10:13 UTC, AnastasiaLobanova approved these changes
Great!! We have green checks! Thank you Maryam!

2022-02-21 10:49 UTC, motin commented
I merged the main branch into this one to double-check that green checks are still around :)

2022-02-21 11:30 UTC, merged