2022 EPA eGrid ingress
climatiq/Open-Emission-Factors-DB pull request #182
Opened 2022-03-03 19:08 UTC by patstirling

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Energy > Electricity

**What?**

US EPA have released their latest eGrid numbers - data provided here.

**Why?**

Top ensure latest US electricity grid emission factors are available

2022-03-04 10:13 UTC, maryarbab requested changes

2022-03-04 10:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_akgd,US eGRID subregion AKGD (ASCC Alaska Grid),kWh,not-supplied,0.500858,0.497882,0.001134,0.001892,not-supplied,not-supplied,,2,electricity_gen
I think the region needs to reflect the egrid subregion and also be consistent with how it is specified in the OEFDB currently (e.g. row 736).

2022-03-04 10:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_akgd,US eGRID subregion AKGD (ASCC Alaska Grid),kWh,not-supplied,0.500858,0.497882,0.001134,0.001892,not-supplied,not-supplied,,2,electricity_gen
IDs are also not consistent with other EPA egrid EFs.

2022-03-04 10:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight-route_type_domestic-distance_na-weight_na-rf_included,Domestic air freight - with RF effect,tonne-km,,4.76719,,,,,,,,fuel_combustion,MfE,2020,NZ,2021/09/10,"Emiss
Would this cause any conflict? Same as 2190, 2198, 2784, and 3037.

2022-03-04 15:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kWh,not-supplied,0.717,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,2/3,electricity_generation,GHG Protocol,2017,AE
Done!

2022-03-04 15:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight-route_type_domestic-distance_na-weight_na-rf_included,Domestic air freight - with RF effect,tonne-km,,4.76719,,,,,,,,fuel_combustion,MfE,2020,NZ,2021/09/10,"Emiss
Shouldn't do - no changes made to these lines and this passed ID checks last time

2022-03-04 16:31 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_akgd,US eGRID subregion AKGD (ASCC Alaska Grid),kWh,not-supplied,0.500858,0.497882,0.001134,0.001892,not-supplied,not-supplied,,2,electricity_gen
fixed - thanks!

2022-03-06 17:16 UTC, maryarbab approved these changes

2022-03-07 09:27 UTC, merged