Exiobase ingress 2
climatiq/Open-Emission-Factors-DB pull request #189
Opened 2022-03-10 10:00 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Multiple

**What?**

Exiobase ingress 2 for Germany 2019

**Why?**

The final part to round up our portfolio of spend-based efs

2022-03-10 12:47 UTC, maryarbab requested changes

2022-03-10 12:47 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_distribution_trade_services_of_electricity,Distribution and trade services of electricity,EUR,0.7556556423,0.7527454686,not-supplied,not-supplied,not-supp
To me it should be electricity_distribution_trade_services_of_electricity. We do not have any energy source here, which makes me wonder if such ID structure (i.e. including energy source sub category) actually can make sense for spend based EFs or even others...

2022-03-10 13:04 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_transmission_services_of_electricity,Transmission services of electricity,EUR,1.2088738058,1.2062291735,not-supplied,not-supplied,not-supplied,not-supplie
I'm not certain it's quite accurate to call this "losses" - I don't think people are spending money on losses after all! It's more likely that this is expenditure on the infrastructure costs of transmitting electricity; suggestion below

```suggestion
Energy,Electricity,electricity-transmission_services_of_electricity,Transmission services of electricity,EUR,1.2088738058,1.2062291735,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,na,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: transmission services of electricity. Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not.,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-10 13:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_transmission_services_of_electricity,Transmission services of electricity,EUR,1.2088738058,1.2062291735,not-supplied,not-supplied,not-supplied,not-supplie
As long as we take the energy_source out, it is fine with me!

2022-03-10 14:59 UTC, patstirling requested changes
A couple more things it could be worth discussing/looking at the source data together?

2022-03-10 14:59 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_cereal_grains,Cereal grains (not elsewhere specified),EUR,1.09282837,1.1743995761,not-supplied,not-supplied,not-supplied,not-su
I think we need to make the IDs here more explicit otherwise it implies that this is a catch-all - suggest we apply this to all such EFs in the dataset

```suggestion
Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_cereal_grains_not_elsewhere_specified,Cereal grains (not elsewhere specified),EUR,1.09282837,1.1743995761,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,na,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: cereal grains (not specified in other EXIOBASE emission factors). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not.,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-10 17:24 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_distribution_services_of_gaseous_fuels_through_mains-fuel_use_na,Distribution services of gaseous fuels through mains,EUR,0.7228332099,0.7197005263,not-supplied,not-supplied,not
Agree to have a new category.

2022-03-10 17:25 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_cereal_grains,Cereal grains (not elsewhere specified),EUR,1.09282837,1.1743995761,not-supplied,not-supplied,not-supplied,not-su
okay

2022-03-10 17:39 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Manufacturing,Machinery,machinery-type_machinery_equipment,Machinery and equipment (not elsewhere specified),EUR,0.2482930032,0.2448604145,not-supplied,not-supplied,not-supplied,not-supplied,not-supp
The categorization in EXIOBASE refers to manufacturing in this case, https://docs.google.com/spreadsheets/d/1cHImwfwpEZzrNmkM7rYX_WdWwz4iT7y1zNjg8JQ9evY/edit#gid=0

unless they are the emissions from manufacturing these rather than buying them? I think, if I spend 100$ on a screwdriver I generate emissions from its manufacturing?

2022-03-10 17:46 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_railway_transportation_services-fuel_source_na,Railway transportation services,EUR,0.1379389414,0.1364899444,not-supplied,not-supplied,not-supplied,not-sup
No we are not certain we just discussed it together, as far I as remember

2022-03-11 09:15 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_railway_transportation_services-fuel_source_na,Railway transportation services,EUR,0.1379389414,0.1364899444,not-supplied,not-supplied,not-supplied,not-sup
Ah - that makes things really tricky. I'd suggest we put these into "Transport services" (renaming "Freight services" at the same time - we keep forgetting to do this!) with the description of these EFs making it clear that this is valid for passenger travel or freight of goods

2022-03-11 09:18 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Manufacturing,Machinery,machinery-type_machinery_equipment,Machinery and equipment (not elsewhere specified),EUR,0.2482930032,0.2448604145,not-supplied,not-supplied,not-supplied,not-supplied,not-supp
I see the point, but the question needs to come the other way round: is the person using this EF buying a screwdriver, or are they the manufacturer of screwdrivers spending money on the process? If it's the former, this should go into equipment sector, if it's the latter it should go into the manufacturing sector. This is similar to the agricultural vs consumer goods decision (is it the farmer spending money on cattle or the consumer spending money on the products of cattle farming?)

2022-03-11 09:55 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_railway_transportation_services-fuel_source_na,Railway transportation services,EUR,0.1379389414,0.1364899444,not-supplied,not-supplied,not-supplied,not-sup
The Freight Services are renamed? Or did I miss some? 


And yes - ok to add those to the Transport Services category

2022-03-11 10:49 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_transmission_services_of_electricity,Transmission services of electricity,EUR,1.2088738058,1.2062291735,not-supplied,not-supplied,not-supplied,not-supplie
Yep, this one can go into the new "Energy Services" category - will suggest a new name in final review to clean up the "services" language :)

2022-03-11 15:58 UTC, maryarbab submitted a review, later dismissed

2022-03-11 15:58 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_wheat,Wheat,EUR,1.1683155313,1.2661901872,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,
Do we need to include "The lca boundaries of these factors are not defined by the source." in the source as the lca_activity is already specified as unknown?

2022-03-11 16:09 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_wheat,Wheat,EUR,1.1683155313,1.2661901872,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,
we had a chat about this today and felt that because these factors are alongside other spend-based factors which have specified boundaries (EPA - we indicate that these are cradle-to-shelf in the description) that it would be worth calling out - otherwise they appear to be comparable if you don't specifically check the lca_activity field. What do you think?

2022-03-11 16:10 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_wheat,Wheat,EUR,1.1683155313,1.2661901872,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,
Okay, makes sense....

2022-03-11 16:11 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_wheat,Wheat,EUR,1.1683155313,1.2661901872,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,
Note though that we should use "LCA" rather than "lca" @AnastasiaLobanova

2022-03-11 16:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Energy Services,energy_services-type_distribution_services_of_gaseous_fuels_through_mains,Distribution services of gaseous fuels through mains,EUR,0.7228332099,0.7197005263,not-supplied,not-su
```suggestion
Energy,Energy Services,energy_services-type_distribution_of_gaseous_fuels_through_mains_services,Distribution of gaseous fuels through mains (services),EUR,0.7228332099,0.7197005263,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: distribution of gaseous fuels through mains (services). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The lca boundaries of these factors are not defined by the source. These factors include effects of international trade. ,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-11 16:26 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat_and_steam-type_steam_hot_water_supply_services,Steam and hot water supply services,EUR,17.0589555931,17.0560581709,not-supplied,not-supplied,not-supplied,not-supplied,not-s
```suggestion
Energy,Heat and Steam,heat_and_steam-type_steam_hot_water_supply_services,Steam and hot water supply (services),EUR,17.0589555931,17.0560581709,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: steam and hot water supply (services). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The lca boundaries of these factors are not defined by the source. These factors include effects of international trade. ,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-11 16:27 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Equipment,Equipment Rental,equipment_rental-type_renting_services_of_machinery_equipment_without_operator_of_personal_household_goods,Rental services of machinery and equipment (without operator) and
```suggestion
Equipment,Equipment Rental,equipment_rental-type_rental_of_machinery_equipment_without_operator_of_personal_household_goods,Rental of machinery and equipment (without operator) and of personal and household goods (services),EUR,0.1415135161,0.1400993318,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: rental of machinery and equipment (without operator) and of personal and household goods (services). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The lca boundaries of these factors are not defined by the source. These factors include effects of international trade. ,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-11 16:28 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Restaurants and Accommodation,Restaurants and Accommodation,restaurants_accommodation-type_hotel_restaurant_services,Hotel and restaurant services,EUR,0.08058471,0.0797962276,not-supplied,not-supplie
```suggestion
Restaurants and Accommodation,Restaurants and Accommodation,restaurants_accommodation-type_hotel_restaurant_services,Hotel and restaurant (services),EUR,0.08058471,0.0797962276,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: hotel and restaurant (services). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The lca boundaries of these factors are not defined by the source. These factors include effects of international trade. ,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-11 16:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-collected_purified_water_distribution_services_of_water,Collected and purified water/distribution services of water,EUR,0.5925026481,0.5877949211,not-supplied,not-supplied
```suggestion
Water,Water Treatment,water-collected_purified_water_distribution_of_water_services,Collected and purified water/distribution of water (services),EUR,0.5925026481,0.5877949211,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,2021,DE,2022/03/02,Emission intensity of supply chain in EUR spend on: collected and purified water/distribution of water (services). Retrieved from the EXIOBASE v3 model outputs for products. These factors were calculated based on 2019 data. CO2 equivalent factors incorporate emissions from land use; constituent gases have not been included as they do not. The lca boundaries of these factors are not defined by the source. These factors include effects of international trade. ,https://zenodo.org/record/5589597#.Yh9_Zi8w1ao
```

2022-03-11 19:11 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-type_wheat,Wheat,EUR,1.1683155313,1.2661901872,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,unknown,EXIOBASE,
Yess!

2022-03-15 11:45 UTC, patstirling reviewed
Just a tiny ID change and we are there!

2022-03-15 14:49 UTC, merged