BEIS ingress v3 - Fuel
climatiq/Open-Emission-Factors-DB pull request #208
Opened 2022-03-24 16:15 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Fuel_

**What?**

_Complete BEIS fuel category emissions factors_

**Why?**

_To update the existing EFs and add any missing one from the source._

2022-03-25 13:16 UTC, patstirling requested changes

2022-03-25 13:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation,Aviation spirit,tonne,,3192.76,3127.67,35.29,29.8,,,,1,fuel_combustion,BEIS,2021,2021,2021,GB,,2022/3/20,Emission intensity of stationary combustion of f
Think these dates should be "2022/03/20" to align with format elsewhere in the DB?

2022-03-25 13:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biopetrol-fuel_use_na,Bio Petrol,GJ,,,70.21,not-supplied,not-supplied,,,,Outside of scopes,fuel_combustion,BEIS,2021,2021,2021,GB,,2022/3/20,Emission intensity of stationary com
All of the biofuel entries have these "outside of scope" entries - not sure what these are, could we have something in the name, description & ID to distinguish them from the other EFs?

2022-03-25 13:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation,Aviation spirit,kWh,,0.24375,0.23878,0.00269,0.00228,,,,1,fuel_combustion,BEIS,2021,2021,2021,GB,,2022/3/20,Emission intensity of stationary combustion o
All entries should have "not-supplied" in any of the gas columns that don't have a number

2022-03-25 15:32 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_avgas-fuel_use_aviation,Aviation spirit,kWh,,0.24375,0.23878,0.00269,0.00228,,,,1,fuel_combustion,BEIS,2021,2021,2021,GB,,2022/3/20,Emission intensity of stationary combustion o
Would this break the existing IDs?

2022-03-28 09:52 UTC, AnastasiaLobanova requested changes
In principle I have only the question about the outside the scopes

2022-03-28 11:04 UTC, AnastasiaLobanova approved these changes

2022-03-28 15:01 UTC, patstirling requested changes

2022-03-30 08:18 UTC, patstirling approved these changes

2022-03-30 08:32 UTC, merged