BEIS v3 ingress - refrigerant gases
climatiq/Open-Emission-Factors-DB pull request #210
Opened 2022-03-30 10:19 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Refrigerants and Fugitive Gases_

**What?**

_Complete BEIS "Refrigerants and Fugitive Gases" category emissions factors_

**Why?**

_To update the existing EFs and add any missing ones from the source._

2022-03-30 15:41 UTC, AnastasiaLobanova approved these changes
Looks good Maryam!!

2022-03-31 08:45 UTC, patstirling requested changes

2022-03-31 08:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Refrigerants and Fugitive Gases,Refrigerants and Fugitive Gases,fugitive_gas-type_carbon_dioxide,Carbon dioxide,kg,not-supplied,1,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,1|2
Just a small spot - could this edit be applied to all of the BEIS EFs please?
```suggestion
Refrigerants and Fugitive Gases,Refrigerants and Fugitive Gases,fugitive_gas-type_carbon_dioxide,Carbon dioxide,kg,not-supplied,1,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,1|2|3,unknown,BEIS,2021,2007-2021,2007,GB,,2021/11/26,Emission intensity for carbon dioxide. This conversion factor should be used to report leakage from air-conditioning refrigeration units or the release to the atmosphere of other gases that have global warming potential (GWP). Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL.,https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
```

2022-03-31 10:52 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Refrigerants and Fugitive Gases,Refrigerants and Fugitive Gases,fugitive_gas-type_carbon_dioxide,Carbon dioxide,kg,not-supplied,1,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,1|2
Done:)

2022-04-01 08:43 UTC, patstirling approved these changes

2022-04-01 09:05 UTC, merged