BEIS ingress v3- Air & Rail
climatiq/Open-Emission-Factors-DB pull request #223
Opened 2022-04-07 13:43 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] New
- [*] Update

**What category or categories does it affect?**

_Air Travel, Air Freight, Rail Travel, Rail Freight_

**What?**

_Complete BEIS Air & Rail category emissions factors_

**Why?**

_To update the existing EFs and add any missing ones from the source._

2022-04-07 15:07 UTC, patstirling requested changes

2022-04-07 15:07 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight-route_type_outside_uk_wtt-distance_na-weight_na-rf_included,Air freight outside UK - with RF effect - WTT,tonne-km,not-supplied,0.11157,not-supplied,not-supplied,
suggest we put "_wtt" after "fright_flight" as it refers to something more fundamental than the "route_type"

2022-04-08 03:00 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight-route_type_outside_uk-distance_na-weight_na-rf_included,Air freight outside UK - with RF effect,tonne-km,not-supplied,1.0189,1.01381,0.00004,0.00505,not-supplied,
Edited the descriptions to reflect the uplift note for the combustion EFs, not the WTT ones.

2022-04-08 03:00 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight-route_type_outside_uk_wtt-distance_na-weight_na-rf_included,Air freight outside UK - with RF effect - WTT,tonne-km,not-supplied,0.11157,not-supplied,not-supplied,
Done:)

2022-04-08 09:09 UTC, AnastasiaLobanova approved these changes
Looks very good Maryam! I just wanted to clarify the application of RF factor to WTT EFs - is it coming from the source?

2022-04-08 09:09 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight_wtt-route_type_domestic-distance_na-weight_na-rf_excluded,Domestic air freight - without RF effect - WTT,tonne-km,not-supplied,0.49186,not-supplied,not-supplied,n
Should wtt actually include RF effect at all? Because it is about sourcing, production and delivery of fuel to a plane, if I understand it right?

2022-04-08 09:09 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight_wtt-route_type_international-distance_long_haul_gt_3700km-weight_na-rf_included,International air freight long haul - with RF effect - WTT,tonne-km,not-supplied,0
Re long and short haul flights, do we specify distances somewhere except for ids? in the documentation?

2022-04-08 10:45 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight_wtt-route_type_international-distance_long_haul_gt_3700km-weight_na-rf_included,International air freight long haul - with RF effect - WTT,tonne-km,not-supplied,0
Not sure about the doc. Will make a note to include it there.

2022-04-08 11:03 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Freight,freight_flight_wtt-route_type_international-distance_long_haul_gt_3700km-weight_na-rf_included,International air freight long haul - with RF effect - WTT,tonne-km,not-supplied,0
Thank you!!

2022-04-08 14:09 UTC, patstirling approved these changes

2022-04-08 14:09 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix_biogenic_CO2,Grid mix (incl. biogenic CO2 factors),kWh,not-supplied,not-supplied,0.1068678568,not-supplied,not-supplied,not-supplied,not-supplied
Is this fixing an earlier error? Should be ok as it's very new, but as ever, ID changes are to be avoided!

2022-04-08 14:10 UTC, merged