BEIS ingress v3 - Sea & Road
climatiq/Open-Emission-Factors-DB pull request #224
Opened 2022-04-08 14:21 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] New
- [*] Update

**What category or categories does it affect?**

_ Sea Travel, Sea Freight, Road Freight, Road Travel_

**What?**

_Complete BEIS transport category emissions factors_

**Why?**

_To update the existing EFs and add any missing ones from the source._

2022-04-08 15:05 UTC, patstirling requested changes

2022-04-08 15:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_gt_2000_lm-tonnage_na-fuel_source_na,RoRo-ferry >2000 LM,tonne-km,not-supplied,0.050189,0.0495,0.000015,0.000674,n
```suggestion
Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_gt_2000_lm-tonnage_na-fuel_source_na,RoRo-ferry >2000 LM,tonne-km,not-supplied,0.050189,0.0495,0.000015,0.000674,not-supplied,not-supplied,,3,fuel_combustion,BEIS,2021,2021,,GB,,2022/03/20,Emission intensity for roll-on/roll-off (RoRo) ferry of greater than 2000 lane meters. A lane meter is a unit of deck area in roll-on/roll-off ships.Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL.,https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
```

2022-04-08 15:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_gt_2000_lm-tonnage_na-fuel_source_na,RoRo-ferry >2000 LM - WTT,tonne-km,not-supplied,0.011272,not-supplied,not-sup
```suggestion
Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_gt_2000_lm-tonnage_na-fuel_source_na,RoRo-ferry >2000 LM - WTT,tonne-km,not-supplied,0.011272,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,well_to_tank,BEIS,2021,2021,,GB,,2022/03/20,Emission intensity of WTT for roll-on/roll-off (RoRo) ferry of greater than 2000 lane meters. A lane meter is a unit of deck area in roll-on/roll-off ships. Well-to-tank (WTT) conversion factors for delivery vehicles & freighting goods should be used to report the upstream Scope 3 emissions associated with extraction/refining and transportation of the raw fuels before they are used to power the transport mode. Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL.,https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
```

2022-04-08 15:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_between_0_and_1999_lm-tonnage_na-fuel_source_na,RoRo-ferry 0 - 1999 LM,tonne-km,not-supplied,0.061139,0.0603,0.000
```suggestion
Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_between_0_and_1999_lm-tonnage_na-fuel_source_na,RoRo-ferry 0 - 1999 LM,tonne-km,not-supplied,0.061139,0.0603,0.000018,0.000821,not-supplied,not-supplied,,3,fuel_combustion,BEIS,2021,2021,,GB,,2022/03/20,Emission intensity for roll-on/roll-off (RoRo) ferry of between 0 and 1999 lane meters. A lane meter is a unit of deck area in roll-on/roll-off ships. Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL.,https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
```

2022-04-08 15:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_between_0_and_1999_lm-tonnage_na-fuel_source_na,RoRo-ferry 0 - 1999 LM - WTT,tonne-km,not-supplied,0.013731,not-su
```suggestion
Transport,Sea Freight,sea_freight-vessel_type_roro_ferry-route_type_na-vessel_length_between_0_and_1999_lm-tonnage_na-fuel_source_na,RoRo-ferry 0 - 1999 LM - WTT,tonne-km,not-supplied,0.013731,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,well_to_tank,BEIS,2021,2021,,GB,,2022/03/20,Emission intensity of WTT for roll-on/roll-off (RoRo) ferry of between 0 and 1999 lane meters. A lane meter is a unit of deck area in roll-on/roll-off ships. Well-to-tank (WTT) conversion factors for delivery vehicles & freighting goods should be used to report the upstream Scope 3 emissions associated with extraction/refining and transportation of the raw fuels before they are used to power the transport mode. Retrieved from the Conversion Factors 2021: flat file published by the UK BEIS/Defra at the source URL.,https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2021
```

2022-04-08 15:21 UTC, AnastasiaLobanova submitted a review, later dismissed
Looks good but there are some dates issues - 2022/3/20 and 2022/03/20 in the Road Freight and Road Travel part. I remember it was before also not sure if we have decided to format dates afterwards.

And just a clarification - year calculated is missing because  BEIS provides no info on this?

2022-04-08 15:26 UTC, AnastasiaLobanova approved these changes

2022-04-11 10:08 UTC, patstirling approved these changes

2022-04-11 10:09 UTC, merged