Fixing small issues
climatiq/Open-Emission-Factors-DB pull request #230
Opened 2022-04-19 16:20 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] Update

**What category or categories does it affect?**

_Multiple_

**What?**

_Adding new scopes to GHG protocol refrigerant gases, fixing the cradle_to_gate typo in BEIS data, and revising one waste category._

**Why?**

_To increase the consistency in the OEFDB_

2022-04-25 11:44 UTC, patstirling requested changes

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_household_residual_waste-disposal_method_anaerobic_digestion,Household residual waste disposal - anaerobic digestion,tonne,not-supplied,8.951,not-supplied,not-supplied,n
Not sure we need a new category here - how does this differ from "General Waste"?

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_household_residual_waste-disposal_method_open_loop,Household residual waste disposal - open-loop,tonne,not-supplied,21.294,not-supplied,not-supplied,not-supplied,not-sup
This definitely needs to change (from glass) - but again think this is just "General Waste"?

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_mixed_food_and_organic_garden-disposal_method_combustion,Mixed food and garden waste (organic) - combustion,tonne,not-supplied,21.294,not-supplied,not-supplied,not-suppl
I think this one should be category "Food and Organic Waste"?

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_mixed_food_and_organic_garden-disposal_method_anaerobic_digestion,Mixed food and garden waste disposal (organic) - anaerobic digestion,tonne,not-supplied,8.951,not-suppl
I think this one should be category "Food and Organic Waste"?

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_mixed_food_and_organic_garden-disposal_method_composting,Mixed food and garden waste disposal (organic) - composting,tonne,not-supplied,8.951,not-supplied,not-supplied,n
I think this one should be category "Food and Organic Waste"?

2022-04-25 11:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_mixed_food_and_organic_garden-disposal_method_landfill,Mixed food and garden waste disposal (organic) - landfill,tonne,not-supplied,587.344,not-supplied,not-supplied,not
I think this one should be category "Food and Organic Waste"?

2022-04-25 13:16 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Waste,Refuse Waste,waste_type_household_residual_waste-disposal_method_anaerobic_digestion,Household residual waste disposal - anaerobic digestion,tonne,not-supplied,8.951,not-supplied,not-supplied,n
It is the category defined by the source (BEIS). Let's discuss if we want to stick with the source category or not? @patstirling

2022-04-26 12:03 UTC, patstirling approved these changes

2022-04-26 12:05 UTC, merged