adding EXIOBASE 2021 for AT AU BG
climatiq/Open-Emission-Factors-DB pull request #250
Opened 2022-05-18 09:49 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Multiple

**What?**

adding EXIOBASE 2021 for AT AU BG

**Why?**

Part of entire EXIOBASE ingress

2022-05-18 13:41 UTC, maryarbab commented
Looks great! A few notes:

- Shouldn't these EFs be part of the fuel category: 

Coking coal
Lignite/brown coal
Natural gas liquids
Other bituminous coal
Patent fuel
Sub-bituminous coal
Charcoal

- Should "Retail trade of motor fuel (services)" be in the fuel category?

- Does "Other transport equipment" refer to passenger vehicle?

2022-05-18 13:41 UTC, maryarbab requested changes
Looks great! A few notes:

Shouldn't these EFs be part of the fuel category:
Coking coal
Lignite/brown coal
Natural gas liquids
Other bituminous coal
Patent fuel
Sub-bituminous coal
Charcoal

Should "Retail trade of motor fuel (services)" be in the fuel category?

Does "Other transport equipment" refer to passenger vehicle?

2022-05-19 08:22 UTC, patstirling approved these changes
Looks good to me!

2022-05-19 10:54 UTC, maryarbab approved these changes

2022-05-19 11:20 UTC, merged