[draft] new validation added branch ref
climatiq/Open-Emission-Factors-DB pull request #261
Opened 2022-05-30 06:47 UTC by GeeWee

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [ ] Update

**What category or categories does it affect?**

_Add your answer here_

**What?**

_Please describe the changes or additions_

**Why?**

_Please give a brief explanation of why these changes are valuable or necessary_

2022-05-30 09:50 UTC, grindcode submitted a review, later dismissed
LGTM!

2022-05-30 10:20 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +allow_empty = false
I think this column can be empty - it means the data quality is ok, it contains flags if there is something wrong

2022-05-30 10:34 UTC, maryarbab requested changes

2022-05-30 10:34 UTC, maryarbab commented on metadata/schema.toml
> +validators = ["is_year"]
shouldn't "years_calculated_from" be also a string, in case there are multiple years?

2022-05-30 10:34 UTC, maryarbab commented on metadata/schema.toml
> +validators = ["is_allowed_string", "is_ascii"]
@AnastasiaLobanova @patstirling shouldn't we also have "not-supplied" in case the LCA activity is unknown (i.e. such methodology is not supplied by the source)?

2022-05-30 10:44 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +validators = ["is_allowed_string", "is_ascii"]
I think probably the broader validator of `is_allowed_string` also includes the `not-supplied` string, but Gustav can say for sure :)

2022-05-30 10:45 UTC, GeeWee commented on metadata/schema.toml
> +allow_empty = false
I think you'er right!

2022-05-30 10:46 UTC, GeeWee commented on metadata/schema.toml
> +name = "name"
Unsure - `is_allowed_string` basically just means "this is a non-empty string without a comma"

Currently there are a bunch of names (30 or so) that are non-ascii, so I just adhered to that when creating the schema. Should `name` be ASCII only?

`activity_id` needs to be ascii-only, we rely on that in the API

2022-05-30 10:47 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +name = "description"
Here we have sometimes funky french (sorry!) characters, e.g. in the descriptions of ADEME or UBA...would this be a problem here for this validator?

2022-05-30 10:47 UTC, GeeWee commented on metadata/schema.toml
> +validators = ["is_year"]
Might be! Currently it seems like we only have a single-year entries. I think the good part is that if we then _do_ add something that contains multiple years, we can just edit the schema. I'm open to doing it now if we expect that we'll get multiple years in there soon though.

2022-05-30 10:48 UTC, GeeWee commented on metadata/schema.toml
> +name = "description"
Yes we do! No, `allowed_string` basically just says "no commas" - perhaps we should rename it to "no_commas"? - if we checked for ASCII in description we'd end up with a lot of issues (I tried that at one point :D)

2022-05-30 10:49 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +name = "name"
Ah ok now I get it - I thought allowed string was alphanumeric string with only underscores and hyphens! All good then! 

Then also my comment below is non valid :)

2022-05-30 10:50 UTC, GeeWee commented
Just noting something here - the image is just an example of output that failed back when I tried to validate `name` with the `is_ascii` validator. Currently as you can see with the "1 successful check", the validator validates the OEFDB as-is.

2022-05-30 10:50 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +name = "description"
Hehe! Yes, sorry I got confused :) All good then from my side :)

2022-05-30 10:51 UTC, AnastasiaLobanova submitted a review, later dismissed

2022-05-30 10:52 UTC, GeeWee commented on metadata/schema.toml
> +validators = ["is_allowed_string", "is_ascii"]
`is-allowed-string` is basically just "any string that doesn't contain commas" - but I can see I'll need to rename it a little later to `no_commas` as it's obviously not very good at saying what it actually checks for :D

2022-05-30 10:55 UTC, maryarbab commented on metadata/schema.toml
> +validators = ["is_year"]
sounds good! yup, let's keep it as it is and we can change it if have multiple years.

2022-05-30 10:57 UTC, maryarbab commented on metadata/schema.toml
> +validators = ["is_allowed_string", "is_ascii"]
Yes, but what I actually meant was what we currently have in the DB for these fields in case they are not provided by the source. We can discuss it in the data sync I guess

2022-05-30 11:01 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +validators = ["is_allowed_string", "is_ascii"]
Ah ok - I see! Let's discuss this in the sync indeed

2022-05-30 12:11 UTC, GeeWee commented
@maryarbab requested re-review, not sure if there's still things I need to do here from your end?

2022-05-30 12:12 UTC, maryarbab approved these changes

2022-06-02 08:13 UTC, GeeWee reviewed
Hey team! Can I get another pass on the new schema?

2022-06-02 08:13 UTC, GeeWee commented on metadata/schema.toml
> +validators = ["has_no_commas", "is_ascii"]
Notice that `is_valid_string` has changed name to `has_no_commas` and `is_ascii` is new.

2022-06-02 08:13 UTC, GeeWee commented on metadata/schema.toml
> +allowed_values = [
Note that there is new documentation about how allow_empty works with validators., and the new `allowed_values` feature.

Unfortunately it was a little cumbersome to use the sector-guidance csv sheet. If we find out that having these sectors/categories in more than one place, we can revisit later.

2022-06-02 08:13 UTC, GeeWee commented on metadata/schema.toml
> +validators = ["is_valid_activity_id", "is_ascii"]
New validator here: `is_valid_activity_id` - that checks for alphanumerics and the special id chars allowed.

2022-06-02 09:55 UTC, maryarbab submitted a review, later dismissed

2022-06-02 14:27 UTC, AnastasiaLobanova commented on metadata/schema.toml
> +name = "description"
Hehe - now since those characters really became a problem - we could delete all of them and then really try to check for ASCII in the description? If it won't be too much of a clean up

2022-06-02 14:27 UTC, AnastasiaLobanova approved these changes

2022-06-07 08:08 UTC, AnastasiaLobanova approved these changes

2022-06-07 08:09 UTC, merged