adding Gemis 2021
climatiq/Open-Emission-Factors-DB pull request #276
Opened 2022-07-04 15:59 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

multiple

**What?**

adding Gemis 2021

**Why?**

provide better coverage for DE sources

2022-07-06 01:01 UTC, maryarbab requested changes
Looks great! There are bunch of commas in the description, which might be better to remove to avoid formatting issues in the G sheets.

2022-07-06 20:53 UTC, patstirling requested changes
great dataset - however it is an extremely varied one across not that many EFs so there's a lot of comments!

2022-07-07 08:12 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Energy,Electricity,electricity-energy_source_electricity_power_plant_mix,Electricity power plant mix,KWh,0.543,not-supplied,0.515,0.00058,0.00004,not-supplied,not-supplied,,,upstream-use_phase-trans
the "grid mix" are from statistical data and one from 2015 are calculated, as I understood

2022-07-07 08:30 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Energy,Electricity,electricity-energy_source_electricity_grid_local,Electricity grid local,KWh,0.6,not-supplied,0.569,0.00075,0.00003,not-supplied,not-supplied,,,upstream-electricity_generation-tran
This is statistical data from GEMIS take a look at years calculated from - they have separately grid mix and grid local, I would keep this this way to align with the source

2022-07-07 08:36 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,KWh,0.582,not-supplied,0.552,0.00072,0.00003,not-supplied,not-supplied,,,upstream-electricity_generation,GEMISv5.0,2021,2021,2010,DE,,C
they vary in the year of calculation - this is statistical data from GEMIS

2022-07-07 09:21 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Energy,Heat and Steam,heat-and-steam-type_district_heating_mix,District heating mix,KWh,0.254,not-supplied,0.237,0.00041,0.00002,not-supplied,not-supplied,,,upstream-use_phase-transport,GEMISv5.0,20
These two values are identical - I think it is the same ef, just differently described (I think we need to delete the one in 5742, agree?

2022-07-07 10:07 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +,Energy,Heat and Steam,heat-and-steam-type_district_heating_mix,District heating mix,KWh,0.254,not-supplied,0.237,0.00041,0.00002,not-supplied,not-supplied,,,upstream-use_phase-transport,GEMISv5.0,20
Hm - even though the EFs are the same, concern is that someone using GEMIS previously might expect to see both - one for "district heating" and one for "CHP & district heating"

2022-07-07 12:12 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +,Materials and Manufacturing,Metals,metals-type_aluminium_secondary,Aluminium secondary,kg,1.683,not-supplied,1.48,0.0019,0.00007,not-supplied,not-supplied,,,upstream-manufacturing-transport,GEMISv5.
Could we add the brackets to the name "Aluminium (secondary)"

2022-07-07 12:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +,Materials and Manufacturing,Metals,metals-type_steel_electric,Steel Electric,kg,0.511,not-supplied,0.473,0.0011,0.00002,not-supplied,not-supplied,,,upstream-manufacturing-transport,GEMISv5.0,2021,20
Could we add the brackets to name e.g. "Steel (electric)"

2022-07-07 12:46 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Energy,Heat and Steam,heat-and-steam-type_electric_heat_pump_water,Electric heat pump - Water,KWh,0.148,not-supplied,0.14,0.00017,0.00001,not-supplied,not-supplied,,,upstream-use_phase-transport,GEM
I think description here is explanatory here

2022-07-07 12:48 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +f0e0de67-5ba5-4055-9db5-32a2546cf5bf,Energy,Heat and Steam,heat-and-steam-type_local_heating_chp_biogas,Local heating (biogas-fired CHP),kWh,0.095,not-supplied,0.064,0.00038,0.00008,not-supplied,not-
Done!

2022-07-07 13:13 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Materials and Manufacturing,Metals,metals-type_steel_galvanized,Steel galvanized,kg,2.284,not-supplied,2.043,0.0068,0.00014,not-supplied,not-supplied,,,upstream-manufacturing-transport,GEMISv5.0,202
Oh true! I will correct this - wrong cope paste from my side

2022-07-07 14:29 UTC, patstirling requested changes
Nearly there I think!

Line 2879 was "Power plant mix" which is now "Grid mix" but distinguished from another "Grid mix" only by not including t&d in the LCA. I think this is meant to be an average of the emission intensity of electricity leaving power plants across DE (rather than being delivered to the consumer) so think we can revert this to "Power plant mix" and id="electricity-energy_source_power_plant_mix" to make sure it doesn't accidentally get used as a grid mix.

2022-07-07 15:16 UTC, maryarbab approved these changes

2022-07-07 18:26 UTC, maryarbab approved these changes

2022-07-08 08:49 UTC, patstirling approved these changes
Approved! Strictly speaking as it's a new DB we should be adding details to the source table at the same time as upload - will make a note to follow this up. We should also update the validator tables to allow the source (and for some reason some of the lca codes are being flagged too - will add this to the card)

2022-07-08 08:55 UTC, patstirling requested changes
The validator is failing on ah - lca_activity = ´transport´- think this needs to be ´transport_and_delivery´. Could you confirm @maryarbab ?

2022-07-08 08:55 UTC, patstirling commented on OpenEmissionFactorsDB.csv
>  4b762ea3-2c88-401b-8e58-e8bb1e816b5f,Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kWh,0.56,not-supplied,0.531,0.0006,0.00004,not-supplied,not-supplied,,,upstream-use_phase-transport
ah - hang on, we'd better replace all instances of ´transport´with ´transport_and_delivery´, as the former doesn't exist in our current schema of lca_activity. Could you confirm this is a sensible change @maryarbab ?

2022-07-08 11:04 UTC, GeeWee commented
Remember to add `GEMIS` to the list in the schema - I can see CI is failing

2022-07-08 11:28 UTC, patstirling commented
> 

yes, we may as well do this at the same time now (and update [OEFDB_sources.md](https://github.com/climatiq/Open-Emission-Factors-DB/blob/main/OEFDB_sources.md))

2022-07-08 12:35 UTC, GeeWee commented
I would suggest as a best-practice you don't let anything into the `main` branch that doesn't pass CI.
Let's keep the documents separate for now, and just try to remember to update both when needed.

2022-07-11 16:49 UTC, patstirling approved these changes

2022-07-11 16:50 UTC, merged