GLEC ingress - Refrigerant gases and Fuel
climatiq/Open-Emission-Factors-DB pull request #279
Opened 2022-07-11 17:26 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] New

**What category or categories does it affect?**

_Refrigerants and Fugitive Gases and Fuel_

**What?**

_ADD GLEC 2019 dataset_

**Why?**

_A key data set for the transport emissions calculations. _

2022-07-12 11:02 UTC, AnastasiaLobanova requested changes
Ah few more things from the checker: There is a problem with the scope field - I think it is an autofill error - "1|2|14", uncertainty field should be empty, in case it is not supplied.

There are also several new values of lca_activity, also those I haven't tackled last time bc of our discussion on using the actual lca phases, rather than their unique combinations. Let's discuss it today again!

2022-07-12 11:43 UTC, patstirling commented
> 

Note that you will need to delete the quotation marks as well if you are editing directly

2022-07-12 11:46 UTC, AnastasiaLobanova commented
> > 
> 
> Note that you will need to delete the quotation marks as well if you are editing directly

They should go away automatically once we commit the change

2022-07-13 15:08 UTC, AnastasiaLobanova submitted a review, later dismissed
looks good to me!

2022-07-14 07:22 UTC, AnastasiaLobanova approved these changes

2022-07-14 13:17 UTC, patstirling requested changes
Great start! Few thoughts/things to tidy up

2022-07-14 13:17 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +658be0c6-dacb-4e73-b942-82524267ce36,Refrigerants and Fugitive Gases,Refrigerants and Fugitive Gases,fugitive_gas-type_r_404a,R-404A - Mixture: 44.0% R-125 - 4.0% R-134a - 52.0% R-143a,kg,not-supplie
For this and other gases with "Mixture:" - do we need to be this explicit? E.g. is R-404A always this mix, or is this particular EF specific to this blend of R-404A? In the former case I'd argue we remove this entirely and the user can check the source if they way. For the latter, I'd argue we put this in the description - it seems too much detail for the name, unless it is a really important detail that helps the user distinguish this particular EF.

2022-07-14 13:36 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +482708c8-f454-466c-85fa-f21bdc28fce6,Energy,Fuel,fuel_type_aviation_fuel-fuel_use_na,Aviation fuel - TTW,kg,not-supplied,3.18,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_t
so both the fuel use and fuel type should be aviation?

2022-07-14 13:37 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +eb24f71f-467f-452a-bed9-5542bfc5d48a,Energy,Fuel,fuel_type_100_percent_biodiesel-fuel_use_na,100% biodiesel (B100) - TTW,kg,not-supplied,0,not-supplied,not-supplied,not-supplied,not-supplied,not-supp
there is no scope mentioned in GLEC. I had not-supplied in the field first but due to the schema error changed it to blank

2022-07-14 13:47 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +482708c8-f454-466c-85fa-f21bdc28fce6,Energy,Fuel,fuel_type_aviation_fuel-fuel_use_na,Aviation fuel - TTW,kg,not-supplied,3.18,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_t
so both the fuel type and fuel use should be aviation?

2022-07-18 10:55 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +482708c8-f454-466c-85fa-f21bdc28fce6,Energy,Fuel,fuel_type_aviation_fuel-fuel_use_na,Aviation fuel - TTW,kg,not-supplied,3.18,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_t
yes, this makes "fuel_use" as a sub-field queryable; the key for machine readability is to remain predictable in the location of data (even if to a human it feels redundant to have the information twice)

2022-07-18 10:55 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +eb24f71f-467f-452a-bed9-5542bfc5d48a,Energy,Fuel,fuel_type_100_percent_biodiesel-fuel_use_na,100% biodiesel (B100) - TTW,kg,not-supplied,0,not-supplied,not-supplied,not-supplied,not-supplied,not-supp
so is this a bug in the schema?

2022-07-19 11:22 UTC, patstirling approved these changes

2022-07-19 12:02 UTC, merged