Update ID structure for sea travel
climatiq/Open-Emission-Factors-DB pull request #28
Opened 2021-10-19 14:48 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Sea travel

What?

For all EFs incurrently in the sea travel category:

IDs updated to adhere to the following machine-readable structure:
passenger_ferry-route_type_[e.g. "foot" or "car"]-route_location_[e.g. "St Malo_to_Portsmouth"] fuel_source_[e.g. "diesel" or "unknown"]-activity_[e.g. "fuel_combustion", "upstream" or "fuel_combustion_and_upstream" or "unknown"]

Name field to be concise, easily read plain English which is as consistent as possible across EFs regardless of source
Description field to provide further detail regarding the specifics of the EF, including life-cycle activity details and specifics of applicability
Updates description field

Why?

This is part of a larger refactoring of IDs across the OEFDB to ensure EFs adhere to a clear standard structure per category and across sources, allowing them to be better understood and compared both by humans and machines.

2021-10-20 17:45 UTC, patstirling requested changes
- We can remove "route_location_" from these IDs as per other travel categories - the region field does this job.
- the name field should not refer to activity - this belongs in the ID and description fields
- that description field should specify whether upstream emissions are included (they are not for BEIS)

2021-10-20 17:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_all_routes_average-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Average passenger ferry route including fuel combustion,kg-CO2e/
Use "route_type_unknown" for "all" or "average" EFs

2021-10-29 09:04 UTC, AnastasiaLobanova submitted a review, later dismissed
Looks good!! just three small typos! :)

2021-10-31 21:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_car-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Ferry route including including cars and passengers including fuel combustion,k
Please do not include activity in the name.

2021-10-31 21:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_car-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Ferry route including including cars and passengers including fuel combustion,k
Do we need " in the description?

2021-10-31 21:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_unknown-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Average passenger ferry route including fuel combustion,kg-CO2e/pkm,0.11286
Do you know what average refers to here?

2021-10-31 21:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_car-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Ferry route including including cars and passengers including fuel combustion,k
Is "car" a route type?

2021-10-31 21:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_foot-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Ferry route with foot passengers only including fuel combustion,kg-CO2e/pkm,0.
Please do not include activity in the name.

2021-11-01 09:07 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_foot-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Ferry route with foot passengers only including fuel combustion,kg-CO2e/pkm,0.
Ok!

2021-11-01 09:12 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Travel,passenger_ferry-route_type_unknown-route_location_unknown-fuel_source_unknown-activity_fuel_combustion,Average passenger ferry route including fuel combustion,kg-CO2e/pkm,0.11286
Yes, average (all passenger).

2021-11-01 12:21 UTC, patstirling commented
> * We can remove "route_location_" from these IDs as per other travel categories - the region field does this job.
> * There appear to have been quotation marks added to each of the descriptions - could these be removed
> * "Emission Intensity" -> "Emission intensity" in all description fields

2021-11-01 12:21 UTC, patstirling requested changes
See earlier comments

2021-11-01 12:23 UTC, patstirling commented
Also I see 449-450 and 455 have been altered; please revert

2021-11-02 10:36 UTC, closed without merging