GLEC ingress - Transport
climatiq/Open-Emission-Factors-DB pull request #285
Opened 2022-07-19 12:23 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] New

**What category or categories does it affect?**

_Frieght categories_

**What?**

_Add all GLEC transport data to OEFDB._

**Why?**

_GLEC provides default freight emissions factors that can be used for transport calculations. _

2022-07-20 22:00 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +43bd1354-dfbb-4107-9c29-b641fc07a0ee,Transport,Sea Freight,sea_freight-vessel_type_coupled_convoys-route_type_inland-vessel_length_gt_163m_lt_185m-tonnage_na-fuel_source_diesel,Coupled convoys (163–1
More em-dashes in these 3 EFs (between 163 and 185)

```suggestion
43bd1354-dfbb-4107-9c29-b641fc07a0ee,Transport,Sea Freight,sea_freight-vessel_type_coupled_convoys-route_type_inland-vessel_length_gt_163m_lt_185m-tonnage_na-fuel_source_diesel,Coupled convoys (163-185m) - inland waterways - TTW,tonne-km,not-supplied,0.014,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +837f3ce4-5dc2-43fd-9614-3974673f189d,Transport,Sea Freight,sea_freight-vessel_type_container-route_type_inland-vessel_length_110m-tonnage_na-fuel_source_diesel,Container vessels 110 m - TTW,tonne-km,
For consistency with other EFs, vessel length to be bracketed

```suggestion
837f3ce4-5dc2-43fd-9614-3974673f189d,Transport,Sea Freight,sea_freight-vessel_type_container-route_type_inland-vessel_length_110m-tonnage_na-fuel_source_diesel,Container vessels (110 m) - inland waterways - TTW,tonne-km,not-supplied,0.021,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:08 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +6a57a772-7409-45e5-a480-f4e0519c83cb,Transport,Sea Freight,sea_freight-vessel_type_dry-route_type_industry_average-vessel_length_na-tonnage_na-fuel_source_na,Industry Average - Dry - Aggregate averag
Apply to all "Industry Average - Dry..."

```suggestion
6a57a772-7409-45e5-a480-f4e0519c83cb,Transport,Sea Freight,sea_freight-vessel_type_container,Container ship - dry,TEU-km,not-supplied,0.0664,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of frieght - aggregate average trade lane. EF is used in cases where the origin destination pair is unknown. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +38ea1d4a-b53f-4795-b467-e1349116ed5f,Transport,Sea Freight,sea_freight-vessel_type_reefer-route_type_industry_average-vessel_length_na-tonnage_na-fuel_source_na,Industry Average - Reefer - Aggregate
Apply to all refrigerated "Industry average"

```suggestion
38ea1d4a-b53f-4795-b467-e1349116ed5f,Transport,Sea Freight,sea_freight-vessel_type_reefer_refrigerated,Container ship - reefer (refrigerated),TEU-km,not-supplied,0.1265,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of frieght - aggregate average trade lane. EF is used in cases where the origin destination pair is unknown. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +bfef9153-6ca2-454f-8035-8245151beead,Transport,Sea Freight,sea_freight-vessel_type_motor-route_type_inland-vessel_length_135m-tonnage_gt_2000t_lt_3000t-fuel_source_diesel,Motor vessels 135 m (2000–30
rogue em-dashes here and in the next 5 EFs where a range is expressed in the `name` field

```suggestion
bfef9153-6ca2-454f-8035-8245151beead,Transport,Sea Freight,sea_freight-vessel_type_motor-route_type_inland-vessel_length_135m-tonnage_gt_2000t_lt_3000t-fuel_source_diesel,Motor vessels 135 m (2000-3000 t) - TTW,tonne-km,not-supplied,0.016,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +76c67e9b-e3d9-4b0c-9131-7fcfa616b39d,Transport,Sea Freight,sea_freight-vessel_type_oil_tanker-route_type_na-vessel_length_na-tonnage_lt_5dwkt-fuel_source_hfo-load_type-heavy,Oil tanker <5 dwkt - Heav
Qualify with "heavy load" here and other Oil tanker EFs

```suggestion
76c67e9b-e3d9-4b0c-9131-7fcfa616b39d,Transport,Sea Freight,sea_freight-vessel_type_oil_tanker-route_type_na-vessel_length_na-tonnage_lt_5dwkt-fuel_source_hfo-load_type-heavy,Oil tanker <5 dwkt - heavy load - HFO - TTW,tonne-km,not-supplied,0.056,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:17 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +aaab058c-0765-42f8-8862-b03587e06b00,Transport,Sea Freight,sea_freight-vessel_type_oil_tanker-route_type_na-vessel_length_na-tonnage_gt_5dwkt_lt_60dwkt-fuel_source_hfo-load_type-heavy,Oil tanker 5–60
From here to 11222 there are em-dashes in the name where a range of dwkt is expressed

```suggestion
aaab058c-0765-42f8-8862-b03587e06b00,Transport,Sea Freight,sea_freight-vessel_type_oil_tanker-route_type_na-vessel_length_na-tonnage_gt_5dwkt_lt_60dwkt-fuel_source_hfo-load_type-heavy,Oil tanker 5-60 dwkt - Heavy - HFO - TTW,tonne-km,not-supplied,0.019,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:18 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +de993a72-d047-4951-b2d6-82c046959955,Transport,Sea Freight,sea_freight-vessel_type_pushed_convoy-route_type_inland-vessel_length_2_barges-tonnage_na-fuel_source_diesel,Pushed convoy – push boat + 2 b
em dashes between "Pushed convoy" and "push boat" in all of these EFs. Added suggestion for qualifying inland water

```suggestion
de993a72-d047-4951-b2d6-82c046959955,Transport,Sea Freight,sea_freight-vessel_type_pushed_convoy-route_type_inland-vessel_length_2_barges-tonnage_na-fuel_source_diesel,Pushed convoy - push boat + 2 barges - inland waterways - TTW,tonne-km,not-supplied,0.014,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:20 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +816cbf66-8806-469e-a2f0-93e771e078ff,Transport,Sea Freight,sea_freight-vessel_type_ro_pax-route_type_na-vessel_length_na-tonnage_na-fuel_source_hfo-load_type-average,Ro-Pax - Average - HFO - TTW,tonn
Add "ferry" to all ferry EFs; no need to express average in name or ID.

```suggestion
816cbf66-8806-469e-a2f0-93e771e078ff,Transport,Sea Freight,sea_freight-vessel_type_ro_pax-route_type_na-vessel_length_na-tonnage_na-fuel_source_hfo,Ro-Pax ferry - HFO - TTW,tonne-km,not-supplied,0.19,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:21 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +db6975ec-08df-470f-85d9-3f7451b59552,Transport,Sea Freight,sea_freight-vessel_type_ro_ro-route_type_na-vessel_length_na-tonnage_average-fuel_source_hfo-load_type-trailer_only,Ro-Ro fleet average - Tr
No need to express averages in name here and following EFs

```suggestion
db6975ec-08df-470f-85d9-3f7451b59552,Transport,Sea Freight,sea_freight-vessel_type_ro_ro-route_type_na-vessel_length_na-tonnage_average-fuel_source_hfo-load_type-trailer_only,Ro-Ro ferry - trailer only - HFO - TTW,tonne-km,not-supplied,0.063,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,tank_to_wheel,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Tank-to-Wheel (TTW) emission intensity of frieght. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +8e8d41b1-2d5d-4afd-889c-12b470a0a33a,Transport,Transport Services and Warehousing,transport_services-type_maritime_container_terminal_mixed,Maritime container terminal - Mixed,container-moved,not-sup
See suggestion for clarifying what this EF is

```suggestion
8e8d41b1-2d5d-4afd-889c-12b470a0a33a,Transport,Transport Services and Warehousing,transport_services-type_maritime_container_terminal,Freight logistics - maritime container terminal per container,container-moved,not-supplied,30.1,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of transport services. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:26 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +e6d98cbc-450a-4545-9cc3-5349ef14ca8e,Transport,Transport Services and Warehousing,transport_services-type_storage_and_transhipment_ambient,Storage + transhipment - Ambient,tonne,not-supplied,1.7,not-
Suggestion for clarifying EF purpose

```suggestion
e6d98cbc-450a-4545-9cc3-5349ef14ca8e,Transport,Transport Services and Warehousing,transport_services-type_storage_and_transhipment_ambient,Freight logistics - storage + transhipment - ambient,tonne,not-supplied,1.7,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of transport services. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:28 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +caa47e37-94c9-4147-8088-79b7038306fc,Transport,Transport Services and Warehousing,transport_services-type_transhipment_site_ambient,Transhipment site - Ambient,tonne,not-supplied,3.4,not-supplied,not
```suggestion
caa47e37-94c9-4147-8088-79b7038306fc,Transport,Transport Services and Warehousing,transport_services-type_transhipment_site_ambient,Freight logistics - transhipment site - ambient,tonne,not-supplied,3.4,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of transport services. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +7df8eb40-12ef-436d-a488-6ecbad9206ec,Transport,Transport Services and Warehousing,transport_services-type_warehouse_ambient,Warehouse - Ambient,tonne,not-supplied,1.9,not-supplied,not-supplied,not-su
```suggestion
7df8eb40-12ef-436d-a488-6ecbad9206ec,Transport,Transport Services and Warehousing,transport_services-type_warehouse_ambient,Freight logistics -  warehouse - ambient,tonne,not-supplied,1.9,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,,unknown,GLEC,2019,2019 - 2022,,GLOBAL,m,Climatiq,2022/06/20,Emission intensity of transport services. Retrieved from the Global Logistics Emissions Council Framework for Logistics Emissions Accounting and Reporting. (2019). NOTE: The source does not clarify if the kgCO2e value is calculated using either IPCC Fourth Assessment Report (AR4) or IPCC Fifth Assessment Report (AR5) methodologies.,https://www.smartfreightcentre.org/en/how-to-implement-items/what-is-glec-framework/58/
```

2022-07-20 22:30 UTC, patstirling commented on metadata/schema.toml
> +    "TEU-km",
This is a whole new unit type I believe @grindcode - "number over distance"; we could re-think "passenger over distance" to be "number over distance"?

2022-07-21 12:27 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +8e8d41b1-2d5d-4afd-889c-12b470a0a33a,Transport,Transport Services and Warehousing,transport_services-type_maritime_container_terminal_mixed,Maritime container terminal - Mixed,container-moved,not-sup
There are three temp sub-categories for these EFs in GLEC: Ambient, Chilled, and Mixed. I wouldn't remove "mixed" here, to be consistent with the other two sub-categories.

2022-07-25 17:40 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +6a8823f1-20c3-48f5-bba2-064303ca8221,Transport,Air Freight,freight_flight-route_type_na-distance_long_haul_gt_3700km-weight_na-rf_na-method_en16258-aircraft_type_belly_freight,Long haul (> 3700 km) -
@patstirling From IATA methodology: 

"Each airline participating in the IATA carbon offset program uses its own dataset of real fuel consumption data from passenger aircraft journeys to maximise the accuracy of the emissions calculations. Because of this, much of the information normally required to accurately estimate emissions (e.g., when using modelled data averages and emission factors) are not required and do not apply to the IATA carbon calculator methodology. These include distance travelled and uplift factors for non-direct routing and delays."

"The CO2 emissions are calculated from the fuel consumption linked to the vehicle operational processes (for aircrafts, it includes processes such as airborne, taxiing, turnaround, auxiliary power usage – as defined in the IATA’s Fuel Measurement Protocol)."

Also, pages 7 & 8 of the following document have some info about fuel uplift, which is not clear if it is included in EFs estimates or not: https://www.iata.org/contentassets/34f5341668f14157ac55896f364e3451/rp-carbon-calculation.pdf

2022-07-27 13:56 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +6a8823f1-20c3-48f5-bba2-064303ca8221,Transport,Air Freight,freight_flight-route_type_na-distance_long_haul_gt_3700km-weight_na-rf_na-method_en16258-aircraft_type_belly_freight,Long haul (> 3700 km) -
Just a note: % are not allowed in ids

2022-07-27 14:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +6a8823f1-20c3-48f5-bba2-064303ca8221,Transport,Air Freight,freight_flight-route_type_na-distance_long_haul_gt_3700km-weight_na-rf_na-method_en16258-aircraft_type_belly_freight,Long haul (> 3700 km) -
So how do we make it clear to users for this EF (and all others) what it is that this includes? I take from your notes that distance uplift is not required for IATA EFs, but it is required for EN16528 - so in theory EN16528 EFs should have no distance uplift aspect to the activity_id while IATA EFs should have "-distance_uplift_included" added to each EF?

2022-07-27 15:07 UTC, AnastasiaLobanova requested changes
Great work Maryam! A lot of new and very interesting data points 

Some comments from me: 
- there are a bunch of errors in ids with a hyphen instead of underscore after load_type - I think quick replacement will fix it. 
- "Artic truck" stands for an articulated truck? Should we use rather a full name here? Artic truck sounds like "arctic"
- There are a lot of abbreviations in names (like EC, WC, GVW, LTL..), which are not "decoded" in the descriptions - do we have a list of abbreviations somewhere? 
- One of those is GVW which is gross vehicle weight, right? Do we want this "gvw" to be a part of id? IDs for transport are already bulky and also "vehicle_weight_60tgvw" looks a bit strange as if it is a part of the unit, maybe to add an underscore between t and gvw, e.g. "vehicle_weight_60t_gvw" if we still want it there
- There are some "Medi- terranean" in the names - suggest being replaced by "Mediterranean"
- There are some "ave load" (11286-11297) in the names, suggest we use "average" instead of "ave"

2022-07-27 15:52 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +8e8d41b1-2d5d-4afd-889c-12b470a0a33a,Transport,Transport Services and Warehousing,transport_services-type_maritime_container_terminal_mixed,Maritime container terminal - Mixed,container-moved,not-sup
Where "mixed" is provided this is typically the same as "average" (as it represents  - so while we can keep this in the name, we needn't have it in the ID - in fact it's better not to, so that someone doesn't have to specify "mixed" but can simply not select anything and it will go to the right (generic) EF

2022-07-27 15:57 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +7c24c4dd-dd7b-40d7-9e40-90bdb18fb297,Transport,Rail Freight,freight_train-route_type_na-fuel_type_electricity-load_type-building_materials,Rail traction - Building Materials,tonne-km,not-supplied,0.0
For this and the following EFs "transport" rather than "load" makes more sense

2022-07-27 16:01 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +e330af54-115c-4e08-ae83-f7a34bfa8717,Transport,Rail Freight,freight_train-route_type_na-fuel_type_electricity-load_type-average_mixed,Rail traction - Average/mixed,tonne-km,not-supplied,0.01,not-supp
For "average" or "mixed" EGs we should removed the subID in the activityID - in this case delete "-load_type-average_mixed" - this way if the user cannot specify a particular load type, it will default to this EF (equivalent to using "na" in the old activity_id schema)

2022-07-27 16:03 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +6a8823f1-20c3-48f5-bba2-064303ca8221,Transport,Air Freight,freight_flight-route_type_na-distance_long_haul_gt_3700km-weight_na-rf_na-method_en16258-aircraft_type_belly_freight,Long haul (> 3700 km) -
There are still a few "frieght"s out there (I found 6)

2022-07-28 11:21 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +c291e17e-ff8a-482a-857e-28dcca1963af,Transport,Road Freight,freight_vehicle-vehicle_type_artic_truck_hpdi-fuel_source_bio_lng_or_diesel-vehicle_weight_lt_40tgvw-load_type-average_mixed,Artic Truck up
I argue that "HPDI" and "SI" are part of the vehicle (powertrain) characteristics, so they should not be combined with the fuel type. GLEC also categorizes "HPDI" and "SI" within the vehicle characteristic, not fuel type (page 106 of GLEC doc)

2022-07-28 12:00 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +70fac576-1543-4b55-8fd4-01f173c6c5fb,Transport,Road Freight,freight_vehicle-vehicle_type_van-fuel_source_cng-vehicle_weight_lte_3.5t,Van =< 3.5 t - CNG - TTW,tonne-km,not-supplied,0.54,not-supplied,n
Regarding consistency, we do have lte across the DB. So, I think we should stick to the source and keep the equal...

2022-07-28 12:29 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +4280c651-5b54-44d2-8858-287f6a3b3863,Transport,Sea Freight,sea_freight-vessel_type_bulk_carrier-route_type_na-vessel_length_na-tonnage_lt_10dwkt-fuel_source_mgo-load_type-average,Bulk carrier <10 dwk
@patstirling isn't MGO "Marine Gas Oil"?

2022-07-28 14:54 UTC, AnastasiaLobanova submitted a review, later dismissed
Looks great to me Maryam!

2022-07-29 10:05 UTC, patstirling requested changes
Can't load diff now so will just use UUID numbers:

- 13a304e9-5d38-4fe8-b606-291d0f5683fc - can remove "transport" from name here
- 4d4f375e-b49b-4d01-9985-9f275bc92420 - rename ID to "transport_services-type_transhipment_maritime_container_terminal" and name to "Freight logistics - container transhipment at maritime container terminal - mixed (this is adding a bit to the source, but it makes it clear to the user/client software that this is transhipment, just of a different unit type)
- where we have used "rigid_truck" replace with "hgv_rigid" to conform with existing EFs
- where we have used "articulated_truck" replace with "hgv_articulated" to conform with existing EFs
- where we have used "vessel_type_reefer_refrigerated" replace with "vessel_type_container_reefer_refrigerated" to conform with existing EFs
- c1e16d96-e6e5-4f45-b49d-a31f02195b72 - these and following 5 EFs can have "load_type_average_freight_only" removed from the ID as they are "average" load type

2022-07-29 11:16 UTC, patstirling approved these changes
Approved!

2022-07-29 11:16 UTC, merged