adding BEIS 2022 Transport
climatiq/Open-Emission-Factors-DB pull request #290
Opened 2022-08-01 17:07 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Transport sector

**What?**

adding BEIS 2022 Transport

**Why?**

annual update of key sources

2022-08-02 08:25 UTC, maryarbab submitted a review, later dismissed

2022-08-02 16:55 UTC, maryarbab approved these changes

2022-08-03 10:05 UTC, patstirling requested changes
Following IDs have "tonnes" where the matching EF from 2021 (and most other 2022 EFs) use "t" in the name:

- fe477d99-9256-4b68-8214-9596c0e7bd05
- 2c2d70b7-b9c5-4d4b-b8d0-4481f477a11b
- 622799d2-621d-4e68-9540-6d4ba45975a7

"Road freight diesel refrigerated HGV 100% laden - WTT" appears in 2021 but not in 2022 - the use phase EF appears in both 2021 and 2022.

In a number of names "Evs" is used instead of "EVs" - find/replace?

still seeing extra "air freight" in the name field of the following 2021 EFs:
- 46e6a589-c161-4571-b299-fc26241b164b
- 8cf618a0-a909-4f63-ae9e-ab5264045628
- a222243b-3d2f-46c9-9d76-171734e32b96
- 1ff05104-695c-45c3-907d-6abc0e704117
- 3da01999-2bc1-4c14-9ceb-e8579cc17d02
- 7f4163d1-1f65-4266-876b-cdcdf3d58e1a
- d5a9d9f0-4294-45e2-b9a7-1b82cb6361eb
- c5f22e30-b8df-49f6-aa1d-2b4cd44b130a

There is an extra 0 in "350000" in the name field - should be "35000-59999" 60ada4f7-b1c4-4180-ad34-9a86ce250f94

2022-08-03 12:13 UTC, patstirling approved these changes

2022-08-03 12:20 UTC, merged