Update ID structure for sea transport
climatiq/Open-Emission-Factors-DB pull request #30
Opened 2021-10-21 12:53 UTC by greenercode

Review all sea transport emission factors

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Sea transport 

**What?**

For all EFs incurrently in the sea transport category:

IDs updated to adhere to the following machine-readable structure:
sea_transport-ship_type [e.g. "bulk_carrier"]- route_type_[e.g.intra_mediterranean]-ship_load_[e.g. "above-8000-teu"]-ship_length_[e.g. 163m]-fuel_source_[e.g. "unknown" or "diesel"]-activity_[e.g. "fuel_combustion", "upstream" or "fuel_combustion_and_upstream" or "unknown"]

Name field to be concise, easily read plain English which is as consistent as possible across EFs regardless of source
Description field to provide further detail regarding the specifics of the EF, including life-cycle activity details and specifics of applicability
Updates description field

**Why?**

This is part of a larger refactoring of IDs across the OEFDB to ensure EFs adhere to a clear standard structure per category and across sources, allowing them to be better understood and compared both by humans and machines.

2021-10-31 20:44 UTC, maryarbab submitted a review, later dismissed

2021-10-31 20:44 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_cargo-route_type_unknown-vessel_length_unknown-tonnage_below_or_equal_to_10000t-fuel_source_heavy_fuel_oil_or_marine_gas_oil-activity_upstream_and_fuel
Does the source define what type of upstream emission it is? Sometimes ADEME defines that.

2021-10-31 20:59 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_bulk_carrier-route_type_unknown-vessel_length_unknown-tonnage_above_200000dwt-fuel_source_unknown-activity_fuel_combustion,Bulk carrier > 200000 dwt,kg
Can you please remove " in the description?

2021-10-31 20:59 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_bulk_carrier-route_type_unknown-vessel_length_unknown-tonnage_average-fuel_source_unknown-activity_fuel_combustion,Bulk carrier (average),kg-CO2e/tkm,0
What does "average" refer to here?

2021-11-01 10:00 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_cargo-route_type_unknown-vessel_length_unknown-tonnage_below_or_equal_to_10000t-fuel_source_heavy_fuel_oil_or_marine_gas_oil-activity_upstream_and_fuel
Unfortunately not. There is only upstream (fuel) and combustion (fuel).

2021-11-01 15:11 UTC, patstirling requested changes
Still quite a lot of "s

2021-11-01 17:02 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_transhipment-route_type_unknown-vessel_length_unknown-tonnage_ambient-vessel_length_unknown-fuel_source_unknown-activity_fuel_combustion,Transshipment
duplicate "vessel_length_unknown" in the ID

2021-11-01 17:22 UTC, patstirling approved these changes
SHIP IT!

2021-11-02 08:27 UTC, AnastasiaLobanova approved these changes

2021-11-02 11:11 UTC, patstirling submitted a review, later dismissed

2021-11-02 14:29 UTC, patstirling requested changes

2021-11-02 14:29 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_panamax-route_type_unknown-vessel_length_unknown-tonnage_50000t-fuel_source_bunker_c_oil-activity_fuel_combustion,Cargo freighter (Panamax),kg-CO2e/tkm
@greenercode the details in the description here do't appear to match the ID and name (eg. the dwt provided in the ID is outside the range of dwt provided in the description) - could you please check this and the other UBA lines?

2021-11-02 14:52 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_panamax-route_type_unknown-vessel_length_unknown-tonnage_50000t-fuel_source_bunker_c_oil-activity_fuel_combustion,Cargo freighter (Panamax),kg-CO2e/tkm
Addressed, are we good to ship now? :)

2021-11-02 15:47 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-11-02 16:20 UTC, patstirling approved these changes

2021-11-02 17:08 UTC, patstirling submitted a review, later dismissed

2021-11-02 17:38 UTC, AnastasiaLobanova approved these changes

2021-11-02 17:39 UTC, merged