Update structure for Road Travel
climatiq/Open-Emission-Factors-DB pull request #33
Opened 2021-10-28 00:05 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [x] Update

**What category or categories does it affect?**

Road Travel

**What?**

Updates all current Roal Travel IDs to adhere to the following structure:

passenger_vehicle-vehicle_type_[e.g. "car" or "bus"]-fuel_source_[e.g. "diesel" or "cng"]-activity_[e.g. "fuel_combustion", "fuel_upstream_and_fuel_combustion"]-distance_[e.g. "short_distance"]-engine_size_[e.g. ""]

In addition to IDs, names, values, and descriptions are also updated.

**Why?**

This is part of a larger refactoring of IDs across the OEFDB to adhere to a specified structure per category, allowing them to be better understood both by humans and machines.

2021-11-01 17:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_passenger-car-fuel_source_unknown-distance_type_unknown-engine_size_unknown-activity_unknown,Motorcycle,kg-CO2e/mile,0.189,,EPA,2020,US,2021/08/
And passenger should be omitted as per all other instances of "car"

2021-11-01 17:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_petrol_hybrid_plug_in-distance_type_unknown-engine_size_medium-activity_unknown,Petrol PHEV passenger car medium,kg-CO2e/pkm,0.1
@greenercode could you please take on finalising this PR in @maryarbab 's absence, as you have some experience here? Please leave as "unknown" if it really can't be told what the activity is at this point and add it to the data health backlog for us to come back to.

2021-11-01 17:15 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_bio_bioethanol-distance_type_unknown-engine_size_medium-activity_unknown,Bioethanol passenger car medium from wheat end energy,k
@greenercode as @maryarbab is away, could you pick this PR up and make the proposed changes to the activity

2021-11-01 17:20 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_passenger-car-fuel_source_unknown-distance_type_unknown-engine_size_unknown-activity_unknown,Motorcycle,kg-CO2e/mile,0.189,,EPA,2020,US,2021/08/
Same is applicable to sea travel, now that I think about it @patstirling

2021-11-02 08:38 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_petrol_hybrid_plug_in-distance_type_unknown-engine_size_medium-activity_unknown,Petrol PHEV passenger car medium,kg-CO2e/pkm,0.1
For now, this will remain as **unknown**. More information is required from the UBA. The above explanation is as specific as we can get. @patstirling

2021-11-02 08:40 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_bio_bioethanol-distance_type_unknown-engine_size_medium-activity_unknown,Bioethanol passenger car medium from wheat end energy,k
For the UBA emission factors relating to energy and more specifically **end energy** , the **activity_unknown** was changed to '**final_energy'**. The main assumption being that; "final energy consumption refers the total energy consumed by end users, such as households, industry and agriculture."  (https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Final_energy_consumption)

2021-11-02 08:58 UTC, greenercode approved these changes

2021-11-02 10:44 UTC, AnastasiaLobanova reviewed
Just small comments - 

- we have to be consistent innthe ids with the casing, e.g. LPG should be lpg

- 1000kg should turn into tonnes, e.g. 12000kg becomes 12t, there should be no underscore between 12 and t, i.e. 12t and not 12_t, the same for engine size 3000cc not 3000_cc
- what means engine size - 12000 kg?

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_LPG-distance_type_long-engine_size_unknown-activity_fuel_upstream_and_fuel_combustion,LPG passenger car long distance,kg-CO2e/pk
LPG -> lpg, we should be consistent with the casing in the IDs

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_bus-fuel_source_diesel-distance_type_unknown-engine_size_above_12000_kg-activity_fuel_combustion,Diesel bus above 12000 kg,kg-CO2e/km,1.0882416,
Should 000kg become t as in other categories? 
Why engine size refers to kgs?

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_coach-fuel_source_average-distance_type_unknown-engine_size_unknown-activity_fuel_combustion,Coach,kg-CO2e/pkm,0.02684,,BEIS,2021,GB,2021/07/23,
fuel source average -> fuel source unknown

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_city_bus-fuel_source_natural_gas-distance_type_unknown-engine_size_unknown-activity_fuel_upstream_and_fuel_combustion,NGV city bus Bus,kg-CO2e/p
fuel source natural gas -> fuel_source_cng to be consistent with the other categories

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_bus-fuel_source_battery_electric-distance_type_unknown-engine_size_above_12000_kg-activity_fuel_combustion,Electric bus above 12000 kg,kg-CO2e/k
12000 kg to t

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_bus_line-fuel_source_CNG-distance_type_unknown-engine_size_unknown-activity_unknown,CNG bus line,kg-CO2e/pkm,0.0617,,UBA,2020,DE,2021/09/15,Emis
CNG - cng

2021-11-02 10:44 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_car-fuel_source_bio_CNG-distance_type_unknown-engine_size_large-activity_unknown,Bio CNG passenger car large,kg-CO2e/pkm,0.00392,,UBA,2020,DE,20
CNG -> cng, here and below

2021-11-02 15:01 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-11-02 15:38 UTC, patstirling requested changes
Can we change "passenger_transport" to "passenger_vehicle" across all IDs - then one small ID error and we are done!

2021-11-02 15:38 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_transport-vehicle_type_bus_below_12t-fuel_source_diesel_hybrid-distance_unknown-engine_size_unknown_fuel_combustion,Diesel hybrid bus below 12 t,kg-CO2e/km,0.5556369,,
missing "-activity_" SubID prefix

2021-11-02 16:11 UTC, greenercode approved these changes

2021-11-02 16:17 UTC, patstirling submitted a review, later dismissed

2021-11-02 16:59 UTC, greenercode approved these changes

2021-11-02 17:12 UTC, merged