add BEIS spend-based data 2019
climatiq/Open-Emission-Factors-DB pull request #348
Opened 2022-11-23 11:14 UTC by gpantelidou

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [X] Update

**What category or categories does it affect?**

multiple

**What?**

add new spend-based data from BEIS 2019 dataset 1990-2019

**Why?**

new dataset was released for 2022

2022-11-24 15:51 UTC, AnastasiaLobanova requested changes
Looks great @gpantelidou! Just small remarks. You are sure it is AR4 values right? 

I believe also in the description instead of "the official report on GHG Emissions of the UK between 1990-2019."  should be "the official report on UK and England's carbon footprint to 2019."

2022-11-24 15:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
Dataset name here I think should be "UK and England's carbon footprint to 2019"

2022-11-24 15:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +e1976aac-f8cc-4d90-9885-630c0531dc42,Agriculture/Hunting/Forestry/Fishing,Timber and Forestry Products,timber_forestry-type_wood_and_of_products_of_wood_and_cork_except_furniture_articles_of_straw_an
please check here the name/id - "and of product of wood" seems to be missing some words

2022-11-24 15:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +dc7e74b9-e07e-42ed-b0e6-f2d92c2ba04f,Organizational Activities,Professional Services and Activities,professional_services-type_accounting_bookkeeping_and_auditing_services_tax_consulting_services,Acc
bookkeeping lacks a space I believe

2022-11-24 15:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +dc7e74b9-e07e-42ed-b0e6-f2d92c2ba04f,Organizational Activities,Professional Services and Activities,professional_services-type_accounting_bookkeeping_and_auditing_services_tax_consulting_services,Acc
check also in the description please

2022-11-24 18:50 UTC, maryarbab commented
@gpantelidou I am confused: Is this 2019 or 2022 data?

2022-11-24 19:07 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +e1976aac-f8cc-4d90-9885-630c0531dc42,Agriculture/Hunting/Forestry/Fishing,Timber and Forestry Products,timber_forestry-type_wood_and_of_products_of_wood_and_cork_except_furniture_articles_of_straw_an
agree, that it needs rewording.

2022-11-24 19:18 UTC, maryarbab requested changes
Looks very good! Some small comments.

2022-11-24 19:18 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +f8522d02-a71c-43bf-94c6-d96a6c94f077,Buildings and Infrastructure,Housing,housing-type_owner_occupiers_housing_services,Owner-Occupiers' Housing Services,GBP,not-supplied,0.027000000000000003,0.02200
Better to avoid capital letters in the name (except for the beginning of the sentence) to be consistent with other names

2022-11-24 19:18 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +18c2b030-00f0-4eb7-bd7f-0a26a06caee5,Consumer Goods and Services,Recreation and Culture,consumer_goods-type_creative_arts_and_entertainment_services,Creative/arts and entertainment services,GBP,not-s
"Creative arts" instead of "Creative/arts"?

2022-11-24 19:18 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +23b687bf-2b6c-4d20-a009-1eefb9384193,Equipment,Machinery,machinery-type_machinery_and_equipment_not_specif,Machinery and equipment not specif,GBP,not-supplied,0.44799999999999995,0.361,not-supplied,n
"specif" needs to be "specific" in the name.

2022-11-25 10:56 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +e1976aac-f8cc-4d90-9885-630c0531dc42,Agriculture/Hunting/Forestry/Fishing,Timber and Forestry Products,timber_forestry-type_wood_and_of_products_of_wood_and_cork_except_furniture_articles_of_straw_an
I doublechecked to be sure and this is the exact name in the original source table: "Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials".  I can change it to "Wood and products of wood and cork, except furniture; articles of straw and plaiting materials"

2022-11-25 11:02 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +dc7e74b9-e07e-42ed-b0e6-f2d92c2ba04f,Organizational Activities,Professional Services and Activities,professional_services-type_accounting_bookkeeping_and_auditing_services_tax_consulting_services,Acc
actually it's one word I googled it to be sure and checked the source table

2022-11-25 11:05 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +f8522d02-a71c-43bf-94c6-d96a6c94f077,Buildings and Infrastructure,Housing,housing-type_owner_occupiers_housing_services,Owner-Occupiers' Housing Services,GBP,not-supplied,0.027000000000000003,0.02200
thanks for spotting that!  you are right, I will fix it

2022-11-25 11:11 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +18c2b030-00f0-4eb7-bd7f-0a26a06caee5,Consumer Goods and Services,Recreation and Culture,consumer_goods-type_creative_arts_and_entertainment_services,Creative/arts and entertainment services,GBP,not-s
oops! I will check if I can adjust the script otherwise I have to fix it manually

2022-11-25 11:25 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
Hmm I don't know the dataset name you are suggesting sounds very generic to me...  
Well, this is the exact name on their website: UK full dataset 1990 - 2019, including conversion factors by SIC code
I think in the dataset column we have to provide the exact name that the user will find on the website of the source so that there won't be any confusions. Of course it's also helpful for the data team for future updates. @maryarbab what do you think?

2022-11-25 11:45 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
Concerning the question if they are AR4 values: According to their methodology report yes! At least that's what I understood when searching. Please check page 14 points 1.7 and 1.8 
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1083857/2022-ghg-cf-methodology-paper.pdf

2022-11-25 11:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
I suggested the name of the dataset on their website, not the name of the file :)

2022-11-25 11:52 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +e1976aac-f8cc-4d90-9885-630c0531dc42,Agriculture/Hunting/Forestry/Fishing,Timber and Forestry Products,timber_forestry-type_wood_and_of_products_of_wood_and_cork_except_furniture_articles_of_straw_an
Let us delete this "of" before products, looks like typo

2022-11-25 11:52 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +dc7e74b9-e07e-42ed-b0e6-f2d92c2ba04f,Organizational Activities,Professional Services and Activities,professional_services-type_accounting_bookkeeping_and_auditing_services_tax_consulting_services,Acc
ah! good to know :D

2022-11-25 12:02 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
Agree with Anastasia that "UK and England's carbon footprint to 2019" is the dataset name and "UK full dataset 1990 - 2019, including conversion factors by SIC code" is the file name.

2022-11-25 12:07 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +2612ace9-a537-4c12-b495-6021b1a534bf,Agriculture/Hunting/Forestry/Fishing,Agriculture/Hunting/Forestry/Fishing,agriculture_fishing_forestry-type_products_of_agriculture_hunting_and_related_services,P
but for the dataset name if we report "UK and England's carbon footprint to 2019" it is not clear for which file we are talking about on their website. I just thought that with the dataset name we are referring to the name of the exact file you will have to download

2022-11-28 11:10 UTC, AnastasiaLobanova approved these changes

2022-11-28 11:10 UTC, merged