Facility properties and emissions added to the OEFDB from GHG Protoco…
climatiq/Open-Emission-Factors-DB pull request #351
Opened 2022-11-28 15:05 UTC by deliceli

…l Evulation Tool Scope3

**Is this a new addition or an update to an existing factor?**

New

**What category or categories does it affect?**

 Facility 

**What?**

Emission factors for the "Facility" category added from GHG Evaluation Tool Scope 3. 

**Why?**

Client request

2022-11-29 15:57 UTC, maryarbab requested changes
Looks good @deliceli, thank you! Few notes:

1. Does the source mention LCA boundary? If not, we should have "unknown" in the lca_activity field.
2. "Facility" should be added to the schema and also "Sector-Category-ID_structure.csv" file. You can also make those changes in this PR.
3. I wonder if we should provide more information about what each scope includes in terms of activities. Does the source provide such information?

2022-11-29 16:41 UTC, AnastasiaLobanova requested changes

2022-11-29 16:41 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Buildings and Infrastructure,Facility,facility-type_lodging_owned,Lodging facility owned,m2,not-supplied,40.145,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,,GHG Protocol,,201
There are two other EFs for Scopes 1 and 2 missing in the Lodging.

I also don't see Education facilities. Could you cross-check that all types of facilities are included here please

2022-12-02 13:55 UTC, deliceli commented on OpenEmissionFactorsDB.csv
> +,Buildings and Infrastructure,Facility,facility-type_lodging_owned,Lodging facility owned,m2,not-supplied,40.145,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,,GHG Protocol,,201
All the comments taken into consideration

2022-12-02 14:49 UTC, maryarbab approved these changes

2022-12-05 22:23 UTC, closed without merging