EF of the Shisheido products added
climatiq/Open-Emission-Factors-DB pull request #352
Opened 2022-11-28 15:19 UTC by deliceli

**Is this a new addition or an update to an existing factor?**

Update

**What category or categories does it affect?**

Personal Care and Accessories

**What?**

EF's of some Shiseido products added to the OEFDB

**Why?**

Client request

2022-11-29 15:50 UTC, AnastasiaLobanova requested changes

2022-11-29 15:50 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
I think lca_activity should be cradle_to_grave, wdyt @maryarbab  ?

2022-11-29 15:50 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
I suggest adjusting the description to: "Emission intensity of facial wash. Factors were obtained from the Environmental Product Footprint LCA-based study conducted by Shiseido according to ISO 140401."

2022-11-29 16:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
@AnastasiaLobanova Agree that it is full LCA, i.e. cradle_to_grave

2022-11-29 16:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
Not sure if it is only scope 3. My suggestion is to leave the scope field blank

2022-11-29 16:13 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
Also agree with rewording the description.

2022-12-02 10:18 UTC, deliceli commented on OpenEmissionFactorsDB.csv
> +,Consumer Goods and Services,Personal Care and Accessories,consumer_goods-type_facial_wash,,g,not-supplied,0.041,not-supplied,not-supplied,not-supplied,not-supplied,not-supplied,,3,cradle_to_shelf,Sh
Changed everything.

2022-12-02 10:23 UTC, AnastasiaLobanova requested changes
Nice work Egeberk! We need to change now the schema.toml file in the metadata folder - to add new units, as well as new LCA activity values.

2022-12-02 10:57 UTC, deliceli commented
> 
<img width="1287" alt="Screenshot 2022-12-02 at 11 54 40" src="https://user-images.githubusercontent.com/113440423/205277498-43898534-8594-4140-85ed-830b2ac2bc5b.png">

Should i add it manually from that button?

2022-12-02 11:06 UTC, AnastasiaLobanova commented
If it is possible then why not. I always do it from my local version using Visual Studio Code

2022-12-02 12:04 UTC, AnastasiaLobanova approved these changes
Looks good to me!

2022-12-02 12:09 UTC, maryarbab approved these changes

2022-12-02 14:42 UTC, merged