Update OpenEmissionFactorsDB.csv
climatiq/Open-Emission-Factors-DB pull request #367
Opened 2022-12-14 17:43 UTC by patstirling

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Road Freight

**What?**

Several small fixes to IDs

**Why?**

These were erroneous

2022-12-14 19:05 UTC, maryarbab requested changes
Looks good to me, @patstirling! Just two notes:
1- "t" seems to be missing in the lower range in rows 19637-19640
2- I assume these EFs are added to the dataset from page 104, right? So, the description needs to be Well-to-Wheel (WTW) for rows 19633-19640 and 19830-19833

2022-12-14 22:46 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +3cd3e74a-c6f0-4b5b-b2a4-d86c6b6a1c57,Transport,Road Freight,freight_vehicle-vehicle_type_mgv-fuel_source_na-vehicle_weight_gt_7.5_lt_20t-distance_uplift_included,MGV (7.5-20 t),tonne-km,not-supplied,
Good catches - have added in the missing "t"s.

I hadn't reviewed the rest of the fields - but good spot -the description didn't reflect what was in the lca_activity field for these EFs, have corrected.

2022-12-15 05:30 UTC, maryarbab requested changes

2022-12-15 05:30 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +6a0d821a-7c3b-4576-bfa9-e69439b5ada9,Transport,Road Freight,freight_vehicle-vehicle_type_mgv-fuel_source_na-vehicle_weight_gt_7.5t_lt_20t-distance_uplift_included,MGV (7.5-20 t),tonne-km,not-supplied
There is a small typo here: WT@-> WTW

2022-12-15 10:05 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +6a0d821a-7c3b-4576-bfa9-e69439b5ada9,Transport,Road Freight,freight_vehicle-vehicle_type_mgv-fuel_source_na-vehicle_weight_gt_7.5t_lt_20t-distance_uplift_included,MGV (7.5-20 t),tonne-km,not-supplied
Fixed! Thanks

2022-12-15 10:07 UTC, maryarbab approved these changes

2022-12-15 10:07 UTC, merged