Scopes and LCA added to GHG
climatiq/Open-Emission-Factors-DB pull request #382
Opened 2023-01-06 10:28 UTC by deliceli

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [X ] Update

**What category or categories does it affect?**

Facility 

**What?**

LCA and Scopes added to name

**Why?**

To make it more understandable and easy to find

2023-01-06 13:18 UTC, gpantelidou approved these changes
seems good to me!!

2023-01-10 10:40 UTC, maryarbab requested changes
Looks good! Thanks @deliceli. Just a small comment and also one note:

We discussed in this slack thread (https://climatiq.slack.com/archives/C020ADYRGS1/p1672766335005329) to provide more information regarding the assumptions you made to derive these EFs. I guess that is still missing from the description.

2023-01-10 10:40 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +a8a09fc4-4e0c-49d4-88d4-e125c43187a4,Buildings and Infrastructure,Facility,facility-type_public_order_and_safety_owned,Public order and safety facility owned [scope 1],m2,not-supplied,25.701,not-supp
scope is missing from the activity_id

2023-01-10 17:23 UTC, AnastasiaLobanova reviewed
Looks good Egeberk! Since we have now lca included, do we still need the "scope" part in the id? I am not sure if these factors are used by someone now

2023-01-10 19:46 UTC, deliceli commented
> Looks good! Thanks @deliceli. Just a small comment and also one note:
> 
> We discussed in this slack thread (https://climatiq.slack.com/archives/C020ADYRGS1/p1672766335005329) to provide more information regarding the assumptions you made to derive these EFs. I guess that is still missing from the description.

The description that we used is the one below. I think years and also employee commuting is given clearly. We just need to add other parameters that we set such as Employee and Waste parameter. You can see my description offer below (Bold one). Waiting for your comment.

- Emission intensity of office facility leased. Factors retrieved from the Quantis+GHG Protocol Scope 3 Calculator for the year 2016 and apply for years beyond 2016. Scope 3 emissions do not include employee commuting.

**- Emission intensity of office facility leased. Factors retrieved from the Quantis+GHG Protocol Scope 3 Calculator for the year 2016 and apply for years beyond 2016. Scope 3 emissions do not include employee commuting. For each related activity id, the Number of Employees was set to 1 to 50 additionally, the Waste parameter which was given in USD set to ''0'' since that is activity-based data.**

2023-01-10 19:48 UTC, deliceli commented on OpenEmissionFactorsDB.csv
> +a8a09fc4-4e0c-49d4-88d4-e125c43187a4,Buildings and Infrastructure,Facility,facility-type_public_order_and_safety_owned,Public order and safety facility owned [scope 1],m2,not-supplied,25.701,not-supp
> scope is missing from the activity_id

I'm afraid it slipped out of my eye. Will fix that.

2023-01-10 20:00 UTC, gpantelidou commented
@deliceli Egeberk, remember that you cannot use commas since it is a csv file, so be careful with the changes in the description text !!

2023-01-11 11:18 UTC, maryarbab commented
My suggestion for the last part of the description: "The assumptions are 1 to 50 for the number of employees and 0 for the amount of USD spent on waste."

2023-01-11 11:21 UTC, maryarbab commented
My suggestion for the last part of the description: "Assumptions are 1-50 for the number of employees and 0 for the amount of USD spent on waste."

2023-01-13 09:59 UTC, deliceli commented on OpenEmissionFactorsDB.csv
> +a8a09fc4-4e0c-49d4-88d4-e125c43187a4,Buildings and Infrastructure,Facility,facility-type_public_order_and_safety_owned,Public order and safety facility owned [scope 1],m2,not-supplied,25.701,not-supp
@maryarbab one question popped up again. If I add scope to the activity id it will be a breaking change also (Since it Is already in the OEFDB) should I skip that?

2023-01-13 10:42 UTC, closed without merging