adding fertilizer EFs
climatiq/Open-Emission-Factors-DB pull request #416
Opened 2023-02-13 13:49 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Arable farming

**What?**

adding fertilizer EFs

**Why?**

new EFs ingress

2023-02-13 16:19 UTC, TimCroker requested changes

2023-02-13 16:19 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +4fa7a6e4-536d-4b0e-a3a5-8f5c3068dfd1,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_urea_wet_climate_indirect,Indirect emissions from urea fertilizer application in wet
arable_farming should be replaced with crop_production throughout

2023-02-13 16:19 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +5392bacb-84fb-4d34-abfd-94b00f99341a,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_nitrate_based_wet_climate_indirect,Indirect emissions from nitrate based fertilizer
Change all instances of arable_farming to crop_production

2023-02-15 10:02 UTC, TimCroker submitted a review, later dismissed

2023-02-15 15:02 UTC, TimCroker requested changes

2023-02-15 15:02 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +44786e2f-2389-4ce4-9554-007379b3d394,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_urea_wet_climate_indirect,Indirect emissions from urea fertilizer application in wet
Slight typo: revise, for all INDIRECT EFs:
_From:_
From IPCC ""2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories"". Chapter 11 Equation 11.10.
_To_
From IPCC ""2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories"". Chapter 11 Equations 11.10 and 11.11.

2023-02-15 15:02 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +2414a1d1-2d07-492b-adbe-6c59fddcdc59,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_ammonium_based_wet_climate_indirect,Indirect emissions from ammonium based fertilize
Slight typo: revise, for all INDIRECT EFs:
_From:_
From IPCC ""2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories"". Chapter 11 Equations 11.10 and Equation 11.1
_To_
From IPCC ""2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories"". Chapter 11 Equations 11.10 and 11.11.

2023-02-15 16:23 UTC, TimCroker approved these changes

2023-02-16 08:30 UTC, gpantelidou approved these changes

2023-02-16 08:32 UTC, merged