add EFs for electricity endpoint computing
climatiq/Open-Emission-Factors-DB pull request #417
Opened 2023-02-14 12:04 UTC by gpantelidou

**Is this a new addition or an update to an existing factor?**

- [X] New
- [ ] Update

**What category or categories does it affect?**

Electricity

**What?**

add missing EFs for electricity endpoint computing 

**Why?**

useful EFs for the endpoint computing project and now new data in the OEFDB

2023-02-14 12:59 UTC, gpantelidou commented
The EFs reported under AR5 have been checked! 
I didn't include the text "not-supplied" to be consistent with data from previous years but I will look again.

2023-02-14 13:13 UTC, patstirling commented
Are we sure about Google being lca_activity=`electricity_generation` not `electricity_consumption` - e.g. does it include t&d

2023-02-14 13:41 UTC, gpantelidou commented
@patstirling About Google lca_activity:  I changed it to electricity_generation after this discussion on linear: 
https://linear.app/climatiq/issue/PROD-633/lca-activities-of-emission-factors

2023-02-15 12:35 UTC, AnastasiaLobanova requested changes

2023-02-15 12:35 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +UUID,sector,category,activity_id,name,activity_unit,kgCO2e-AR5,kgCO2e-AR4,kgCO2,kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,uncertainty,scope,lca_activity,source,dataset,year_released,year_
Everything looks clean to me @gpantelidou - just in this line is a copied header, should be deleted :)

2023-02-15 12:41 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +UUID,sector,category,activity_id,name,activity_unit,kgCO2e-AR5,kgCO2e-AR4,kgCO2,kgCH4,kgN2O,kgCO2e-OtherGHGs-AR5,kgCO2e-OtherGHGs-AR4,uncertainty,scope,lca_activity,source,dataset,year_released,year_
Oh no, ah thanks for spotting that !!!

2023-02-15 16:18 UTC, closed without merging