added electricity EFs from UK suppliers
climatiq/Open-Emission-Factors-DB pull request #423
Opened 2023-03-01 16:06 UTC by gpantelidou

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Electricity

**What?**

new fuel mix EFs from electricity suppliers in UK for the latest year (most 2022, a few 2021) + new sub-id for the activity_id structure. 

**Why?**

good dataset for UK customers

2023-03-01 16:44 UTC, maryarbab submitted a review, later dismissed
Looks clean!

2023-03-02 09:35 UTC, TimCroker requested changes

2023-03-02 09:35 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +65eaec9f-a8c2-49ef-bb44-eaf77be191d2,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_ammonium_based_combined_climate_direct,Direct emissions from ammonium based fertiliz
What are the extra " for e.g.
from IPCC ""2019 Refinement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories"".

2023-03-02 09:35 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +65eaec9f-a8c2-49ef-bb44-eaf77be191d2,Agriculture/Hunting/Forestry/Fishing,Arable Farming,arable_farming-fertilizer_ammonium_based_combined_climate_direct,Direct emissions from ammonium based fertiliz
See also other lines on arable farming

2023-03-02 09:35 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +,Energy,Electricity,electricity-energy_source_grid-supplier_boost,Electricity supplied from grid - supplier Boost,kWh,not-supplied,0.261,0.261,not-supplied,not-supplied,not-supplied,not-supplied,,2,e
(applies to all entries)

2023-03-02 09:35 UTC, TimCroker commented on OpenEmissionFactorsDB.csv
> +,Energy,Electricity,electricity-energy_source_grid-supplier_boost,Electricity supplied from grid - supplier Boost,kWh,not-supplied,0.261,0.261,not-supplied,not-supplied,not-supplied,not-supplied,,2,e
Change year-valid to the year before publishing for all i.e. 2022 publish = 2021 valid

2023-03-02 10:34 UTC, TimCroker approved these changes

2023-03-02 11:08 UTC, maryarbab approved these changes

2023-03-02 12:11 UTC, merged