fix activity units and update sector-category-id file
climatiq/Open-Emission-Factors-DB pull request #428
Opened 2023-03-28 13:04 UTC by gpantelidou

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

activity units 

**What?**

fixed activity units for 7 emission factors from GHG protocol and since it was a small PR I also updated the sector-category-id file

**Why?**

correct breaking changes and keep the sector-category-id file up-to-date

2023-03-28 13:27 UTC, AnastasiaLobanova reviewed
Looks great! 
Did you cross-check all activity_ids structure in the structure file?

2023-03-28 14:53 UTC, AnastasiaLobanova commented
Yes, I think we should try to check in Python, I have no precise idea how but we can check tomorrow together if you want

2023-03-28 15:54 UTC, gpantelidou commented
@AnastasiaLobanova yes let's check this together tomorrow thank you :)

2023-03-28 21:04 UTC, maryarbab requested changes

2023-03-28 21:04 UTC, maryarbab commented on Sector-Category-ID_structure.csv
> +Energy,Electricity,electricity-energy_source_[....]-supplier_[....],
@gpantelidou did we already change electricity id structure?

2023-03-29 06:50 UTC, gpantelidou commented on Sector-Category-ID_structure.csv
> +Energy,Electricity,electricity-energy_source_[....]-supplier_[....],
No we didn't. This id structure `electricity-energy_source_[....]-supplier_[....]` was added recently when we added electricity EFs for specific UK suppliers. In this PR just noticed this strange character �. inside the [ ]  instead of ... when I opened the file and just changed it

2023-03-29 07:05 UTC, maryarbab commented on Sector-Category-ID_structure.csv
> +Energy,Electricity,electricity-energy_source_[....]-supplier_[....],
okay, let's fix this for now and then have a discussion about electricity ids

2023-03-29 07:06 UTC, maryarbab approved these changes

2023-03-29 09:39 UTC, merged