change activity_ids for electricity supplier mix and add new relevant…
climatiq/Open-Emission-Factors-DB pull request #434
Opened 2023-04-07 11:29 UTC by gpantelidou

… EFs

**Is this a new addition or an update to an existing factor?**

- [x] New
- [x] Update

**What category or categories does it affect?**

Electricity

**What?**

change activity_ids for electricity supplier mix EFs and add new EFs from Electricity Info for year 2021

**Why?**

correct breaking changes + add 2021 data for UK suppliers since until now we had only the latest data from their table (for some companies latest data were for year 2022 and for others for 2021)

2023-04-07 13:07 UTC, maryarbab requested changes

2023-04-07 13:07 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +caa42d23-6bce-4392-a5b7-663aad746165,Energy,Electricity,electricity-supply_grid-source_supplier_mix_location_based,Electricity supplied from grid,kWh,0.81,0.81,0.81,0.0,0.0,not-supplied,not-supplied,
Let's remove "location_based" from the id for this and the following ones.

2023-04-07 13:07 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +b9cecd80-d0df-4217-8bf5-62276588e9cb,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - UK Average,kWh,not-supplied,0.204,0.204,not-supplied,no
No need for the UK average in the id. We already have it in the region.

2023-04-07 13:07 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +317f9e7e-e820-406a-97d4-903f42013904,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - supplier UK Average,kWh,not-supplied,0.194,0.194,not-su
No need for the UK average in the id. We already have it in the region.

2023-04-07 13:20 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +1bdecbac-2adb-49cf-91a0-49a838a976a7,Energy,Electricity,electricity-supply_grid-source_supplier_mix_dkis,Electricity supplied from grid,kWh,not-supplied,0.54,not-supplied,not-supplied,not-supplied,no
I was also wondering if it is neccessary to have it in the activity_id - since it could be included in the region as we have for example with eGRID data for the US. But then the region here would be `AU-NT-DKIS` or `AU-DKIS` ?

2023-04-07 13:21 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +3c8b7c62-c15d-45c7-a494-3147cb3e703d,Energy,Electricity,electricity-supply_grid-source_supplier_mix_bulb,Electricity supplied from grid - supplier Bulb,kWh,not-supplied,0.0,0.0,not-supplied,not-suppl
It's just Bulb - doublechecked here: 
https://electricityinfo.org/fuel-mix-of-uk-domestic-electricity-suppliers/?y=2021#tabletop

2023-04-07 13:22 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +caa42d23-6bce-4392-a5b7-663aad746165,Energy,Electricity,electricity-supply_grid-source_supplier_mix_location_based,Electricity supplied from grid,kWh,0.81,0.81,0.81,0.0,0.0,not-supplied,not-supplied,
alright, I will delete this part

2023-04-07 13:23 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +b9cecd80-d0df-4217-8bf5-62276588e9cb,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - UK Average,kWh,not-supplied,0.204,0.204,not-supplied,no
Ah yes you're right - will remove it

2023-04-07 13:25 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +b9cecd80-d0df-4217-8bf5-62276588e9cb,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - UK Average,kWh,not-supplied,0.204,0.204,not-supplied,no
@maryarbab should I also delete the UK Average from the name and leave it just Electricity supplied from grid ?

2023-04-07 13:26 UTC, gpantelidou commented on OpenEmissionFactorsDB.csv
> +317f9e7e-e820-406a-97d4-903f42013904,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - supplier UK Average,kWh,not-supplied,0.194,0.194,not-su
yes yes - same as your comment above

2023-04-07 13:58 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +b9cecd80-d0df-4217-8bf5-62276588e9cb,Energy,Electricity,electricity-supply_grid-source_supplier_mix_uk_average,Electricity supplied from grid - UK Average,kWh,not-supplied,0.204,0.204,not-supplied,no
No, let's keep it in the name

2023-04-10 09:48 UTC, maryarbab approved these changes

2023-04-10 09:53 UTC, merged