de-dupe IDs
climatiq/Open-Emission-Factors-DB pull request #44
Opened 2021-11-08 14:50 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Multiple categories

**What?**

Cleaning entries with the same ID+year+unit+source

**Why?**

It is critical for API implementation

2021-11-08 15:49 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0791,10,ADEME,2014,FR,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh su
this is deleted bc we have another entry from ADEME in line 883, which has more activities included. They are different only by the activities entry so we can add this one in the next update when for the uniqueness of EF we will tackle also the activity field.

2021-11-08 15:54 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.69,,DISER,2018,AU-WA-SA,2021/07/30,Emission Intensity of Western Australia – South West Interconnected System (SWIS)'s Gri
@patstirling please check here!

2021-11-08 15:54 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
this is deleted for now as there were two entries - soybean diesel end and soybean diesel sustain, which I assume should be soybean diesel produced with renewable energy, but the EF was higher than the soybean diesel end. So it is not too clear what sustain refers to.

2021-11-08 15:54 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_hydrogen-distance_unknown-engine_size_large,Hydrogen passenger car large,kg-CO2e/pkm,0,,UBA,2020,DE,2021/09/15,Emission intensity
these three are deleted bc I was not able to find out what is the difference between BZ (which should be brennstoffzelle, a cell for fuel burn) and otto engine (which should be steam-based, but are they still used?...) we can add those back after verification with UBA

2021-11-08 17:51 UTC, patstirling requested changes

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.69,,DISER,2018,AU-WA-SA,2021/07/30,Emission Intensity of Western Australia – South West Interconnected System (SWIS)'s Gri
Suggest this remains as AU-WA (as that is the correct UNLocode) but that we change the ID to read -energy_source_swis_grid_mix

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.59,,DISER,2018,AU-WA,2021/07/30,Emission Intensity of Western Australia – North Western Interconnected System (NWIS). Grid
Suggest this remains as AU-WA (as that is the correct UNLocode) but that we change the ID to read -energy_source_nwis_grid_mix

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.594,15,ADEME,2018,FR-2A-FR-2B,2021/08/13,"Emission intensity of grid mix as reported. Overseas departments and territories
Just while we are here, "Corse" should be "Corsica"

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0791,10,ADEME,2014,FR,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh su
Is this captured somewhere so we won't forget to ad back in?

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_grid_mix,Transmission & distribution,kg-CO2e/kwh,0.01879,,BEIS,2021,GB,2021/07/23,Emission intensity of transmissions & distribution (T&D). Available in B
Are all T&Ds being removed? If so, are we capturing this info somewhere?

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_roro_ferry-route_type_unknown-vessel_length_unknown-tonnage_average-fuel_source_unknown,RoRo-ferry (average),kg-CO2e/tkm,0.051659,,MfE,2020,NZ,2021/09/
Name: "RoRo-ferry (average)" -> "RoRo ferry" to align with other EFs in this category

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_roro_ferry-route_type_unknown-vessel_length_unknown-tonnage_from_0_to_1999lm-fuel_source_unknown,RoRo-ferry 0 - 1999 lane meters,kg-CO2e/tkm,0.06114,,M
Name: "RoRo-ferry 0 - 1999 lane meters" -> "RoRo ferry (0-1999 lane meters)"

Description: suggest "Emission intensity for roll-on/roll-off (RoRo) Ferry of between 0 and 1999 lane meters.  A lane meter is a unit of deck area in roll-on/roll-off ships. Published by the Ministry for the Environment of New Zealand in 2020."

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_general_cargo-route_type_unknown-vessel_length_unknown-tonnage_average-fuel_source_unknown,General cargo,kg-CO2e/tkm,0.01323,,BEIS,2021,GB,2021/07/23,E
?!?!?!

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_vehicle_cargo-route_type_unknown-vessel_length_unknown-tonnage_average-fuel_source_unknown,Cargo ship vehicle transport,kg-CO2e/tkm,0.03858,,BEIS,2021,
suggest id "vessel_type_vehicle_carrier" and name "Cargo ship (vehicle carrier)"

2021-11-08 17:51 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
It will likely be sustainably sourced soybean. It's not impossible for this to be a higher EF depending on the supply chain and any change in land use - although seems very strange as one would think the definition of sustainable would infer lower carbon emissions. Suggest we ask Phil to review.

2021-11-08 18:25 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0791,10,ADEME,2014,FR,2021/08/13,Emission intensity of grid mix as reported. The values take electrical and thermal kWh su
Yes! I have it noted in a doc on my PC and also here: https://docs.google.com/spreadsheets/d/1mbSljVKYUVU_a0I3WexOfZWm-3vhynrcqcwTgPJb8S0/edit?usp=sharing

2021-11-08 18:44 UTC, maryarbab submitted a review, later dismissed

2021-11-09 08:48 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
I have asked him! :)

2021-11-09 08:54 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,electricity-energy_source_grid_mix,Transmission & distribution,kg-CO2e/kwh,0.01879,,BEIS,2021,GB,2021/07/23,Emission intensity of transmissions & distribution (T&D). Available in B
I found only one entry of T&D across all DB

2021-11-09 10:14 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
Yes! Confirmed with Phil and also while clicking through all the process inputs at the UBA website (6 different windows) I found that it is written that soja beans are produced with the highest social and environmental standards.

2021-11-09 10:17 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
hm - still seems strange that the more sustainable soya leads to more emissions? But if that's what the data says...

2021-11-09 10:18 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> -Transport,Road Travel,passenger_vehicle-vehicle_type_car-fuel_source_diesel_soybean_oil-distance_unknown-engine_size_medium,Diesel passenger car medium - soybean oil sustain end energy,kg-CO2e/pkm,0.
Another question to ask UBA!

2021-11-09 13:15 UTC, maryarbab approved these changes

2021-11-09 13:15 UTC, patstirling requested changes

2021-11-09 13:15 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_marine_gas_oil,fuel_type_marine_gas_oil-acitvity_combustion,kg-CO2e/l,2.77539,,BEIS,2021,GB,2021/07/23,Emission intensity of marine gas oil. The fuels conversion factors should
acitvity_combustion (mispelling of activity) still in ID - check for this across DB

2021-11-09 14:23 UTC, patstirling requested changes

2021-11-09 14:23 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_metropolitan-fuel_source_average,National average for metropolitan passenger train,kg-CO2e/pkm,0.03772874,,MfE,2020,NZ,2021/09/10,Emission intensity f
not expecting to see activity_ in the activity column...

2021-11-09 14:23 UTC, patstirling approved these changes

2021-11-09 14:28 UTC, merged