got rid of commas and aposthrophes
climatiq/Open-Emission-Factors-DB pull request #46
Opened 2021-11-09 14:59 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

All categories (more or less)

**What?**

This is the final retouching of the DB bf the release. Small things like commas, not needed double quotes are deleted, abbreviations introduced etc. 

**Why?**

To finalize larger work on restructuring the IDs and OEFDB

2021-11-09 16:13 UTC, patstirling requested changes

2021-11-09 16:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_international_rail-fuel_source_unknown,International rail passenger train,kg-CO2e/pkm,0.02813,,BEIS,2021,GB,2021/07/23,Emission intensity for internat
"London-Brussels London-Paris London-Marne Le Vallee (Disney) London-Avignon London-Amsterdam and the ski train from London to Bourg-Saint-Maurice" -> "London-Brussels/London-Paris/London-Marne Le Vallee (Disney)/London-Avignon/London-Amsterdam/London to Bourg-Saint-Maurice (ski train)"

2021-11-09 16:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Travel,passenger_flight-route_type_unknown-aircraft_type_unknown-distance_between_300_and_2300mi-class_unknown-contrails_unknown,Medium-haul flight,kg-CO2e/pmile,0.131,,EPA,2021,US,2021
"medium haul flight. Medium Haul (>= 300 miles < 2300 miles)" -> "medium haul flight (between 300 and 2300 miles)"

2021-11-09 16:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv_rigid_refrig-fuel_source_diesel-vehicle_weight_unknown-percentage_load_50_laden,Road freight diesel refrigerated rigid HGV 50% laden,kg-CO2e/
"No upstream or downstream LCA activity is included only fuel combustion." -> "Emissions from fuel combustion only." throughout DB

2021-11-09 16:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_unknown-fuel_source_electricity,Electric passenger train,kg-CO2e/pkm,0.0388,20,ADEME,2020,IE,2021/08/20,Emission intensity for electric train travel (
"This emission factor accounts for energy (electricity - at plant) including fuel combustion and upstream. The data for European countries were taken from a study of the International Union of Rail-ways (UIC) on external effects commonly referred to as the INFRAS-IWW study which was updated in October 2004 with reference year 2000. This study makes it possible to establish emission factors for rail passenger transport in different European countries for traction energy alone. All the available data integrate the upstream and combustion of the traction energy used. It does not include the manufacture of rolling stock or emissions related to the infrastructure (railway tracks stations etc.)." -> "Including emissions from electricity generation and transmission/distribution" throughout DB

2021-11-09 16:13 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Transport,freight_train-route_type_domestic-fuel_type_electric,Rail freight electric train,kg-CO2e/tkm,0.019,,UBA,2020,DE,2021/09/15,Emission intensity of goods transported by electric
Replace "Data from the Öko-Instituts renewbility technology database." -> "Data from the Öko-Institut" thrroughout DB

Replace ".Provided by the Öko-Institut." -> ". Provided by the UBA" throughout DB

2021-11-09 16:34 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0977,,MfE,2019,NZ,2021/09/10,Emission intensity of grid mix as reported. Published by New Zealands Ministry for the Enviro
@Pat here you mean remove all instances of "It is Generation Factor" from MfE entries?

2021-11-09 16:36 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0977,,MfE,2019,NZ,2021/09/10,Emission intensity of grid mix as reported. Published by New Zealands Ministry for the Enviro
Or replace it with "Includes generation factor"?

2021-11-09 16:41 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0977,,MfE,2019,NZ,2021/09/10,Emission intensity of grid mix as reported. Published by New Zealands Ministry for the Enviro
Sorry comment was lost in the mist - well spotted, it should be replace with "Includes generation factor" for now

2021-11-10 07:35 UTC, patstirling requested changes

2021-11-10 07:35 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_transit_rail-fuel_source_unknown,Transit rail passenger train,kg-CO2e/pmile,0.106,,EPA,2021,US,2021/08/23,Emission intensity for average passenger tra
"rail typically within an urban center such as subways elevated railways metropolitan railways (metro) streetcars trolley cars and tramways. Published by the EPA. The method of calculation used is the distance-based method which involves determining the mass distance and mode of each shipment then applying the appropriate mass-distance emission factor for the vehicle used. The activity is unknown." -> "rail typically within an urban center such as subways/elevated railways/metropolitan railways (metro)/streetcars/trolley cars/tramways. Published by the EPA. The method of calculation used is the distance-based method which involves determining the mass/distance/mode of each shipment then applying the appropriate mass-distance emission factor for the vehicle used. LCA activity is unknown.

2021-11-10 07:35 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_domestic-distance_unknown-weight_unknown-contrails_unknown,Domestic air freight,kg-CO2e/tkm,1.19,,UBA,2020,DE,2021/09/15,Emission intensity of inland
"Data from the Öko-Instituts renewability technology database." -> "Provided by the UBA" throughout DB

2021-11-10 08:20 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_domestic-distance_unknown-weight_unknown-contrails_unknown,Domestic air freight,kg-CO2e/tkm,1.19,,UBA,2020,DE,2021/09/15,Emission intensity of inland
I cannot find this entry in the latest commit..

2021-11-10 08:32 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_domestic-distance_unknown-weight_unknown-contrails_unknown,Domestic air freight,kg-CO2e/tkm,1.19,,UBA,2020,DE,2021/09/15,Emission intensity of inland
Btw and renewability should be spelled as '[renewbility](http://www.renewbility.de/)'.

2021-11-10 08:45 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Air Transport,freight_flight-route_type_domestic-distance_unknown-weight_unknown-contrails_unknown,Domestic air freight,kg-CO2e/tkm,1.19,,UBA,2020,DE,2021/09/15,Emission intensity of inland
We should (eventually) remove all of these as it is VERY confusing to the reader and doesn't add much - simply "Provided by the UBA" is enough. Adding to data health

2021-11-10 10:27 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.0977,,MfE,2019,NZ,2021/09/10,Emission intensity of grid mix as reported. Published by Includes production fuel mix factor.
It is just this in line! But this is a very nice catch - I got really lucky here, bc the previous comments was:

"New Zealands Ministry for the Environment" -> "the New Zealand MfE" in all cases.

And I have wrongly replaced it with the "Includes production fuel mix factor". Luckily, this is the only place with the "New Zealands Ministry for the Environment", other entries related to MfE have "Published by the Ministry for the Environment of New Zealand" in the description. I will replace it this way also in this line and if we want to change it in the future, I suggest adding it to the Health Card.

2021-11-10 10:57 UTC, patstirling requested changes

2021-11-10 10:57 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_grid_mix,Grid mix,kg-CO2e/kwh,0.21233,,BEIS,2021,GB,2021/07/23,Emission intensity of electricity generated as reported. Available in BEISs Greenhouse Gas
"BEISs" -> "BEIS"

2021-11-10 10:58 UTC, patstirling approved these changes

2021-11-10 11:09 UTC, merged