Resolve esoteric IDs in the fuel category
climatiq/Open-Emission-Factors-DB pull request #49
Opened 2021-11-10 14:53 UTC by patstirling

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Fuel

**What?**

Resolve esoteric IDs in the fuel category

**Why?**

Provide better comparability across EFs

2021-11-10 15:55 UTC, maryarbab requested changes

2021-11-10 15:55 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_kerosene,Aviation turbine fuel (kerosene),kg-CO2e/l,2.54514,,BEIS,2021,GB,2021/07/23,Emission intensity of aviation turbine fuel for turbo-prop aircraft and jets (
Aviation turbine is what is being noted by the source...

2021-11-10 15:55 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo,Biodiesel HVO,kg-CO2e/l,0.03558,,BEIS,2021,GB,2021/07/23,Emission intensity of hydrogenated vegetable oil (HVO) biodiesel. Available in BEIS Greenhouse Gas Reporti
Why do we remove the decription?

2021-11-10 15:55 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_petrol,Petrol,kg-CO2e/l,2.33969,,BEIS,2021,GB,2021/07/23,Emission intensity of 100% mineral petrol. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
why do we remove the description?

2021-11-10 16:00 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
Other fuel EFs (e.g. the BEIS ones) which are used for transport don't specify this, so to provide standardisation decided to normalise this EF with the others and for the outlier (stationary) provide a point of difference

2021-11-10 16:06 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_kerosene,Aviation turbine fuel (kerosene),kg-CO2e/l,2.54514,,BEIS,2021,GB,2021/07/23,Emission intensity of aviation turbine fuel for turbo-prop aircraft and jets (
If you look at the two sources here, they are both reporting two things - kerosene-based aviation fuel (aka AVTUR, jet fuel or turbine fuel - https://en.wikipedia.org/wiki/Aviation_fuel#Jet_fuel, https://en.wikipedia.org/wiki/Jet_fuel) and petrol-based aviation fuel (aka Avgas https://en.wikipedia.org/wiki/Aviation_fuel#Avgas, https://en.wikipedia.org/wiki/Avgas). I'll correct to "(petrol)" - this should make it clear what the two are, and standardise them

2021-11-10 16:09 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_biodiesel_hvo,Biodiesel HVO,kg-CO2e/l,0.03558,,BEIS,2021,GB,2021/07/23,Emission intensity of hydrogenated vegetable oil (HVO) biodiesel. Available in BEIS Greenhouse Gas Reporti
The description is designed to help the user select the appropriate EF - in these instances the text is methodology-oriented, which we don't need to include (there is a much larger process to go through ragarding this!)

2021-11-10 16:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_petrol,Petrol,kg-CO2e/l,2.33969,,BEIS,2021,GB,2021/07/23,Emission intensity of 100% mineral petrol. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
see above

2021-11-10 16:17 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-11-10 16:17 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
let us add it to the name then?

2021-11-10 17:15 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
yep it is (line 408): "Diesel (stationary industrial use)"

2021-11-10 17:25 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
but the "transport" is not in the name, right?

2021-11-10 18:49 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
Good point!

2021-11-10 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_fuel_petroleum,Aviation fuel (petroleum),kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation gasoline. Published by the Ministry for the Environm
Wait yes they are in the name

2021-11-11 07:17 UTC, maryarbab approved these changes
Looks great, Pat! Thank you so much for making the effort to add the "use" sub-category!

2021-11-11 08:18 UTC, AnastasiaLobanova approved these changes

2021-11-11 08:23 UTC, merged