Specify emissions for business travel
climatiq/Open-Emission-Factors-DB pull request #5
Opened 2021-09-23 09:15 UTC by greenercode

**What?**

Specify emissions for business travel.

**Why**

Making the distinction between EFs that include indirect effects of non-CO2 emissions and those that include direct effects of CO2, CH4 and N2O emissions only (change within the description).

2021-09-23 10:29 UTC, patstirling requested changes
There is a larger problem here of consistency of IDs for air travel. Suggest we change them in this pull request. To wit:

Suggest all IDs in the air travel category be changed to a standardised format which clarifies:

- [haul length]
- [domestic/international]
- [travel class/average]
- [with-contrails/without-contrails]

Please review all Air Travel lines to ensure consistency in both IDs and descriptions

2021-09-23 10:41 UTC, grindcode commented
The currently used assumption is that contrails should be taking into account as a default.

For this reason, an option to go about this:
- Provide no further specification for EFs that contain contrails in the methodology.
- Provide `-without-contrails` as a suffix for EFs that do NOT contain contrails in the methodology.

Open for discussion.

2021-09-23 14:17 UTC, patstirling commented
> The currently used assumption is that contrails should be taken into account as a default.
> 
> For this reason, an option to go about this:
> 
> * Provide no further specification for EFs that contain contrails in the methodology.
> * Provide `-without-contrails` as a suffix for EFs that do NOT contain contrails in the methodology.
> 
> Open for discussion.

Agreed - this is neater and defaults to the reality (forces people to deliberately choose the less complete version

2021-09-23 14:57 UTC, patstirling requested changes
Line 418 - does this need "uk-" at beginning? Region is GB so this specifies country. I think "domestic-flight-average-passenger

Line 967 - think "to-from-non-uk-" is a bit laboured; "international-outside-uk" would be easier to understand. Note 966, 968, 969 and 975 are also "international-outside-uk" according to their descriptions

Line 1000, 1003-1006, 1152-1154, 1158-1160 - can we conform to format here e.g. "long-haul-flight-international-average-passenger-without-contrails". See note above about "uk-" at beginning. Note position of "flight" should be consistent

Can we also update air travel EFs from other sources to align with the format above. Eg. 10, 419-422, 970-974, 976-978, 1001-1002, 1032-1033, 1155-1157 & 1303-1304

2021-09-23 15:48 UTC, maryarbab approved these changes

2021-09-30 11:38 UTC, patstirling requested changes

2021-09-30 11:38 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> -Energy,Electricity,grid-mix,Grid Mix,kg-CO2e/kwh,0.22,10,ADEME
this should read "non-uk countries" and we should make clear that BEIS does not make any distinctions between short-, medium- or long-haul flights; we should add this in the descriptions of all lines that this applies to

2021-09-30 11:46 UTC, patstirling approved these changes

2021-09-30 11:47 UTC, merged