Resolve esoteric IDs in the Road Travel
climatiq/Open-Emission-Factors-DB pull request #51
Opened 2021-11-10 16:16 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [x] Update

**What category or categories does it affect?**

Road Travel

**What?**

Resolve esoteric IDs in the fuel category

**Why?**

Provide better comparability across EFs

2021-11-10 17:20 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-11-10 17:27 UTC, patstirling requested changes

2021-11-10 17:27 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_petrol_transport,Aviation petrol,kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation petrol. Published by the Ministry for the Environment of New
This change is outside the Road Travel category - likely to cause conflicts!

2021-11-10 17:27 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_commuter_rail-fuel_source_unknown,Commuter rail passenger train,kg-CO2e/pmile,0.143,,EPA,2021,US,2021/08/23,Emission intensity for commuter rail passe
This change is outside the Road Travel category - likely to cause conflicts! There are a number of these below...

2021-11-10 18:57 UTC, patstirling requested changes
Just one change still outside the category!

2021-11-10 18:57 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Fuel,fuel_type_aviation_petrol_transport,Aviation petrol,kg-CO2e/l,2.3123049,,MfE,2020,NZ,2021/09/10,Emission intensity of aviation petrol. Published by the Ministry for the Environment of New
This change still needs to be removed as it clashes with 49

2021-11-11 08:35 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_commuter_rail-fuel_source_unknown,Commuter rail passenger train,kg-CO2e/pmile,0.143,,EPA,2021,US,2021/08/23,Emission intensity for commuter rail passe
should be resolved now!

2021-11-11 08:35 UTC, AnastasiaLobanova approved these changes

2021-11-11 09:19 UTC, patstirling approved these changes

2021-11-11 09:28 UTC, merged