Include BEIS construction waste data
climatiq/Open-Emission-Factors-DB pull request #73
Opened 2021-11-18 08:47 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

Waste

**What?**

Include waste disposal emission factors from construction (BEIS, 2021). 

**Why?**

The inclusion of the BEIS waste data is essential for the construction sector.

2021-11-18 16:32 UTC, patstirling requested changes
See comments below on categorisation and other aspects.

A more general update is detailed here:

ID structure will need to be updated to reflect the method of disposal (this is not LCA activity, but an aspect of the method of waste disposal). This also means there are a lot of identical lines in here (activity does not provide uniqueness).

Suggest, for example:

`waste_type_metal_mixed_cans-disposal_method_open_loop`
`waste_type_metal_mixed_cans-disposal_method_closed_loop`
`waste_type_metal_mixed_cans-disposal_method_landfill`
`waste_type_metal_mixed_cans-disposal_method_combustion`

Any acronyms or initialisms used in the `ID` field (such as "hdpe") will need to be added to the glossary in this PR, [here](https://github.com/climatiq/Open-Emission-Factors-DB/blob/greenercode-BEIS-construction-waste/ID_STRUCTURE_GUIDANCE.md).

Activity will need to be updated to be in line with BEIS guidance (linked to you separately in [this doc](https://docs.google.com/spreadsheets/d/1yAvWLuov_CVdwnDfrZZiCrkNZQI-Tr-j/edit#gid=216654049)).

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_weee_fridges_and_freezers-waste_use_disposal,WEEE - fridges and freezers,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for WEEE - fridges and freezers
Please provide full description of "WEEE" in description field for these EFs (1342-1352)

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_hdpe_including_forming-waste_use_disposal,HDPE (incl. forming),kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for HDPE including forming (open-loop). A
Please provide full terms for "HDPE", "LDPE", "LLDPE", "PET", "PP" and "PVC" for lines 1383-1406

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_books-waste_use_disposal,Books,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for books waste (closed-loop). Available in BEIS Greenhouse Gas Reporting
From lines 1309-1318, BEIS category is "Other" - suggest this be "General waste" to be clearer

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_household_residual_waste-waste_use_disposal,Household residual waste,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for household residual waste (open-
From line 1319 - 1341, BEIS category is "Refuse". Suggest these go into "General waste" category.

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_weee_fridges_and_freezers-waste_use_disposal,WEEE - fridges and freezers,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for WEEE - fridges and freezers
From line 1342 - 1354 BEIS category is "Electrical items" - suggest category "Electrical Waste"

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_metal_aluminium_cans_and foil_excluding_forming-waste_use_disposal,Metal: aluminium cans and foil (excl. forming),kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission
From 1355 - 1370 BEIS category is "Metal" - suggest we use "Metal Waste"

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_average_plastics-waste_use_disposal,Average plastics,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for average plastics (open-loop). Available in BEIS
From line 1371 - 1406 BEIS category is "Plastic" suggest we us "Plastic Waste"

2021-11-18 16:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_board-waste_use_disposal,Board,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for board waste (closed-loop). Available in BEIS Greenhouse Gas Reporting
From lines 1407 - 1418 the BEIS category is "Paper" suggest we use "Paper and Cardboard Waste"

2021-11-18 17:33 UTC, maryarbab requested changes
To add one note to Pat's general comments: let's avoid using "average" in EFs to be consistent with the latest release. 
Also let's check the very high values...

2021-11-18 18:28 UTC, AnastasiaLobanova requested changes
Great job Stefan!! I have one additional comment - some descriptions are missing info that these are Emissions from waste. Would be great to adjust them! Thank you!

2021-11-18 18:28 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_weee_fridges_and_freezers-waste_use_disposal,WEEE - fridges and freezers,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for WEEE - fridges and freezers
I think from the description for lines 1342-1352 it is not clear that these are emissions from waste:

suggest "Emission intensity for WEEE - fridges and freezers (open-loop) waste disposal"

2021-11-18 18:28 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_metal_aluminium_cans_and foil_excluding_forming-waste_use_disposal,Metal: aluminium cans and foil (excl. forming),kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission
The same comment with the descriptions for lines 1353-1371, I think in the description if should be stated somewhere that it is "Emission intensity of waste..."

2021-11-19 08:58 UTC, patstirling commented
NB. the name and description of this PR should be changed to reflect that more than construction waste is being added.

2021-11-22 14:58 UTC, patstirling requested changes
Please review all name and description fields to make sure that the disposal method is reflected. E.g. for `waste_type_metal_mixed_cans-disposal_method_open_loop` would expect to see name: "Metal waste disposal (mixed cans) - open loop" in the name and similar detail in the description (currently all mixed cans lines are identical)

2021-11-22 14:58 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Electrical Items Waste,waste_type_weee_fridges_and_freezers-disposal_method_open_loop,WEEE (fridges and freezers),kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for waste from elect
Suggest "Electrical Waste" for this category rather than "Electricl Items Waste"

2021-11-22 16:05 UTC, maryarbab requested changes

2021-11-22 16:05 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Waste,Metal Waste,waste_type_metal_aluminium_cans_and foil_excluding_forming-disposal_method_open_loop,Metal: aluminium cans and foil waste (excl. forming),kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emi
waste_type_metal_aluminium_cans_and foil_excluding_forming-disposal_method_open_loop -> waste_type_metal_aluminium_cans_and_foil_excluding_forming-disposal_method_open_loop (there are bunch of these)

2021-11-22 17:19 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-11-23 08:32 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Waste,Construction Waste,waste_type_construction-disposal_method_open-loop,Construction waste,kg-CO2e/t,1,,BEIS,2021,GB,2021/11/18,Emission intensity for construction waste. Available in BEIS Greenho
To be addressed in LCA reviewing. _For landfill, the factors in the tables include collection, transportation and landfill emissions (‘gate to grave’). For combustion and recycling, the factors consider transport to an energy recovery or materials reclamation facility only. This is in line with GHG Protocol Guidelines, with subsequent emissions attributed to electricity generation or recycled material production respectively._

2021-11-23 09:54 UTC, maryarbab submitted a review, later dismissed

2021-11-24 13:15 UTC, patstirling requested changes
Very close now - just a couple of things to fix in the guidance and one clarification in the Paper and Cardboard EFs

2021-11-24 13:15 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Paper and Cardboard Waste,waste_type_board-disposal_method_closed_loop,Board waste disposal - closed-loop,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity for board waste disposal - c
For the "Paper and Cardboard Waste" section all instances of "board" in the ID, name or description be replaced with "cardboard" - this avoids confusion with other kinds of board (e.g. plaster)

2021-11-24 14:18 UTC, patstirling requested changes

2021-11-24 14:18 UTC, patstirling commented on ID_STRUCTURE_GUIDANCE.md
> +`waste_type[e.g."aggregates"]-disposal_method_[e.g."open-loop"]`
Just missing that hyphen between waste type and example:

`waste_type_[e.g."aggregates"]-disposal_method_[e.g."open-loop"]`

2021-11-24 14:18 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Waste,Paper and Cardboard Waste,waste_type_paper_and_cardboard-disposal_method_closed_loop,Paper and Cardboard waste disposal - closed-loop,kg-CO2e/t,21.3,,BEIS,2021,GB,2021/11/18,Emission intensity
Decapitalise "Cardboard" in `name` 1411-1414

2021-11-24 14:23 UTC, patstirling approved these changes

2021-11-24 14:24 UTC, merged