Adding DEFRA/BEIS spend-based EFs to OEFDB
climatiq/Open-Emission-Factors-DB pull request #74
Opened 2021-11-24 14:29 UTC by AnastasiaLobanova

**Is this a new addition or an update to an existing factor?**

- [x] New
- [ ] Update

**What category or categories does it affect?**

Several categories 

**What?**

Adding spend-based EFs to the OEFDB from DEFRA/BEIS source

**Why?**

There is a growing interest for these EFs in the industry

2021-11-24 14:49 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +in_review,Insurance and financial services,spend_based-type_changes_in_inventories_not_clear, Changes in inventories NOT CLEAR,kgCO2e/pound,0.396,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purc
Perhaps having _unspecified_  here- this makes the reporting of these the more challenging - if they remain unspecific. This is also pure semantics and not a priority..

2021-11-24 14:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Insurance and financial services,spend_based-type_changes_in_inventories_not_clear, Changes in inventories NOT CLEAR,kgCO2e/pound,0.396,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purc
Yes, I just marked those that needed checking. The "not_clear" has to go before the merge

2021-11-24 18:50 UTC, patstirling reviewed
General coments:

- unit should be kgCO2e/GBP
- source should be BEIS - or Uni of Leeds?
- remove rogue "s and ,s and spaces from all fields

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Food and non-alcoholic beverages,spend_based-type_rice, Rice,kgCO2e/pound,0.154,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: rice. In actual prices in £s,
Suggest sector: Consumer goods

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Clothing and footwear,spend_based-type_mens_outer_garments, Mens outer garments,kgCO2e/pound,0.278,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: mens outer
Suggest sector: "Consumer goods"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Housing,spend_based-type_actual_rentals, Actual rentals,kgCO2e/pound,0.162,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: actual rentals. In actual prices in
Suggest sector "Buildings and housing"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Health,spend_based-type_nhs_prescription_charges_and_payments, NHS prescription charges and payments,kgCO2e/pound,2.548,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and
Suggest sector Suggest that these go into sector "Health and social care" and category "Health care"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Education,spend_based-type_education, Education,kgCO2e/pound,0.297,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: education. In actual prices in £s, includin
Suggest sector "Education" and category "Education" for these 2 EFs

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Food and beverage services,spend_based-type_restaurant_and_cafe_meals, Restaurant and cafe meals,kgCO2e/pound,0.43,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and servi
Suggest sector "Restaurants and accommodation" and category "Food and beverage services"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Accommodation,spend_based-type_holiday_in_the_uk, Holiday in the UK,kgCO2e/pound,0.425,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: holiday in the uk. In a
Suggest sector "Restaurants and accommodation" and category "Accommodation" for these 3 EFs.

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Personal care & social protection & other,spend_based-type_hairdressing_beauty_treatment," Hairdressing, beauty treatment",kgCO2e/pound,0.314,,DEFRA,2018,UK,2021/11/10,"Emission intensity o
Suggest sector "Consumer goods" and "Personal care and accessories" for these 20 EFs (note they are a bit mixed up)

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Insurance and financial services,spend_based-type_residential_homes_not_clear, Residential homes NOT CLEAR,kgCO2e/pound,0.432,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased good
Not sure what the "NOT CLEAR" refers to here - but there appears to be several EFs between the "Personal care & social protection & other" and "Insurance and financial services" categories. Suggest that these go into sector "Health and social care" category "Social care"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Personal care & social protection & other,spend_based-type_home_help, Home help,kgCO2e/pound,0.432,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: home help.
Suggest sector "Health and social care" category "Social care"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Personal care & social protection & other,spend_based-type_nursery_creche_play_schools_not_clear," Nursery, creche, play schools NOT CLEAR",kgCO2e/pound,0.432,,DEFRA,2018,UK,2021/11/10,"Emi
Suggest sector "Health and social care" category "Social care"

2021-11-24 18:50 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +in_review,Insurance and financial services,spend_based-type_structure_insurance, Structure insurance,kgCO2e/pound,0.143,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services:
Suggest sector "Insurance and financial services" categories "Insurance" and "Financial services" for these EFs

2021-11-25 15:46 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Vehicles,spend_based-type_new_cars_vans_outright_purchase, New cars/vans outright purchase,kgCO2e/pound,0.26,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods and services: n
I will do in this PR "Vehicle" and we can change Vehicle -> Vehicles in the next one, not to mix things!

2021-11-25 15:49 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Alcoholic beverages & tobacco and narcotics,spend_based-type_spirits_and_liqueurs, Spirits and liqueurs,kgCO2e/pound,0.08,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased goods an
done

2021-11-25 16:06 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Personal care & social protection & other,spend_based-type_hairdressing_beauty_treatment," Hairdressing, beauty treatment",kgCO2e/pound,0.314,,DEFRA,2018,UK,2021/11/10,"Emission intensity o
I think hairdressing is a service. Shall we leave sector "Consumer goods and services"?

2021-11-26 15:47 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Water OR Building services,spend_based-type_paraffin_weed_peat_hot_water," Paraffin, weed, peat, hot water ",kgCO2e/pound,0.528,,DEFRA,2018,UK,2021/11/10,"Emission intensity of purchased go
I am deleting it for now, looks indeed weird...!

2021-11-26 15:59 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +in_review,Road travel OR Rail travel OR Sea travel OR Air travel,spend_based-type_combined_fares_other_than_season_tickets, Combined fares other than season tickets,kgCO2e/pound,9.496,,DEFRA,2018,UK,
deleted

2021-11-29 14:21 UTC, patstirling requested changes
Fabulous work! Some sensible solutions to tricky problems here. Really like the new description; a couple of small edits, suggest following for last 2 sentences: 

Caution! These EFs are modelled and may represent an average value across an entire category of goods or services. This is a limitation stemming from mismatches in the fidelity of datasets included in the modelling.

2021-11-29 15:12 UTC, greenercode submitted a review, later dismissed

2021-11-30 13:10 UTC, patstirling requested changes

2021-11-30 13:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Recreation and Culture,type_purchase_of_motor_caravan_loan_hp,Purchase of motor caravan-loan/HP,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain i
This has an EF value of "-0" which reflects the source GHG e column - however the source CO2 column is non-zero, which means something has gone wrong. This is a very esoteric EF - suggest we remove it.

2021-11-30 13:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Health and Social Care,Health Care,type_other_health_services,Other health services,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: other health services. I
This has an EF value of "-0" which reflects the source GHG e column - however the source CO2 column is non-zero, which means something has gone wrong. Suggest we match it's value with the others in it's category (which are identical in CO2 values)

2021-11-30 13:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_repair_of_glassware_tableware_and_household_utensils,Repair of glassware tableware and household utensils,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/1
This has an EF value of "-0" which reflects the source GHG e column - however the source CO2 column is non-zero, which means something has gone wrong. Suggest we match it's value with the others in it's category (which are identical in CO2 values)

2021-11-30 13:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Insurance and Financial Services,Financial Services,type_credit_card_fees,Credit card fees,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: credit card fees.
This has an EF value of "-0" which reflects the source, but is nonsensical. Suggest we remove.

2021-11-30 13:10 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Recreation and Culture,type_video_recorder,Video recorder,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: video recorder. In act
This has an EF value of "-0" which reflects the source, but is nonsensical. Suggest we remove.

2021-11-30 23:39 UTC, maryarbab requested changes

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Buildings and Housing,Housing,type_actual_rentals,Actual rentals,kgCO2e/GBP,0.162,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: actual rentals. In actual prices in £s a
Great work, Anastasia! How about to just have "Buildings" as the sector name and the "Housing" just for the category field?

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Buildings and Housing,Housing,type_actual_rentals,Actual rentals,kgCO2e/GBP,0.162,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: actual rentals. In actual prices in £s a
Also, we keep Housing in the sector name, then "Furnishings and Household" can be included in that sector too...

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Information and Communication ,Information and Communication Services,type_postal_services,Postal services,kgCO2e/GBP,0.481,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on
I think sector and category should be switched in this row...

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_other_major_electrical_appliances_eg_dish_washers_microwaves_vacuum_cleaners_heaters,Other major electrical appliances eg dish washers micro
how about including the example just in the name and description, not within the ID?

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_disinfectants_polishes_other_cleaning_materials_some_pest_controls,Disinfectants polishes other cleaning materials some pest controls,kgCO2e
Does the name make sense?:)

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_domestic_services_including_cleaners_gardeners_au_pairs,Domestic services including cleaners gardeners au pairs,kgCO2e/GBP,0.031,,BEIS,2018,
What does "au" mean here?

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_carpet_cleaning__ironing_service_and_window_cleaner,Carpet cleaning  ironing service and window cleaner,kgCO2e/GBP,0.031,,BEIS,2018,UK,2021/
There is an extra "_" in the ID.

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Vehicle Maintenance and Services,type_diesel_oil,Diesel oil,kgCO2e/GBP,0.918,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: diesel oil. In ac
Does this mean an oil change for example?

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Personal Care and Accessories,type_prams_pram_accessories,Prams pram accessories,kgCO2e/GBP,0.335,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend
just "Pram accessories" in the name?

2021-11-30 23:39 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Food and Non-Alcoholic Beverages,type_rice,Rice,kgCO2e/GBP,0.154,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: rice. In actual prices in £s
Should we keep "DEFRA" in the description?

2021-12-01 07:49 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Furnishings and Household,type_domestic_services_including_cleaners_gardeners_au_pairs,Domestic services including cleaners gardeners au pairs,kgCO2e/GBP,0.031,,BEIS,2018,
It is Au pair - helper from a foreign country

2021-12-01 07:51 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Food and Non-Alcoholic Beverages,type_rice,Rice,kgCO2e/GBP,0.154,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: rice. In actual prices in £s
I think - yes, bc in the website their email is specified as the one responsible for answering questions.

2021-12-01 10:56 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Buildings and Housing,Housing,type_actual_rentals,Actual rentals,kgCO2e/GBP,0.162,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: actual rentals. In actual prices in £s a
I see the point! But also to keep the Furnishings and Household goods within Consumer Good and Services appears to me valid. 

I have changed Building and Housing sector to just Buildings to match the existing sector - Buildings. great catch!

2021-12-01 10:59 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Information and Communication ,Information and Communication Services,type_postal_services,Postal services,kgCO2e/GBP,0.481,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on
I would avoid creating another sector with identical name to a Category. I hope it is ok!

2021-12-01 11:01 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Vehicle Maintenance and Services,type_diesel_oil,Diesel oil,kgCO2e/GBP,0.918,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend on: diesel oil. In ac
I guess it is about just buying the oil. I don't think it is about the service itself

2021-12-01 11:16 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Recreation and Culture,type_purchase_of_motor_caravan_loan_hp,Purchase of motor caravan-loan/HP,kgCO2e/GBP,-0,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain i
For this and line 1489, can we replace name with "Purchase (outright) of motorhome or caravan" and "Purchase (loan/HP) of motor caravan" - we will need to make sure the ID and descriptions match; "hp" in description should be "hire purchase"

2021-12-01 11:17 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Consumer Goods and Services,Personal Care and Accessories,type_prams_pram_accessories,Prams pram accessories,kgCO2e/GBP,0.335,,BEIS,2018,UK,2021/11/10,Emission intensity of supply chain in GBP spend
I have changed to "Prams and Pram accessories"

2021-12-01 23:41 UTC, maryarbab approved these changes

2021-12-02 14:43 UTC, AnastasiaLobanova reviewed
Thank you Pat for the work! Looks great and clean. I have two  suggestions:

- I think we need to be very clear and specify in the description that this is not the data provided by BEIS in their report, but our aggregates based on their data. 
- Why do we need the specification of sub-sector or sub-category in the first part of ID? Is it better for the API? 

Thank you


Happy to

2021-12-02 15:32 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_vehicle-vehicle_type_taxi_or_hired_car_van_bicycle-fuel_source_na-distance_short-engine_size_na,Taxis and hire cars/vans/bikes,,kgCO2e/GBP,0.705,,BEIS,2018,UK,2021/11/
Ah - in this instance I aligned with what we already have for the accommodation category - but I agree to confirm with the general ID format of "thing_it_is-type_detail_of_thing" this should be changed for the whole category (there will be PRs following this one to align the various categories where needed)

2021-12-02 15:39 UTC, patstirling approved these changes

2021-12-02 15:41 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_vehicle-vehicle_type_taxi_or_hired_car_van_bicycle-fuel_source_na-distance_short-engine_size_na,Taxis and hire cars/vans/bikes,,kgCO2e/GBP,0.705,,BEIS,2018,UK,2021/11/
Finally - yes, I will add that we have grouped EFs in the description, good call

2021-12-02 15:59 UTC, patstirling approved these changes

2021-12-02 16:18 UTC, maryarbab approved these changes

2021-12-02 16:25 UTC, grindcode approved these changes

2021-12-02 16:25 UTC, merged