Adding LCA activity column
climatiq/Open-Emission-Factors-DB pull request #79
Opened 2021-12-01 06:33 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [*] New
- [ ] Update

**What category or categories does it affect?**

All

**What?**

Adding LCA activity for each emission factor based on the information that the source provides.

**Why?**

The user knows exactly what each emission factor refers to in terms of LCA activity.

2021-12-01 11:04 UTC, patstirling requested changes
Completely amazing work! Couple of thoughts in comments - also, could you update the DATA_GUIDANCE doc within the pull request to reflect these changes?

2021-12-01 11:04 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Travel,passenger_vehicle-vehicle_type_city_bus-fuel_source_bev-distance_na-engine_size_na,Electric city bus,kg-CO2e/pkm,0.0217,70,ADEME,2018,FR,2021/08/20,Emission Intensity of electri
manufactuing -> manufacturing

2021-12-01 11:04 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_car-fuel_source_fcev_smr_centralized_natural_gas-engine_size_na-vehicle_age_na-vehicle_weight_na,Hydrogen car (SMR centralized natural gas),kg-CO2e/km
Is "vehicle_manufacturing" too specific? Could we use "manufacturing" as a more general term, as I imagine we'll have EFs reflecting the manufacture of all sorts of things in the future.

2021-12-01 13:18 UTC, AnastasiaLobanova requested changes
Thank you Maryam!! Great piece of work! Should be very helpful for the user to orient and also will save loooots of time for the users.

I have two general comments:

I suggest no spaces in header - better for the automatic processing i.e. LCA activity -> LCA_activity

I am not 100% clear on how the hyphens and underscores are used? Hyphens to separate different LCA phases? Then I don't understand this one: upstream-vehicle_manufacturing - here the vehicle manufacturing is not upstream? Or what is meant by upstream here? 


Small comment: 

There are some extra spaces at the end of the "upstream-vehicle_manufacturing "

2021-12-01 18:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Vehicle,passenger_vehicle-vehicle_type_car-fuel_source_fcev_smr_centralized_natural_gas-engine_size_na-vehicle_age_na-vehicle_weight_na,Hydrogen car (SMR centralized natural gas),kg-CO2e/km
Good point. Actually, ADEME has both "vehicle manufacturing" and "manufacturing" for EFs. I decided to have it all as "vehicle manufacturing" to be consistent as I could not think of any other manufacturing activity for these factors. But I can change that to "manufacture" to be inclusive. The other point is that in this column we are trying to keep activities as close as possible to the source and then group them in the LCA boundary column. Any thoughts?

2021-12-02 10:04 UTC, AnastasiaLobanova submitted a review, later dismissed

2021-12-02 16:20 UTC, patstirling requested changes
small change to column header - also to "manufacturing" as discussed

2021-12-02 17:09 UTC, patstirling submitted a review, later dismissed

2021-12-02 17:21 UTC, patstirling approved these changes

2021-12-02 17:28 UTC, merged