Adding BEIS heat and steam & water supply
climatiq/Open-Emission-Factors-DB pull request #83
Opened 2021-12-03 16:17 UTC by patstirling

**Is this a new addition or an update to an existing factor?**

- [X] New
- [ ] Update

**What category or categories does it affect?**

Energy, Water

**What?**

Adding BEIS values for these categories

**Why?**

_Please give a brief explanation of why these changes are valuable or necessary_

2021-12-03 17:16 UTC, grindcode requested changes
Duplicated EF + broken source links.

2021-12-03 17:16 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/ML,149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
This EF is a duplicated of the previous one, simply in a different unit but same type (Volume). I would argue there is no value in adding this.

2021-12-03 17:16 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/m3,0.149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https:
Source link is broken

2021-12-03 17:16 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/ML,149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
Source link is broken

2021-12-03 17:24 UTC, maryarbab requested changes

2021-12-03 17:24 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/ML,149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
Agree. Also, does the source mention any details about the upstream activities?

2021-12-07 11:39 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/ML,149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https://
Have removed duplicate and updated descriptions/lca in line with https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/990675/2021-ghg-conversion-factors-methodology.pdf - please do review!

2021-12-07 11:40 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Water,Water Supply,water-supply,Water supply,kg-CO2e/m3,0.149,,BEIS,2021,GB,2021/11/25,Emission intensity for water supply. Available in BEIS Greenhouse Gas Reporting: Conversion Factors 2021.,https:
Links fixed

2021-12-07 11:57 UTC, grindcode requested changes

2021-12-07 11:57 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_onsite_wtt,Onsite heat and steam (WTT),kg-CO2e/kWh,0.03153,,BEIS,2021,GB,2021/11/25,Emission intensity for Well-to-Tank - onsite heat and steam. Available in
source link is broken

2021-12-07 11:57 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt,District heat and steam (WTT),kg-CO2e/kWh,0.03153,,BEIS,2021,GB,2021/11/25,Emission intensity for Well-to-Tank - district heat and steam. Availa
source link is broken

2021-12-07 11:57 UTC, grindcode commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_district_wtt_distribution_5percent_loss,District heat & steam (WTT; distribution 5% loss),kg-CO2e/kWh,0.00166,,BEIS,2021,GB,2021/11/25,Emission intensity for
source link is broken

2021-12-07 12:35 UTC, grindcode approved these changes

2021-12-07 14:29 UTC, maryarbab requested changes

2021-12-07 14:29 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Water,Water Treatment,water-treatment,Water treatment,kg-CO2e/m3,0.272,,BEIS,2021,GB,2021/07/23,Emission Intensity of water treatment in the UK in 2021. Based on emissions associated with offices/tra
Looks great! My only comment is that the water treatment here sounds to be more related to the end-of-life processes.

2021-12-07 15:10 UTC, maryarbab approved these changes

2021-12-07 15:14 UTC, merged