Update DATA_GUIDANCE.md
climatiq/Open-Emission-Factors-DB pull request #84
Opened 2021-12-06 16:05 UTC by maryarbab

**Is this a new addition or an update to an existing factor?**

- [ ] New
- [*] Update

**What category or categories does it affect?**

_All_

**What?**

_Add some notes about the lca_activity column, which has been recently added to the OEFDB._

**Why?**

_To clarify what type of information the lca-activity column includes._

2021-12-06 16:14 UTC, greenercode submitted a review, later dismissed

2021-12-07 11:30 UTC, grindcode submitted a review, later dismissed

2021-12-07 14:28 UTC, patstirling requested changes

2021-12-07 17:13 UTC, patstirling commented on DATA_GUIDANCE.md
> +Life cycle assessment activity that each emission factor refers to, ranging from cradle to grave such as upstream (e.g. `fuel_upstream` or `manufacturing`), use phase (e.g. `fuel_combustion`), and en
I don't mind keeping it, just the first part of the sentence runs into the second and makes it confusing. Suggest:

"Life cycle assessment activity to which the emission factor applies. This can be one or several phases from "cradle" to "grave", including upstream (e.g. `fuel_upstream` or `manufacturing`), use phase (e.g. `fuel_combustion`), and end-of-life (e.g. `end_of_life` or `gate_to_grave`) emissions. If the source does not provide such information, the field is marked as `unknown`. "

2021-12-08 10:35 UTC, patstirling approved these changes

2021-12-08 11:15 UTC, merged