Include main line train travel EFs (France)
climatiq/Open-Emission-Factors-DB pull request #89
Opened 2021-12-08 14:35 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

rail travel 

**What?**

Support main line train travel (region: France)

**Why?**

Up until now, the OEFDB did not support these main french rail travel emission factors.

2021-12-09 09:16 UTC, maryarbab requested changes

2021-12-09 09:16 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_mainline-route_location_na-fuel_source_na,Mainline train,kg-CO2e/pkm,0.00529,20,ADEME,2020,FR,2021/11/30,"Emission intensity for mainline train train
There is double “train”s in the description.

2021-12-09 09:16 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_mainline-route_location_na-fuel_source_na,Mainline train,kg-CO2e/pkm,0.00529,20,ADEME,2020,FR,2021/11/30,"Emission intensity for mainline train train
It seems that we do not have the “route_location” for other ids in this category.

2021-12-09 09:16 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-route_location_na-fuel_source_na,High speed train ,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,"Emission intensity for high speed train
Do we need 2019 in the description?

2021-12-09 09:16 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-route_location_paris_and_suburbs-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),kg-CO2e/pkm,0.0041,20,ADEME,
Does the source mention “upstream electricity generation”? I wonder this refers to fuel upstream for elec generation or fuel combustion for electricity generation.

2021-12-09 09:27 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-route_location_paris_and_suburbs-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),kg-CO2e/pkm,0.0041,20,ADEME,
It is unclear - this is what we decided with @patstirling yesterday.

2021-12-09 09:41 UTC, AnastasiaLobanova requested changes
Good job Stephane! Thank you!

Please fish those commas out of description and name fields :)

2021-12-09 09:41 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-route_location_na-fuel_source_na,High speed train ,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,"Emission intensity for high speed train
There is an extra space at the end of the name field and also commas int he description.

2021-12-09 09:41 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-fuel_source_na,High speed train,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,"Emission intensity for high speed train including upstream
There are commas in the description field

2021-12-09 10:36 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-route_location_paris_and_suburbs-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),kg-CO2e/pkm,0.0041,20,ADEME,
Hi both - here's the mothodology that ADEME cites from SNCF: http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf - this is what ADEME refer to in their methodology. The key bit is "(Consommation d’électricité x facteur d’émission de CO2e de l’électricité à usage transport + Consommation gasoil x Facteur d’émission du gasoil) / Voyageurs x km =
Emission d’un voyageur par type de train exprimé en gramme de CO2e /km". This implies that these EFs are the addition of the emissions of the electricity used (which is implicitly upstream) and the combustion of fuel in use-phase (but NOT upstream costs of fuel). How would you advise this be reflected in the lca field @maryarbab ?

2021-12-09 10:42 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-route_location_na-fuel_source_na,High speed train ,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,"Emission intensity for high speed train
These do feel like a very long descriptions. Remember that the description field only needs to provide detail not already in the other fields that a user might need to help choose the right EF, or clarify source (e.g. by exploding initialisms like ADEME). Suggest we remove the reference to 2019 and remove "This emission factor does not include the manufacture of rolling stock or emissions related to the infrastructure (railway tracks stations etc.). Provided by the GT Transport Base Carbone & InfoGES SNCF." from all EFs

2021-12-09 13:28 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_high_speed-route_location_na-fuel_source_na,High speed train ,kg-CO2e/pkm,0.00173,20,ADEME,2020,FR,2021/11/30,"Emission intensity for high speed train
Addressed this.

2021-12-09 22:44 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-route_location_paris_and_suburbs-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),kg-CO2e/pkm,0.0041,20,ADEME,
My suggestion is: electricity_generation-fuel_combustion.

2021-12-10 14:55 UTC, patstirling approved these changes

2021-12-13 08:06 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_rer_and_transilien-route_location_paris_and_suburbs-fuel_source_na,RER (Paris area) and Transilien (suburban-train lines),kg-CO2e/pkm,0.0041,20,ADEME,
Do we agree to have electricity_generation-fuel_combustion as the LCA activity? It still seems to be upstream-fuel_combustion in the lca activity field.

2021-12-13 09:58 UTC, AnastasiaLobanova approved these changes

2021-12-13 18:44 UTC, maryarbab approved these changes

2021-12-14 07:15 UTC, merged