Sea transport erroneous units
climatiq/Open-Emission-Factors-DB pull request #91
Opened 2021-12-09 10:13 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

[x] Update

**What category or categories does it affect?**

Sea transport 

**What?**

A couple of identified erroneous units, essentially coming from this source https://www.smartfreightcentre.org/pdf/GLEC-report-on-GHG-Emission-Factors-for-Inland-Waterways-Transport-SFC2018.pdf. For one BEIS (UK) and one MfE (Nz) EF units were in g-CO2e/tkm instead of kg-CO2e/tkm. I also reviewed the LCA activity format for Well_to_Propeller to well_to_propeller.

**Why?**

The values were incorrect from a scientific perspective.

2021-12-09 11:37 UTC, AnastasiaLobanova requested changes
Is this correct that we have in some cases g-CO2e and in some kg? 

UPD: Ah now I see from the factor value :) Sorry

2021-12-09 11:40 UTC, AnastasiaLobanova approved these changes

2021-12-09 22:22 UTC, maryarbab requested changes
I am still confused: why don't we make the conversion to only have one unit (i.e. kg of CO2eq)?

2021-12-10 07:09 UTC, greenercode commented
> I am still confused: why don't we make the conversion to only have one unit (i.e. kg of CO2eq)?

I can do! But should we not stay truthful to the source considering this is g-CO2e/tkm (just not Kg-CO2e/tkm)? Perhaps this can be easily converted in the API.

2021-12-13 07:56 UTC, maryarbab requested changes

2021-12-13 07:56 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_container_coupled_convoy-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Container vessels coupled convoy,g-CO2e/tkm,19.7,,STC-Nestra B.V.,202
Did we finally decide to have one unit here and convert units or have multiple ones?

2021-12-13 09:50 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_container_coupled_convoy-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Container vessels coupled convoy,g-CO2e/tkm,19.7,,STC-Nestra B.V.,202
Not sure! @maryarbab @patstirling @AnastasiaLobanova do we have a consensus about this? Going by the normalisation argument of the DB we could in fact do the conversions?

2021-12-13 09:59 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_container_coupled_convoy-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Container vessels coupled convoy,g-CO2e/tkm,19.7,,STC-Nestra B.V.,202
I agree with both! Question is - if API is doing it then we do not need to normalise it by hand in my view

2021-12-13 17:14 UTC, patstirling approved these changes

2021-12-13 17:14 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Sea Transport,sea_freight-vessel_type_container_coupled_convoy-route_type_na-vessel_length_na-tonnage_na-fuel_source_na,Container vessels coupled convoy,g-CO2e/tkm,19.7,,STC-Nestra B.V.,202
Let's stay true to the source here (as long as it's correct); the API will take the thinking out of it for folks using it to access the full range of EFs

2021-12-13 18:45 UTC, maryarbab approved these changes

2021-12-14 07:17 UTC, merged