Update UBA train travel name and descriptions
climatiq/Open-Emission-Factors-DB pull request #92
Opened 2021-12-09 10:24 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] Update

**What category or categories does it affect?**

Rail travel

**What?**

Update UBA train travel name and descriptions 

**Why?**

These used to indicate near and remote. This has been modified to local and long distance to improve UX.

2021-12-09 11:36 UTC, AnastasiaLobanova approved these changes

2021-12-09 22:18 UTC, maryarbab requested changes

2021-12-09 22:18 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_diesel,Local passenger train (diesel),kg-CO2e/pkm,0.0713,,UBA,2020,DE,2021/09/15,Emission intensity of local passenger train (diesel
 I would suggest having it as "Diesel local passenger train" and "Diesel long-distance passenger train" to be consistent with the rest (e.g. row 995).

2021-12-10 07:05 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_diesel,Local passenger train (diesel),kg-CO2e/pkm,0.0713,,UBA,2020,DE,2021/09/15,Emission intensity of local passenger train (diesel
@AnastasiaLobanova @patstirling Long- it would be great to have a consensus on order here. I agree with the @maryarbab's consistency argument vis-à-vis the rest of the OEFDB, but not sure whether diesel is the activity? This is why I do not think it should go first in the name column. Please share your thoughts.

2021-12-10 15:01 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_diesel,Local passenger train (diesel),kg-CO2e/pkm,0.0713,,UBA,2020,DE,2021/09/15,Emission intensity of local passenger train (diesel
The standard form from name across the transport sector is to have the fuel type followed by the vehicle type - e.g. "Diesel bus" - suggest we conform to that with "Diesel local passenger train". In description "Emission intensity of diesel local passenger train including fuel combustion and upstream" would be ideal.

2021-12-10 15:04 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_diesel,Local passenger train (diesel),kg-CO2e/pkm,0.0713,,UBA,2020,DE,2021/09/15,Emission intensity of local passenger train (diesel
👌

2021-12-13 07:55 UTC, maryarbab requested changes

2021-12-13 07:55 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_electricity,Electric long-distance passenger train,kg-CO2e/pkm,0.00948,,UBA,2020,DE,2021/09/15,Emission intensity of electri
Does the source mention "electricity consumption"?

2021-12-13 17:24 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_electricity,Electric long-distance passenger train,kg-CO2e/pkm,0.00948,,UBA,2020,DE,2021/09/15,Emission intensity of electri
Opening gambit is that this should align with the "electricity_generation" value for all other electric trains/vehicles in the DB. It's a valid question as to whether generation, T&D and extraction/fuel transportation is included in "electricity_generation" for UBA EFs though - for example BEIS don't include T&D (that's a separate EF)

2021-12-13 18:48 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_electricity,Electric long-distance passenger train,kg-CO2e/pkm,0.00948,,UBA,2020,DE,2021/09/15,Emission intensity of electri
Yes exactly: electricty_consumption happens at the end-user side, taking into account the T&D losses, while electrcity_generation happens at the power plant before any transmission and distribution to the end-user.

2021-12-15 04:11 UTC, maryarbab requested changes

2021-12-15 04:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_diesel,Diesel local passenger train,kg-CO2e/pkm,0.0713,,UBA,2020,DE,2021/09/15,Emission intensity of diesel local passenger train in
LCA activity should be: upstream-fuel_combustion as it is a diesel vehicle not electric

2021-12-15 04:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_diesel,Diesel long-distance passenger train,kg-CO2e/pkm,0.044,,UBA,2020,DE,2021/09/15,Emission intensity of diesel long-dist
LCA activity should be: upstream-fuel_combustion

2021-12-15 04:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_local-fuel_source_electricity,Electric local passenger train,kg-CO2e/pkm,0.0546,,UBA,2020,DE,2021/09/15,Emission intensity of electric local passenger
Suggestion for LCA activity: upstream-electricity_consumption (if consumption is mentioned by the source) or upstream-electricity_generation (if generation is mentioned by the source)

2021-12-15 04:11 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_electricity,Electric long-distance passenger train,kg-CO2e/pkm,0.00948,,UBA,2020,DE,2021/09/15,Emission intensity of electri
Suggestion for LCA activity: upstream-electricity_consumption (if consumption is mentioned by the source) or upstream-electricity_generation (if generation is mentioned by the source)

2021-12-16 14:59 UTC, maryarbab approved these changes

2021-12-16 23:03 UTC, maryarbab approved these changes

2021-12-17 07:17 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_long_distance-fuel_source_diesel,Diesel long-distance passenger train,kg-CO2e/pkm,0.044,,UBA,2020,DE,2021/09/15,Emission intensity of diesel long-dist
Line 993 here - wasn't it that discussion we had about Nahverkehr meaning in German, and we came to a conclusion it means urban trains, e.g. underground trains/trams? 
https://de.wikipedia.org/wiki/Nahverkehr

2021-12-17 09:29 UTC, merged