Include EF for nuclear electricity generation (ADEME)
climatiq/Open-Emission-Factors-DB pull request #93
Opened 2021-12-09 10:59 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Electricity 

**What?**

A single EF for nuclear electricity generation was missing (source: ADEME). 

**Why?**

To have a holistic picture of conventional energy generation sources - this should be included.

2021-12-09 11:35 UTC, AnastasiaLobanova requested changes

2021-12-09 11:35 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_nuclear_fired_plant,Nuclear fired plant,kg-CO2e/kWh,0.006,10,ADEME,2018,FR,2021/11/30,Emission intensity for nuclear fired power plant. The data scope inc
I think it is just Nuclear power plant, not nuclear fired plant :)

2021-12-09 22:15 UTC, maryarbab approved these changes

2021-12-13 10:07 UTC, AnastasiaLobanova approved these changes

2021-12-13 13:29 UTC, merged