Include purchased heat and steam EF (EPA)
climatiq/Open-Emission-Factors-DB pull request #95
Opened 2021-12-10 07:31 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

[x] New

**What category or categories does it affect?**

Heat and steam 

**What?**

Include purchased heat and steam EF (EPA)

**Why?**

This emission factor greatly contributes to the scientific depth of the existing category.

2021-12-10 15:04 UTC, patstirling requested changes
Nice addition! Just a small comment

2021-12-10 15:04 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_purchased,Purchased heat and steam,kg-CO2e/kWh,0.08907,,EPA,2021,US,2021/12/12,Emission intensity for steam or heat purchased per kWh of steam. These factors
the "per kWh of steam" - could this simply be "per kWh", as steam and heat already mentioned in the sentence?

2021-12-10 16:44 UTC, patstirling approved these changes

2021-12-13 07:49 UTC, maryarbab requested changes

2021-12-13 07:49 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_purchased,Purchased heat and steam,kg-CO2e/kWh,0.08907,,EPA,2021,US,2021/12/12,Emission intensity for steam or heat purchased per kWh. This factor assumes na
Does "use-phase" refer to ng combustion?

2021-12-13 17:36 UTC, patstirling requested changes

2021-12-13 17:36 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_purchased,Purchased heat and steam,kg-CO2e/kWh,0.08907,,EPA,2021,US,2021/12/12,Emission intensity for steam or heat purchased per kWh. This factor assumes na
Looks like it does - "fuel_combustion" seems the more accurate; we'd need to understand whether there was any upstream activities (extraction, transmission) accounted for

2021-12-13 18:49 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Energy,Heat and Steam,heat-and-steam-type_purchased,Purchased heat and steam,kg-CO2e/kWh,0.08907,,EPA,2021,US,2021/12/12,Emission intensity for steam or heat purchased per kWh. This factor assumes na
Agree. Let's use fuel_combustion if it is the only activity to be consistent.

2021-12-15 04:14 UTC, maryarbab approved these changes

2021-12-15 15:15 UTC, maryarbab approved these changes

2021-12-15 16:18 UTC, patstirling approved these changes

2021-12-15 16:18 UTC, merged