Include additional HGV EFs (BEIS)
climatiq/Open-Emission-Factors-DB pull request #96
Opened 2021-12-10 09:19 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Road transport 

**What?**

Include additional HGV EFs (BEIS) 

**Why?**

This category was incomplete, and necessitated the inclusion of additional emission factors.

2021-12-10 17:25 UTC, patstirling requested changes

2021-12-10 17:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv_all_art-fuel_source-diesel-vehicle_weight_na-percentage_load_100,Road freight diesel all artics HGV 100% laden,kg-CO2e/tkm,0.05944,,BEIS,2021
ID field: 
- "art" -> "articulated" to conform with existing EFs
 
Name:
- "artics" -> "articulated"
- remove "all"

Description
- remove "all"

This for all the lines these apply to.

2021-12-10 17:25 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport ,Road Transport,freight_vehicle-vehicle_type_hgv_all_art_refrig-fuel_source-diesel-vehicle_weight_na-percentage_load_100,Road freight diesel refrigerated all artics HGV 100% laden,kg-CO2e/t
There's a rogue space after "Transport" in the sector field in this and the following EFs. Also these seem to be not in Sector > Category > Name order?

2021-12-13 07:45 UTC, maryarbab approved these changes

2021-12-13 10:11 UTC, AnastasiaLobanova requested changes

2021-12-13 10:11 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv_rigid-fuel_source-diesel-vehicle_weight_gt_17t-percentage_load_100,Road freight diesel rigid HGV (>17t) 100% laden,kg-CO2e/tkm,0.12009,,BEIS,
1035-1083 - an underscore instead of hyphen is needed between the source and diesel

2021-12-13 10:11 UTC, AnastasiaLobanova commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_hgv_rig-fuel_source-diesel-vehicle_weight_na-percentage_load_na,Road freight diesel rigids HGV 100% average laden,kg-CO2e/tkm,0.2078,,BEIS,2021,G
rig -> rigid to comply with other entries

2021-12-13 17:44 UTC, patstirling requested changes

2021-12-13 17:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.55,,DISER,2018,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
changes outside of the categories intended should be removed to avoid conflicts

2021-12-13 17:44 UTC, patstirling commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_urban-fuel_source_na,Urban passenger train,kg-CO2e/pmile,0.171,,EPA,2021,US,2021/08/23,Emission intensity for average passenger train. This emission f
changes outside of the categories intended should be removed to avoid conflicts

2021-12-13 18:51 UTC, maryarbab approved these changes

2021-12-14 07:24 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Energy,Electricity,electricity-energy_source_dkis_grid_mix,Grid mix,kg-CO2e/kWh,0.55,,DISER,2018,AU-NT,2021/11/30,Emission intensity for the Darwin Katherine Interconnected System (DKIS) grid mix. Pu
Ah, yes. I had already merged this separate (and individual change) while having this PR open. This is why it shows up on all the existing ones...

2021-12-14 07:24 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_urban-fuel_source_na,Urban passenger train,kg-CO2e/pmile,0.171,,EPA,2021,US,2021/08/23,Emission intensity for average passenger train. This emission f
Same comment applies here.

2021-12-15 16:26 UTC, patstirling approved these changes

2021-12-15 16:35 UTC, patstirling approved these changes

2021-12-15 16:35 UTC, merged