Include vans EFs (road transport)
climatiq/Open-Emission-Factors-DB pull request #99
Opened 2021-12-13 14:18 UTC by greenercode

**Is this a new addition or an update to an existing factor?**

- [x] New

**What category or categories does it affect?**

Road transport 

**What?**

Include vans EFs (road transport) from BEIS. 

**Why?**

These EFs were not included yet - and will add an additional level of depth to the road transport category.

2021-12-13 19:01 UTC, maryarbab requested changes

2021-12-13 19:01 UTC, maryarbab commented on OpenEmissionFactorsDB.csv
> +Transport,Road Transport,freight_vehicle-vehicle_type_van-fuel_source_na-vehicle_weight_lt_3.5t,Unknown fuel source - Van (up to 3.5 tonnes),kg-CO2e/tkm,0.60635,,BEIS,2021,GB,2021/12/13,Emission inte
I would have "Average van" in the name.

2021-12-14 07:36 UTC, greenercode commented on OpenEmissionFactorsDB.csv
> +Transport,Rail Travel,passenger_train-route_type_urban-fuel_source_na,Urban passenger train,kg-CO2e/pmile,0.171,,EPA,2021,US,2021/08/23,Emission intensity for average passenger train. This emission f
I would do this in a separate PR - but yes I agree. I think it shows up here but it is related with previous PRs and subsequent changes/additions on the DB being taken into account.

2021-12-15 09:40 UTC, maryarbab approved these changes

2021-12-15 15:24 UTC, merged